export const ARCH = [
  {
    kicker: 'ACT V · SIMULATION ARCHITECTURE',
    title: 'From geospatial data to a real aircraft — one continuous stack',
    sub: 'Every rung uses the artefacts of the rung below. The same flight code that runs in SITL runs on the aircraft, so the only thing that changes between simulation and reality is the world.',
    scene: 'simStack',
    stageTag: 'SIMULATION STACK',
    caption: 'GIS → OSM/GeoJSON → terrain+buildings → traffic → weather+radio → twin → Omniverse/Isaac Sim → Isaac Lab → ROS 2 → PX4/SITL → HITL → real UAV.',
    diagram: {
      type: 'stack',
      title: 'SIMULATION STACK · ARTEFACT PASSED UPWARD',
      bh: 30,
      items: [
        { t: 'GIS (authoritative geography)', s: 'coordinate frames, elevation, land use', r: '→ georeferenced base' },
        { t: 'OpenStreetMap / GeoJSON', s: 'roads, footprints, boundaries', r: '→ vector features' },
        { t: 'Terrain + buildings (USD)', s: 'meshes, materials, collision', r: '→ simulation geometry', cls: 'accent' },
        { t: 'Traffic (SUMO)', s: 'vehicle and crowd flows', r: '→ dynamic actors', cls: 'accent' },
        { t: 'Weather + radio propagation', s: 'wind, rain, path loss, blockage', r: '→ physics fields', cls: 'accent' },
        { t: 'DIGITAL TWIN', s: 'one synchronised scene of record', r: '→ shared world state', cls: 'ok' },
        { t: 'Omniverse / Isaac Sim', s: 'rigid-body physics + sensor rendering', r: '→ sensor streams', cls: 'ok' },
        { t: 'Isaac Lab', s: 'thousands of parallel RL environments', r: '→ trained policies', cls: 'ai' },
        { t: 'ROS 2', s: 'same middleware, same topics as flight', r: '→ integration parity', cls: 'ai' },
        { t: 'PX4 + SITL', s: 'real autopilot firmware, simulated I/O', r: '→ software-in-the-loop', cls: 'warn' },
        { t: 'HITL', s: 'real autopilot hardware, simulated world', r: '→ timing parity', cls: 'warn' },
        { t: 'REAL UAV', s: 'the only test that counts', r: '→ measured sim-to-real gap', cls: 'bad' },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'WHY THIS ORDER', items: ['Geometry before physics — you cannot simulate a channel without buildings', 'Physics before learning — a policy trained on wrong dynamics is worse than none', 'Middleware parity before hardware — most “AI failures” are integration failures'] },
      { h: 'TOOL RESPONSIBILITIES', tone: 'ok', items: ['<b>QGIS</b> geospatial preparation', '<b>SUMO</b> traffic microsimulation', '<b>STK</b> orbits, passes, link windows', '<b>Isaac Sim</b> robotics + sensor physics', '<b>Isaac Lab</b> parallel policy training', '<b>Sionna RT</b> ray-traced radio channels', '<b>PX4 / ROS 2</b> the same code as flight', '<b>CUDA</b> everything above, faster'] },
    ],
    right: [
      { h: 'WHAT MOVES DOWN THE STACK', tone: 'ai', items: ['Trained policies and calibrated parameters', 'Scenario definitions that found failures', 'Fidelity corrections from real flights'] },
      { h: 'THE HONEST PART', tone: 'warn', text: 'The sim-to-real gap is <b>measured</b> at the top and fed back down as a correction, not assumed away. Every fidelity claim has a number attached.' },
    ],
    tech: ['Omniverse / OpenUSD', 'Isaac Sim', 'Isaac Lab', 'SUMO', 'STK', 'QGIS', 'Sionna RT', 'ROS 2', 'PX4 SITL', 'CUDA'],
    metrics: [['&lt;1 m', 'geometry error'], ['&lt;3 dB', 'channel model error'], ['10⁴+', 'parallel envs'], ['&lt;15%', 'sim-to-real policy gap']],
    note: 'Simulation is a production system in this architecture — versioned, validated and continuously corrected against reality.',
    spec: {
      visual: 'A twelve-step staircase of glowing slabs rising from data to a real hovering UAV, with a green data spine climbing alongside.',
      scene3d: 'Slabs 26 → 16 m wide, offset 1.1 m in X per rung to form a staircase; NVIDIA-green spine with packets; a real UAV hovering above the top rung with a pulsing “SIM → REAL GAP” label.',
      components: ['12 stack rungs', 'Tool-responsibility panel', 'Ascending data spine', 'Real UAV at the top'],
      dataflow: 'Artefacts pass upward (geometry → physics → policies → firmware parity); corrections pass downward from the measured gap.',
      animation: ['Packets climb the spine', 'Gap label breathes', 'Slow orbit revealing the staircase depth'],
      text: 'Why this order, tool responsibilities, and the honest treatment of the sim-to-real gap.',
      message: 'One continuous stack with parity at every rung is what makes simulation-trained autonomy trustworthy in the field.',
    },
  },

  {
    kicker: 'ACT V · TECHNOLOGY TOPOLOGY',
    title: 'How the toolchain hangs together',
    sub: 'Six technology families, one platform core. Nothing here is exotic: the differentiator is that they share one world model, one data platform and one deployment path.',
    scene: 'toolConstellation',
    stageTag: 'TOOL CONSTELLATION',
    caption: 'Simulation · robotics · AI · communications · infrastructure · data, all bound to the platform core.',
    left: [
      { h: 'DESIGN CHOICES', items: ['Standards over bespoke: ROS 2, PX4, USD, 3GPP', 'Open weights where certification allows', 'GPU-first: CUDA from PHY to policy training', 'Everything containerised and versioned'] },
    ],
    right: [
      { h: 'INTEGRATION RULES', tone: 'ok', items: ['One coordinate frame authority', 'One time authority', 'One model registry', 'One telemetry schema'] },
      { h: 'RISK', tone: 'warn', text: 'Tool sprawl is the main failure mode of platforms like this. Each family has one designated primary tool and an explicit exit path.' },
    ],
    tech: ['Omniverse', 'Isaac Sim/Lab', 'SUMO', 'STK', 'QGIS', 'ROS 2', 'PX4', 'PyTorch', 'CUDA', 'Sionna', 'Kubernetes'],
    note: 'A technology map is only useful if it also states what is NOT in the platform, and how each choice could be replaced.',
    spec: {
      visual: 'Six technology hubs on a ring around a central platform orb, each hub fanning out to its tools as small nodes.',
      scene3d: 'Hubs at radius 13, tools at radius 19–22 with connecting lines; centre orb r=1.8; holographic ring floor r=16.',
      components: ['6 family hubs', '~30 tool nodes', 'Platform core orb'],
      dataflow: 'Beams from the core to each family hub represent the shared contracts (frames, time, registry, schema).',
      animation: ['Core rings counter-rotate', 'Beam packets flow outward', 'Slow orbit'],
      text: 'Design choices, integration rules, and the tool-sprawl risk.',
      message: 'Standards-based, GPU-first, with one authority per cross-cutting concern.',
    },
  },

  {
    kicker: 'ACT V · AI ARCHITECTURE',
    title: 'From raw data to physical action — the AI stack',
    sub: 'Ten tiers, one direction of travel, and a feedback path that turns outcomes back into data. This is the slide that shows generative AI, agentic AI and physical AI as one pipeline rather than three buzzwords.',
    scene: 'aiStack',
    stageTag: 'AI STACK',
    caption: 'RAW DATA → DATA ENGINEERING → EMBEDDINGS → RAG/VECTOR/KG → FOUNDATION MODELS → SPECIALISED MODELS → AGENTS → MULTI-AGENT ORCHESTRATION → PHYSICAL AI → ACTION.',
    diagram: {
      type: 'stack',
      title: 'AI STACK · WHAT EACH TIER GUARANTEES',
      bh: 32,
      items: [
        { t: 'RAW DATA', s: 'sensors · video · LiDAR · RF · satellite', r: 'time + pose + uncertainty', cls: 'accent' },
        { t: 'DATA ENGINEERING', s: 'clean · align · label · version', r: 'reproducible datasets', cls: 'accent' },
        { t: 'FEATURE / EMBEDDING', s: 'multimodal encoders', r: 'shared representation', cls: 'accent' },
        { t: 'RAG · VECTOR DB · KNOWLEDGE GRAPH', s: 'retrieval + relations', r: 'grounding with citations', cls: 'ok' },
        { t: 'FOUNDATION MODELS', s: 'pretrained backbones', r: 'transfer across tasks', cls: 'ai' },
        { t: 'SPECIALISED MODELS', s: 'perception · prediction · channel', r: 'calibrated predictions', cls: 'ai' },
        { t: 'AGENTS', s: 'objective · memory · tools · reasoning', r: 'auditable decisions', cls: 'ai' },
        { t: 'MULTI-AGENT ORCHESTRATION', s: 'negotiate · allocate · resolve', r: 'consistent joint plan', cls: 'ai' },
        { t: 'PHYSICAL AI', s: 'plan → control → actuate', r: 'bounded, safe motion', cls: 'warn' },
        { t: 'ROBOT / UAV / SATELLITE ACTION', s: 'effect in the physical world', r: 'measured outcome', cls: 'ok' },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'ONE DIRECTION, TWO RETURNS', items: ['Upward: data becomes capability', 'Return 1 (fast): outcome → state → next decision', 'Return 2 (slow): outcome → dataset → next model'] },
    ],
    right: [
      { h: 'WHERE EACH BUZZWORD LIVES', tone: 'ai', kv: [['Generative AI', 'tiers 4–6: grounding, explanation, synthetic data'], ['Agentic AI', 'tiers 7–8: goals, tools, negotiation'], ['Physical AI', 'tiers 9–10: motion with consequences']] },
    ],
    tech: ['PyTorch', 'CUDA', 'vector DB', 'knowledge graph', 'VLM/LLM', 'RL/MARL', 'TensorRT', 'ROS 2'],
    metrics: [['10', 'tiers'], ['2', 'feedback paths'], ['&lt;300 ms', 'retrieval at the edge'], ['&lt;10 ms', 'actuation loop']],
    note: 'If a tier cannot state what it guarantees to the tier above, it is not an architecture — it is a diagram.',
    spec: {
      visual: 'Ten stacked slabs, each with a large title and a small subtitle, connected by explicit upward arrows on the right side and a bidirectional spine on the left.',
      scene3d: 'Slabs 30 → 24 m wide spaced 2.9 m; violet spine (up) with cyan return packets; a UAV above the top tier representing action.',
      components: ['10 tiers', 'Upward arrows per tier', 'Feedback spine', 'Action asset'],
      dataflow: 'Raw data climbs to action; outcomes return as state (fast) and as data (slow).',
      animation: ['Arrow pulses walk upward tier by tier', 'Spine packets travel both ways', 'Slow orbit'],
      text: 'The two return paths, and where generative / agentic / physical AI actually sit.',
      message: 'The stack is one pipeline: language and generative models are components inside a control system, not the product.',
    },
  },

  {
    kicker: 'ACT V · AGENTIC AI',
    title: 'Agent topology: intent in, coordinated action out',
    sub: 'A hierarchy with explicit authority: the mission agent owns intent, the planner decomposes it, specialist agents bid and negotiate, the safety agent can veto, and only the fleet manager talks to hardware.',
    scene: 'agentGraph3D',
    stageTag: 'AGENT GRAPH · 3D',
    caption: 'MISSION → PLANNER → {NAV, COMMS, ENERGY, RESOURCE, KNOWLEDGE} → {PERCEPTION, TWIN, SAFETY} → FLEET MANAGER → assets.',
    left: [
      { h: 'AUTHORITY MODEL', tone: 'ai', items: ['Intent flows down, never sideways', 'Specialists <b>bid</b>, the planner <b>decides</b>', 'Safety agent has an absolute veto', 'Only the fleet manager issues hardware commands'] },
      { h: 'CONFLICT RESOLUTION', items: ['Priority order fixed at design time', 'Ties broken by predicted mission risk', 'Unresolvable conflicts escalate to a human'] },
    ],
    right: [
      { h: 'MESSAGE TYPES', kv: [['INTENT', 'goal + constraints + deadline'], ['BID', 'cost, feasibility, confidence'], ['GRANT', 'assignment + resource budget'], ['ALERT', 'anomaly, risk, deviation'], ['VETO', 'blocking safety decision'], ['TRACE', 'rationale for the audit log']] },
      { h: 'FAILURE HANDLING', tone: 'warn', text: 'Any agent may crash. Its last granted assignments remain valid for a bounded time, then the fleet manager conservatively degrades.' },
    ],
    tech: ['LLM tool-use planners', 'contract-net protocol', 'behaviour trees', 'blackboard architecture', 'ROS 2 actions', 'OpenTelemetry traces'],
    metrics: [['&lt;2 s', 'intent → assignment'], ['6', 'message types'], ['1', 'veto authority'], ['100%', 'decisions traced']],
    note: 'Multi-agent systems fail through ambiguous authority, not weak models. The authority graph is therefore part of the architecture.',
    spec: {
      visual: 'Five-level agent hierarchy of glowing orbs in 3D, dashed message links between levels, converging on a fleet manager that drives three real assets below.',
      scene3d: 'Levels at y = 26, 21.4, 16.8, 12.2, 7.6; orbs r=0.8 (1.2 for mission agent); message bus bar behind the top level; UAV, UGV and satellite at the bottom.',
      components: ['11 agents on 5 levels', 'Message bus', 'Three actuated assets'],
      dataflow: 'Intent → decomposition → specialist bids → converged plan → hardware, with a red veto edge from safety.',
      animation: ['Messages march between levels at 2.2 units/s', 'Orb rings counter-rotate', 'Assets operate continuously'],
      text: 'Authority model, conflict resolution, message types, failure handling.',
      message: 'Clear authority and typed messages are what make multi-agent autonomy debuggable and certifiable.',
    },
  },

  {
    kicker: 'ACT V · AGENT ANATOMY',
    title: 'Every agent is the same seven things',
    sub: 'One template, applied ten times. That is what makes the fleet of agents reviewable: the same seven properties are specified, tested, logged and revoked for each one.',
    scene: 'agentAnatomy',
    stageTag: 'AGENT ANATOMY',
    caption: 'Objective · state · memory · tools · reasoning · communication · action.',
    left: [
      { h: 'SPECIFICATION PER AGENT', tone: 'ai', kv: [['OBJECTIVE', 'measurable goal + success test'], ['STATE', 'belief, with freshness bounds'], ['MEMORY', 'episodic + RAG, scoped + retained'], ['TOOLS', 'typed schemas, rate limits'], ['REASONING', 'plan → critique → replan'], ['COMMS', 'message types it may emit'], ['ACTION', 'bounded, logged, revocable']] },
    ],
    right: [
      { h: 'WHY THIS MATTERS', items: ['An agent without a success test cannot be evaluated', 'An agent without scoped memory becomes a privacy problem', 'An agent with unlimited tools becomes an unbounded risk', 'An agent without traces cannot be certified'] },
      { h: 'REVIEW GATE', tone: 'warn', text: 'No agent enters the fleet without all seven fields filled, a red-team review, and a revocation path.' },
    ],
    tech: ['tool schemas (JSON)', 'scoped memory stores', 'policy guardrails', 'rate limiting', 'trace logging', 'red-team scenarios'],
    metrics: [['7', 'mandatory fields'], ['100%', 'tool calls schema-validated'], ['&lt;1 s', 'revocation propagation']],
    note: 'This template is the difference between “we use agents” and “we operate agents”.',
    spec: {
      visual: 'A single large agent orb at the centre with seven labelled component blocks orbiting it, each connected by a bidirectional beam.',
      scene3d: 'Central orb r=2.2; seven 3.4 × 1.5 × 1.4 m blocks on an ellipse of radius 9.4 (Z compressed 0.55) bobbing individually.',
      components: ['Agent core', '7 property blocks with one-line definitions'],
      dataflow: 'Bidirectional beams: the core reads state/memory/tools and writes actions/messages.',
      animation: ['Blocks bob out of phase', 'Beams carry packets both ways', 'Core cage rotates'],
      text: 'The seven-field specification and the review gate.',
      message: 'Uniform agent anatomy makes a multi-agent system auditable rather than emergent.',
    },
  },

  {
    kicker: 'ACT V · RAG ARCHITECTURE',
    title: 'Retrieval-augmented decisions, with citations',
    sub: 'The platform does not rely on what a model happened to memorise during pretraining. Mission-critical facts — airspace rules, building layouts, past incidents, live sensor summaries — are retrieved, ranked and cited.',
    scene: 'ragPipeline',
    stageTag: 'RAG PIPELINE',
    caption: 'CORPUS → EMBED → VECTOR DB (+ KNOWLEDGE GRAPH) → RETRIEVE → RERANK → LLM/VLM → AGENT → MISSION DECISION.',
    diagram: {
      type: 'graph',
      title: 'RAG DATA PATH WITH GOVERNANCE',
      h: 290,
      groups: [
        { t: 'INDEXING (offline + streaming)', x: 14, y: 30, w: 470, h: 240 },
        { t: 'QUERY TIME (online)', x: 500, y: 30, w: 486, h: 240 },
      ],
      nodes: [
        { id: 'doc', x: 30, y: 60, w: 130, h: 46, t: 'Documents', s: 'regs · manuals' },
        { id: 'map', x: 30, y: 118, w: 130, h: 46, t: 'Maps / GIS', s: 'geometry' },
        { id: 'sat', x: 30, y: 176, w: 130, h: 46, t: 'Satellite + history', s: 'products, missions' },
        { id: 'chunk', x: 186, y: 100, w: 130, h: 46, t: 'Chunk + tag', s: 'spatial + temporal', cls: 'accent' },
        { id: 'emb', x: 186, y: 168, w: 130, h: 46, t: 'Embed', s: 'multimodal encoder', cls: 'accent' },
        { id: 'vdb', x: 340, y: 100, w: 130, h: 46, t: 'Vector DB', s: 'ANN index', cls: 'ok' },
        { id: 'kg', x: 340, y: 168, w: 130, h: 46, t: 'Knowledge graph', s: 'entities + relations', cls: 'ok' },
        { id: 'q', x: 516, y: 60, w: 140, h: 46, t: 'Agent query', s: 'task + context', cls: 'ai' },
        { id: 'ret', x: 676, y: 60, w: 140, h: 46, t: 'Retriever', s: 'dense + sparse + geo', cls: 'ok' },
        { id: 'rr', x: 836, y: 60, w: 136, h: 46, t: 'Reranker', s: 'cross-encoder', cls: 'ok' },
        { id: 'llm', x: 676, y: 140, w: 140, h: 46, t: 'LLM / VLM', s: 'grounded generation', cls: 'ai' },
        { id: 'ag', x: 836, y: 140, w: 136, h: 46, t: 'Agent decision', s: 'action + citations', cls: 'ai' },
        { id: 'gov', x: 516, y: 210, w: 456, h: 40, t: 'Governance: access control · citation required · confidence threshold · human escalation', cls: 'ghost' },
      ],
      edges: [
        { a: 'doc', b: 'chunk' }, { a: 'map', b: 'chunk' }, { a: 'sat', b: 'emb' }, { a: 'chunk', b: 'emb' },
        { a: 'emb', b: 'vdb', cls: 'ok' }, { a: 'emb', b: 'kg', cls: 'ok' },
        { a: 'q', b: 'ret', cls: 'ai' }, { a: 'ret', b: 'rr', cls: 'ok' }, { a: 'rr', b: 'llm', cls: 'ok' },
        { a: 'llm', b: 'ag', cls: 'ai' }, { a: 'vdb', b: 'ret', cls: 'ok' }, { a: 'kg', b: 'llm', cls: 'ok' },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'WHY NOT JUST A BIGGER MODEL', items: ['Regulations change weekly; weights do not', 'Local knowledge is not on the public internet', 'A decision must be explainable to a regulator', 'Retrieval is cheaper than retraining'] },
    ],
    right: [
      { h: 'GOVERNANCE', tone: 'warn', items: ['Access control per corpus and per agent', 'Citation required for safety-relevant claims', 'Confidence threshold → human escalation', 'Retrieval logs kept with the mission record'] },
    ],
    tech: ['FAISS / Milvus / pgvector', 'Neo4j / RDF', 'CLIP-style encoders', 'BM25 hybrid', 'cross-encoder rerankers', 'LLM/VLM tool calls'],
    metrics: [['&gt;0.9', 'recall@10'], ['&lt;300 ms', 'edge retrieval'], ['100%', 'cited safety claims'], ['0', 'ungrounded critical decisions']],
    note: 'RAG is presented here as an accountability mechanism first and a capability second.',
    spec: {
      visual: 'A seven-station 3D pipeline with a knowledge graph above the mid-point and a vector cloud beside it, ending in a “mission decision” panel with real citations.',
      scene3d: 'Seven 4.8 × 2.8 × 2.4 m station boxes spaced 6.6 m at y=8, linked by tubes with arrowheads and travelling packets; graph and cloud float above; decision panel to the right.',
      components: ['7 pipeline stations', 'Knowledge graph', 'Vector cloud', 'Decision panel with sources'],
      dataflow: 'Corpus → embed → index; query → retrieve → rerank → generate → decide, with the graph feeding constraints into generation.',
      animation: ['Packets step along the pipeline', 'Graph and cloud rotate', 'Decision panel remains legible as the camera drifts'],
      text: 'Why not a bigger model, plus the governance rules.',
      message: 'Grounded, cited retrieval is what lets an autonomous decision be reviewed after the fact.',
    },
  },

  {
    layout: 'full',
    kicker: 'ACT V · PHYSICAL AI',
    title: 'The loop that makes it physical',
    sub: 'PHYSICAL WORLD → SENSORS → PERCEPTION MODEL → WORLD MODEL → REASONING → PLANNING → CONTROL POLICY → ACTUATOR → PHYSICAL WORLD. Eight stations, one closed loop, running at 10–100 Hz on the vehicle.',
    scene: 'physicalAILoop',
    stageTag: 'PHYSICAL AI LOOP · HERO',
    caption: 'Each station is a real subsystem with its own latency budget; the ring is the actual data path, not a metaphor.',
    tech: ['visual-inertial odometry', 'occupancy + ESDF', 'learned world models', 'MPC / RL policies', 'ros2_control', 'TensorRT'],
    metrics: [['10–100 Hz', 'loop rate'], ['&lt;10 ms', 'control latency'], ['8', 'stations'], ['0', 'unbounded outputs']],
    note: 'This is the slide to remember: intelligence that does not close this loop on hardware is analytics, not autonomy.',
    spec: {
      visual: 'Full-bleed hero: a luminous eight-station ring hovering above a working city, with a UAV and a robot operating inside the ring’s footprint.',
      scene3d: 'Eight 2.4 m pillars with halos and light columns on an ellipse of radius 19 (Z 0.62) at y≈9; curved beams between stations; city, UAV and UGV below; observe/act links tie the ring to the assets.',
      components: ['8 loop stations', 'Curved inter-station beams', 'City + UAV + UGV', 'observe / act links'],
      dataflow: 'Clockwise: world → sensors → perception → world model → reasoning → planning → control → actuator → world.',
      animation: ['Packets circulate continuously', 'Halos pulse at 2 Hz out of phase', 'UAV and robot move inside the loop footprint', 'Slow 50 m camera orbit'],
      text: 'Title and subtitle only — the ring is the content.',
      message: 'Autonomy is a closed physical loop with a guaranteed rate; every station has an owner and a latency budget.',
      production: 'Camera (0,20,46) → (0,9,0), 48° FOV. Station colours follow the deck grammar: cyan sensing, mint world model, violet reasoning, amber control.',
    },
  },

  {
    kicker: 'ACT V · DIGITAL TWIN ARCHITECTURE',
    title: 'Real world and twin, and the three flows between them',
    sub: 'A twin is only useful if the flows are specified: what goes up, what comes back, and how stale either is allowed to be.',
    scene: 'dtArchitecture',
    stageTag: 'DIGITAL TWIN · SPLIT SCREEN',
    caption: '1 · telemetry → twin. 2 · twin → optimised policy. 3 · policy → real UAV. Sync channels and rates listed in-scene.',
    diagram: {
      type: 'chain',
      title: 'SYNCHRONISATION CHANNELS AND RATES',
      items: [
        { t: 'Pose + IMU', s: '50 Hz · control-relevant', cls: 'accent' },
        { t: 'Perception summary', s: '5 Hz · objects, occupancy', cls: 'accent' },
        { t: 'Network KPI', s: '1 Hz · rate, RSRP, outage', cls: 'ok' },
        { t: 'Geometry delta', s: 'on change · collapse, blockage', cls: 'ok' },
        { t: 'Twin age budget', s: '&lt; 200 ms for control use', cls: 'bad' },
      ],
    },
    left: [
      { h: 'WHAT THE TWIN IS FOR', items: ['Predicting risk before acting', 'Rehearsing plans in parallel', 'Training policies at scale', 'Explaining decisions to humans', 'Regression-testing every model release'] },
    ],
    right: [
      { h: 'FIDELITY CONTRACT', tone: 'ok', kv: [['Geometry', '&lt; 1 m error'], ['Radio', '&lt; 3 dB vs measurement'], ['Dynamics', '&lt; 10% on step response'], ['Sync age', '&lt; 200 ms'], ['Coverage', '100% of mission volume']] },
      { h: 'FAILURE MODE', tone: 'warn', text: 'A twin that silently drifts is more dangerous than no twin. Age and error are published as first-class telemetry.' },
    ],
    tech: ['Omniverse / OpenUSD', 'Isaac Sim', 'Sionna RT', 'SUMO', 'weather feeds', 'state estimation'],
    metrics: [['&lt;200 ms', 'sync age'], ['&lt;1 m', 'geometry error'], ['&lt;3 dB', 'radio error'], ['3', 'specified flows']],
    note: 'The twin is the platform’s prediction engine, and it is held to published accuracy numbers like any other sensor.',
    spec: {
      visual: 'Symmetric split screen: warm real city (left) and mint twin (right) with identical geometry and a mirrored UAV, plus three numbered arrows.',
      scene3d: 'Two 38 m city instances with seed 71 rendered in different palettes; twin bounded by a mint wireframe box; three arrows: telemetry (cyan, →), policy (violet, ←), actuation (mint, ↑ on the real side).',
      components: ['Real city + tower + UAV', 'Twin city + tower + UAV', 'Three numbered flows', 'Sync-channel panel'],
      dataflow: 'Explicitly numbered 1-2-3 so the viewer reads the causal order.',
      animation: ['Real UAV flies; twin UAV mirrors exactly', 'Arrows pulse in sequence 1 → 2 → 3', 'Slow orbit keeping both halves in frame'],
      text: 'What the twin is for, the fidelity contract, and the silent-drift failure mode.',
      message: 'A twin is a measured instrument with a published error budget, not a visualisation.',
    },
  },

  {
    layout: 'full',
    kicker: 'ACT V · COMMUNICATION ARCHITECTURE',
    title: 'One network from orbit to the user',
    sub: 'LEO constellation → UAV swarm → 5G/6G towers → ground users and edge servers, with satellite-to-satellite optical links overhead. Each link type has its own visual signature.',
    scene: 'commGlobal',
    stageTag: 'GLOBAL COMMS · LIVE 3D',
    caption: 'SAT→GROUND (Ka) · SAT→UAV (Ku NTN) · UAV↔UAV mesh · UAV→TOWER fronthaul · 5G/6G ACCESS · OPTICAL ISL.',
    tech: ['3GPP NTN Rel-17/18', '5G NR', '6G candidates', 'mmWave', 'FSO', 'O-RAN', 'Sionna', 'TR 38.901'],
    metrics: [['5', 'distinct link types'], ['&gt;100 Mb/s', 'aggregate user rate'], ['&lt;50 ms', 'edge RTT'], ['n+1', 'paths per critical flow']],
    note: 'Every node in this picture is a routing decision the communication agent makes and re-makes continuously.',
    spec: {
      visual: 'Full-bleed: Earth limb and LEO shell at the top, a UAV mesh in the middle, and a city with towers, gateway, edge racks and users at the bottom — all links labelled in 3D.',
      scene3d: 'Earth r=38 centred at (0,−42,−10); 2 × 6 ambient satellite shell at r=48 plus two detailed satellites at 29–32 m that carry the labelled links; 8-UAV mesh at 15 m; city, gateway, edge rack, 8 users.',
      components: ['LEO constellation', 'UAV mesh', 'Towers with coverage cones', 'Gateway', 'Edge racks', 'Users'],
      dataflow: 'Five labelled flows spanning space, air and ground, including an inter-satellite optical link.',
      animation: ['Satellites orbit', 'Packets march at per-link rates', 'Mesh re-forms as UAVs move'],
      text: 'Title and link legend only; the labels live in the 3D scene.',
      message: 'Space, air and ground are one routable network, continuously optimised rather than statically planned.',
      production: 'Camera 46° FOV authored at (0,18,58) → (0,14,0), then auto-framed. White for the optical ISL, mint for fronthaul, ice for space links.',
    },
  },

  {
    kicker: 'ACT V · FEDERATED LEARNING',
    title: 'Learning from the fleet without collecting the fleet’s data',
    sub: 'Each UAV, robot and edge server trains on what it sees. Only model updates leave the device, encrypted and aggregated. Raw imagery, locations and personal data stay where they were captured.',
    scene: 'federated',
    stageTag: 'FEDERATED LEARNING',
    caption: 'Red cubes: raw data that never leaves. Mint octahedra: model updates that do.',
    diagram: {
      type: 'chain',
      title: 'FEDERATED ROUND',
      items: [
        { t: 'Local training', s: 'on-device, own data', cls: 'ok' },
        { t: 'Δθ only', s: 'encrypted, clipped, noised', cls: 'ok' },
        { t: 'Secure aggregation', s: 'server sees no individual update', cls: 'accent' },
        { t: 'Global model θ', s: 'validated before release', cls: 'ai' },
        { t: 'Broadcast', s: 'back to every device', cls: 'ai' },
      ],
      note: 'Non-IID by construction: each device sees a different city, channel and mission profile — the aggregation must expect it.',
    },
    left: [
      { h: 'WHY IT IS REQUIRED HERE', items: ['Imagery of people and property is sensitive', 'Bandwidth from a UAV is scarce and precious', 'Some data cannot legally cross a border', 'Customers will not hand over raw operational data'] },
      { h: 'INPUTS', tone: 'ok', items: ['Local datasets per device', 'Current global model', 'Privacy budget and clipping bounds'] },
    ],
    right: [
      { h: 'PROCESSING', items: ['Local epochs with FedAvg / FedProx', 'Update clipping + optional differential privacy', 'Secure aggregation (server cannot inspect individuals)', 'Client selection weighted by data quality'] },
      { h: 'OUTPUTS / RISKS', tone: 'warn', items: ['Global model + per-round quality report', 'Risk: non-IID divergence → use proximal terms', 'Risk: stragglers → asynchronous aggregation', 'Risk: poisoning → robust aggregation + attestation'] },
    ],
    tech: ['FedAvg / FedProx', 'secure aggregation', 'differential privacy', 'CSI-feedback style compression', 'device attestation', '3GPP Rel-18 AI/ML framework'],
    metrics: [['0 bytes', 'raw sensitive data transmitted'], ['&gt;10×', 'bandwidth saving vs raw upload'], ['≈ central', 'accuracy on non-IID splits'], ['&lt;1%', 'accuracy loss from privacy noise']],
    note: 'Federated learning here is not a research flourish: it is the only way the fleet can learn from customer environments at all.',
    spec: {
      visual: 'Six devices in a ring, each holding a red “raw data stays” cube and a mint “Δθ leaves” octahedron, all linked to an aggregation orb that feeds a rotating global model above.',
      scene3d: 'Four UAVs, two ground assets and an edge rack on a ring of radius ~22; aggregation orb at (0,20,0); global model icosahedron at (0,27,0); dashed updates up, beam broadcasts down.',
      components: ['6 devices', 'Local data (red) vs update (mint) per device', 'Secure aggregation orb', 'Global model', 'Protocol panel'],
      dataflow: 'Device → Δθ → aggregation → global θ → broadcast → device. Raw data has no outbound path at all.',
      animation: ['Update octahedra pulse while “training”', 'Dashed packets rise, beam packets descend', 'Global model rotates'],
      text: 'Why it is required, processing steps, and the three real risks with mitigations.',
      message: 'Privacy-preserving learning is an enabling constraint: it is what makes fleet-scale learning legally and commercially possible.',
    },
  },

  {
    kicker: 'ACT V · MULTI-AGENT RL',
    title: 'A swarm that learns to cooperate',
    sub: 'Each UAV is an agent with its own observation and action space; the reward couples them. Centralised training with decentralised execution means they learn together but fly independently.',
    scene: 'marlSwarm',
    stageTag: 'MARL · CTDE',
    caption: 'City + obstacles + users + channels as the environment; six agents; state, action and reward panels above.',
    diagram: {
      type: 'graph',
      title: 'MARL FORMULATION (Dec-POMDP)',
      h: 260,
      nodes: [
        { id: 'env', x: 330, y: 40, w: 340, h: 56, t: 'ENVIRONMENT', s: 'city geometry · users · channel · wind · energy', cls: 'accent' },
        { id: 'o1', x: 40, y: 130, w: 150, h: 46, t: 'Agent 1 obs', s: 'local + neighbours', cls: 'ok' },
        { id: 'o2', x: 210, y: 130, w: 150, h: 46, t: 'Agent 2 obs', s: 'local + neighbours', cls: 'ok' },
        { id: 'o3', x: 380, y: 130, w: 150, h: 46, t: 'Agent i obs', s: 'local + neighbours', cls: 'ok' },
        { id: 'critic', x: 590, y: 130, w: 190, h: 46, t: 'Centralised critic', s: 'sees joint state (training only)', cls: 'ai' },
        { id: 'act', x: 800, y: 130, w: 172, h: 46, t: 'Decentralised actors', s: 'run on each UAV', cls: 'ai' },
        { id: 'r', x: 330, y: 200, w: 340, h: 48, t: 'REWARD  +throughput +coverage −energy −latency −collision', s: 'shared + individual shaping terms', cls: 'warn' },
      ],
      edges: [
        { a: 'env', b: 'o1' }, { a: 'env', b: 'o2' }, { a: 'env', b: 'o3' }, { a: 'env', b: 'critic', cls: 'ai' },
        { a: 'critic', b: 'act', cls: 'ai' }, { a: 'o3', b: 'r', cls: 'warn' }, { a: 'act', b: 'env', cls: 'ai', bend: 90 },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'STATE (per agent)', kv: [['kinematics', 'position, velocity, altitude'], ['energy', 'battery, power draw'], ['channel', 'CSI, interference, blockage'], ['demand', 'users served, queue'], ['neighbours', 'relative state of nearby agents']] },
      { h: 'ACTION', tone: 'ok', kv: [['trajectory', 'waypoint / velocity command'], ['power', 'transmit power'], ['channel', 'resource block selection'], ['altitude', 'coverage vs path loss'], ['association', 'which users to serve']] },
    ],
    right: [
      { h: 'REWARD', tone: 'warn', items: ['+ aggregate throughput and fairness', '+ priority-area coverage', '− energy consumed per bit', '− end-to-end latency', '− collision and geofence violation (hard penalty)'] },
      { h: 'TRAINING SETUP', tone: 'ai', items: ['CTDE: centralised critic, decentralised actors', 'Domain randomisation over city, wind, demand', 'Curriculum: 2 agents → 6 → 20', 'Evaluated against a tuned classical baseline'] },
    ],
    tech: ['MADDPG / QMIX / MAPPO', 'Isaac Lab', 'Sionna channel models', 'PyTorch', 'Ray', 'domain randomisation'],
    metrics: [['6 → 20', 'agents in curriculum'], ['&gt;baseline', 'throughput vs tuned heuristic'], ['0', 'collisions in evaluation'], ['&lt;15%', 'sim-to-real gap']],
    note: 'MARL is used where the coupling is real — spectrum, coverage and airspace are shared resources, so the policies must be learned jointly.',
    spec: {
      visual: 'Six labelled agents flying over a city of users with demand bars, each projecting a coverage cone, over a violet wireframe reward field, with state/action/reward panels floating above.',
      scene3d: 'City spread 52 m; 22 users with height-coded demand bars; 6-UAV mesh at 16 m with 26 m range; 26 × 26 wireframe reward field at y=0.4; three panels at y=27.',
      components: ['6 agents with labels', 'Users + demand bars', 'Coverage cones', 'Reward field', 'State/action/reward panels'],
      dataflow: 'Environment → observations → policies → actions → environment, with the reward field visualising the shared objective.',
      animation: ['Agents re-form the mesh and shift coverage', 'Cones breathe', 'Reward field shimmers where coverage is good'],
      text: 'Full Dec-POMDP formulation with state, action, reward and training setup.',
      message: 'Where resources are shared, coordination must be learned jointly — with hard penalties for safety violations, not soft ones.',
    },
  },
];
