export const CLOSING = [
  {
    kicker: 'ACT XI · TECHNOLOGY MAP',
    title: 'The complete technology ecosystem',
    sub: 'Six families, explicit primary choices, and no magic. Everything here either exists today or is an active standards track.',
    scene: 'toolConstellation',
    stageTag: 'TECHNOLOGY ECOSYSTEM',
    diagram: {
      type: 'matrix',
      title: 'TECHNOLOGY MAP BY FAMILY',
      ih: 25,
      cols: [
        { t: 'SIMULATION', cls: 'ok', items: [{ t: 'Omniverse / OpenUSD' }, { t: 'Isaac Sim' }, { t: 'Isaac Lab' }, { t: 'SUMO (traffic)' }, { t: 'STK (orbits)' }, { t: 'QGIS (geospatial)' }] },
        { t: 'ROBOTICS', cls: 'accent', items: [{ t: 'ROS 2 (middleware)' }, { t: 'PX4 (flight control)' }, { t: 'MAVLink' }, { t: 'ros2_control' }, { t: 'Nav2 / MoveIt' }] },
        { t: 'AI', cls: 'ai', items: [{ t: 'PyTorch' }, { t: 'CUDA / TensorRT' }, { t: 'LLMs · VLMs' }, { t: 'RL · MARL' }, { t: 'Federated learning' }, { t: 'RAG · vector DB · KG' }] },
        { t: 'COMMUNICATION', cls: 'accent', items: [{ t: '5G NR · 6G candidates' }, { t: '3GPP NTN Rel-17/18' }, { t: 'mmWave' }, { t: 'FSO / optical ISL' }, { t: 'O-RAN' }, { t: 'NVIDIA Sionna' }] },
        { t: 'INFRASTRUCTURE', cls: 'warn', items: [{ t: 'Kubernetes / K3s' }, { t: 'GPU clusters' }, { t: 'Edge servers' }, { t: 'Object storage' }, { t: 'Model registry' }, { t: 'GitOps' }] },
        { t: 'DATA', cls: 'ok', items: [{ t: 'GIS / OSM / GeoJSON' }, { t: 'Telemetry (MCAP)' }, { t: 'Sensor data (LiDAR, RGB, RF)' }, { t: 'Satellite products' }, { t: 'Parquet / Delta' }] },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'PRIMARY CHOICES', items: ['<b>Simulation</b> Isaac Sim + Isaac Lab on OpenUSD', '<b>Robotics</b> ROS 2 + PX4', '<b>AI</b> PyTorch + CUDA + TensorRT', '<b>Comms</b> 3GPP NTN + Sionna for modelling', '<b>Infra</b> Kubernetes everywhere, GPU-first'] },
    ],
    right: [
      { h: 'DELIBERATELY NOT IN SCOPE', tone: 'warn', items: ['Custom silicon', 'Proprietary middleware replacing ROS 2', 'A single monolithic “do everything” model', 'Any autonomous use of force'] },
      { h: 'EXIT PATHS', tone: 'ok', text: 'Each primary choice has a documented replacement path — the interfaces from Phase 1 are what make that possible.' },
    ],
    tech: ['Omniverse', 'Isaac Sim/Lab', 'ROS 2', 'PX4', 'PyTorch', 'CUDA', 'Sionna', 'NTN', 'Kubernetes', 'GIS'],
    metrics: [['6', 'technology families'], ['~35', 'named components'], ['0', 'unproven dependencies']],
    note: 'The differentiator is not the tool list — it is that these tools share one world model, one data platform and one deployment path.',
    spec: {
      visual: 'Technology constellation in 3D above a six-column technology matrix.',
      scene3d: 'Six hubs on a ring of radius 13 with ~30 tool nodes at radius 19–22, all beamed to a central platform orb.',
      components: ['6 family hubs', '30+ tool nodes', 'Platform core'],
      dataflow: 'Core → families: the shared contracts. Families → core: capabilities.',
      animation: ['Core rings rotate, beams carry packets outward'],
      text: 'Primary choices, explicit non-scope, and exit paths.',
      message: 'Standard, provable components — integrated by architecture rather than by adapters.',
    },
  },

  {
    kicker: 'ACT XI · GOVERNANCE',
    title: 'Regulation, ethics and assurance are part of the architecture',
    sub: 'An autonomy platform that cannot produce evidence cannot be authorised. Compliance is therefore designed into the data platform, the safety plane and the agent layer — not added afterwards.',
    scene: 'backdrop',
    sceneOpts: { variant: 'orbit', cam: [0, 10, 34] },
    stageTag: 'ASSURANCE',
    diagram: {
      type: 'graph',
      title: 'EVIDENCE CHAIN FROM DESIGN TO AUTHORISATION',
      h: 260,
      nodes: [
        { id: 'r', x: 20, y: 46, w: 170, h: 48, t: 'Requirements + hazards', s: 'P0 / P1 artefacts', cls: 'accent' },
        { id: 's', x: 220, y: 46, w: 170, h: 48, t: 'Safety concept', s: 'planes, modes, monitors', cls: 'bad' },
        { id: 'v', x: 420, y: 46, w: 170, h: 48, t: 'Verification evidence', s: 'L1–L9 test records', cls: 'ok' },
        { id: 'o', x: 620, y: 46, w: 170, h: 48, t: 'Operational record', s: 'replayable missions', cls: 'ok' },
        { id: 'a', x: 820, y: 46, w: 158, h: 48, t: 'Authorisation', s: 'regulator decision', cls: 'ai' },
        { id: 'p', x: 20, y: 150, w: 240, h: 48, t: 'Privacy & data protection', s: 'federated learning, minimisation, residency', cls: 'ghost' },
        { id: 'e', x: 290, y: 150, w: 240, h: 48, t: 'Ethical constraints', s: 'human authority, no autonomous force', cls: 'ghost' },
        { id: 'x', x: 560, y: 150, w: 240, h: 48, t: 'Explainability', s: 'cited decisions, traces, counterfactuals', cls: 'ghost' },
        { id: 'c', x: 830, y: 150, w: 148, h: 48, t: 'Continuous assurance', s: 'per release', cls: 'ghost' },
      ],
      edges: [
        { a: 'r', b: 's' }, { a: 's', b: 'v', cls: 'bad' }, { a: 'v', b: 'o', cls: 'ok' }, { a: 'o', b: 'a', cls: 'ai' },
        { a: 'p', b: 'v' }, { a: 'e', b: 'v' }, { a: 'x', b: 'o' }, { a: 'c', b: 'a' },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'WHAT REGULATORS ASK FOR', items: ['What can go wrong, and what stops it', 'How you know it works (evidence, not opinion)', 'What happens when the AI is wrong', 'Who is responsible for each decision', 'How you will notice degradation in service'] },
    ],
    right: [
      { h: 'HOW THE ARCHITECTURE ANSWERS', tone: 'ok', items: ['Safety plane independent of the learning plane', 'Nine-level validation with recorded evidence', 'Degradation ladder with classical fallbacks', 'Per-decision traces bound to model versions', 'Fleet monitoring with automatic rollback'] },
      { h: 'ETHICAL POSITION', tone: 'warn', text: 'Human authority over consequential action is architectural, not procedural: the fleet manager will not execute an unauthorised class of action even if an agent requests it.' },
    ],
    tech: ['ISO/IEC standards for AI management', 'aviation airworthiness processes', 'GDPR-style data minimisation', 'audit logging', 'model cards', 'incident reporting'],
    metrics: [['100%', 'decisions attributable'], ['per release', 'assurance evidence'], ['0', 'autonomous use-of-force'], ['&lt;60 s', 'rollback on regression']],
    note: 'Every claim in this deck is designed to be defensible in front of a regulator, an auditor or an inquiry.',
    spec: {
      visual: 'Quiet orbital backdrop (Earth and constellation) so the evidence-chain diagram is the focus.',
      components: ['Evidence chain: requirements → safety concept → verification → operations → authorisation', 'Four cross-cutting governance blocks'],
      animation: ['Backdrop only: Earth rotates, satellites orbit. No motion competing with the diagram.'],
      text: 'What regulators ask for, mapped one-to-one onto architectural answers.',
      message: 'Assurance is an architectural property, and it is what converts capability into permission to operate.',
    },
  },

  {
    kicker: 'ACT XI · SCALE-UP',
    title: 'Capability milestones, not calendar promises',
    sub: 'Each milestone is defined by demonstrated capability and evidence, with an explicit gate. Programmes fail when milestones are dates instead of proofs.',
    scene: 'backdrop',
    sceneOpts: { variant: 'swarm', cam: [0, 16, 44] },
    stageTag: 'MILESTONES',
    diagram: {
      type: 'stack',
      title: 'CAPABILITY LADDER · EACH RUNG IS A GATE',
      bh: 40,
      items: [
        { t: 'M1 · One asset, one twin, one mission in simulation', s: 'twin validated, single-agent policy beats baseline', l: 'M1', r: 'gate: P7 statistics', cls: 'accent' },
        { t: 'M2 · Hardware-in-the-loop parity', s: 'real firmware meets rate and jitter budgets', l: 'M2', r: 'gate: P9 timing report', cls: 'accent' },
        { t: 'M3 · Controlled flight, measured gap', s: 'sim-to-real gap < 15% on mission metrics', l: 'M3', r: 'gate: P10 flight report', cls: 'ok' },
        { t: 'M4 · Multi-agent swarm with learned coordination', s: 'MARL policy beats heuristic, survives agent loss', l: 'M4', r: 'gate: P6 + P8 evidence', cls: 'ok' },
        { t: 'M5 · Cross-domain mission (satellite + air + ground)', s: 'detection-to-tasking under 2 s across domains', l: 'M5', r: 'gate: end-to-end rehearsal', cls: 'ai' },
        { t: 'M6 · Pilot deployment with real users', s: 'KPIs met, interventions < 0.1 / UAV-hour', l: 'M6', r: 'gate: operator sign-off', cls: 'ai' },
        { t: 'M7 · Multi-region operation with continual learning', s: 'automated retrain → validate → canary loop', l: 'M7', r: 'gate: continuous assurance', cls: 'warn' },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'WHAT EACH GATE REQUIRES', items: ['A measurable claim', 'Recorded evidence, reproducible', 'An independent reviewer', 'A documented residual risk list'] },
      { h: 'PARALLELISABLE WORK', tone: 'ok', items: ['Twin construction and data collection', 'Agent development and safety-plane implementation', 'Regulatory engagement (starts at M1, not M6)'] },
    ],
    right: [
      { h: 'CRITICAL PATH', tone: 'warn', items: ['Twin fidelity → everything trained on it', 'Safety plane → everything allowed to fly', 'Interface contracts → everything that must integrate', 'Regulatory relationship → everything that must operate'] },
      { h: 'BIGGEST RISKS', tone: 'warn', items: ['Twin fidelity overestimated (mitigated by measured gap at M3)', 'Tool sprawl (mitigated by primary-choice discipline)', 'Safety plane treated as a feature (mitigated by plane separation)', 'Data without lineage (mitigated at P2 by design)'] },
    ],
    tech: ['capability-based gating', 'independent review', 'residual risk registers', 'regulatory pre-engagement'],
    metrics: [['7', 'capability milestones'], ['1', 'gate per milestone'], ['4', 'critical-path dependencies']],
    note: 'Sequencing is driven by evidence dependencies: nothing is scheduled that cannot be proven when it is claimed.',
    spec: {
      visual: 'A live swarm backdrop under a seven-rung capability ladder diagram.',
      components: ['7 milestone rungs with gates', 'Critical-path and risk lists'],
      animation: ['Backdrop swarm only — the diagram carries the content.'],
      text: 'Gate requirements, parallel work, critical path, and the four biggest risks with mitigations.',
      message: 'Milestones are proofs, and the critical path is a chain of evidence dependencies.',
    },
  },

  {
    layout: 'full',
    kicker: 'ACT XI · FINAL MASTER VISUAL',
    title: 'One system: space, air, ground, edge, cloud, twin, agents',
    sub: 'Earth and its constellation above, a living city below, a swarm and robots working, a digital twin on one side, the training cloud on the other, and the agent layer coordinating everything inside the SENSE → UNDERSTAND → REASON → LEARN → PLAN → ACT → ADAPT loop.',
    scene: 'finalMaster',
    fitMargin: 0.94,
    stageTag: 'MASTER VISUAL · LIVE 3D',
    caption: 'Everything in this deck, operating simultaneously, in one frame.',
    tech: ['LEO / NTN', '6G mesh', 'UAV swarm', 'ground robots', 'edge GPU', 'digital twin', 'RAG + knowledge', 'agentic AI', 'physical AI', 'federated MARL', 'MLOps'],
    metrics: [['15', 'layers'], ['14', 'phases'], ['9', 'validation levels'], ['7', 'loop stages'], ['1', 'platform']],
    note: 'This is not an AI model for drones. It is an autonomous physical AI infrastructure that senses, understands, reasons, learns, plans, acts and adapts — continuously.',
    spec: {
      visual: 'The maximal scene: Earth limb with a four-plane constellation, a full city with towers, gateway, edge racks, robots and people, a 14-UAV swarm, the digital twin to the left, the training cloud to the right, an agent ring in the middle and the seven-stage loop ring above everything.',
      scene3d: 'Earth r=52 at (0,−57,0); 3 × 6 ambient satellite shell at r=64 plus two detailed satellites at 31–34 m linked by an optical ISL; city (140 buildings) at y=−3.6 with towers, gateway, edge rack, 3 UGVs and pedestrians; 12-UAV mesh at 16 m; digital twin at (−46,2,18); GPU pod at (46,0,20); 7 agent orbs at y=28; SENSE→ADAPT ring of 7 nodes at y=44 on radius 26; bidirectional spine on the axis.',
      components: ['Earth + constellation', 'City + infrastructure + robots + humans', 'UAV swarm', 'Digital twin', 'Cloud cluster', 'Agent layer', 'SENSE→ADAPT loop ring', 'Central bidirectional spine'],
      dataflow: 'Vertical spine carries observations up and commands/models down; side beams connect the twin and the cloud; the loop ring above states the system’s cycle.',
      animation: ['Earth rotates, constellation orbits', 'Swarm re-forms its mesh, robots patrol, traffic moves', 'Loop-ring packets circulate', 'Agent orbs pulse', '110 m camera orbit with slow vertical bob'],
      text: 'Title, subtitle and the loop legend only. This slide must work with the sound off.',
      message: 'One continuously learning autonomous system spanning space, air, ground, edge and cloud.',
      production: 'Camera 48° FOV authored at (0,26,96) → (0,22,0), auto-framed with fitMargin 0.94 to fill the stage. Fog is derived from the content bounding sphere. Exposure 1.16. If rendered as video: 20 s orbit, no cuts, titles fading in over the first 3 s.',
    },
  },

  {
    layout: 'full',
    titleSlide: true,
    scene: 'closingRing',
    kicker: 'THE POINT OF ALL OF THIS',
    title: 'SENSE · UNDERSTAND · REASON · <em>LEARN</em> · PLAN · ACT · ADAPT',
    sub: 'An autonomous physical AI infrastructure connecting space, air, ground, edge, cloud, digital twins, generative AI, agentic AI, physical AI, multi-agent learning, communication networks and robotics into one continuously learning system.',
    strip: ['15 LAYERS', '14 PHASES', '9 VALIDATION LEVELS', '17-STEP MISSION', '10 USE CASES', '1 PLATFORM'],
    stageTag: 'CLOSING',
    caption: 'Deck built as a live WebGL presentation — every scene above is rendered in real time, not pre-recorded.',
    spec: {
      visual: 'A luminous seven-node loop ring in orbit above Earth with a single UAV rotating slowly at its centre.',
      scene3d: 'Earth r=30 at (0,−32,−16); seven ring nodes on radius 22 (Z 0.8) at y≈12 seen from a raised camera so the ring reads as a ring; UAV at the centre rotating at 0.3 rad/s.',
      components: ['Earth', '7-stage loop ring', 'Central UAV'],
      dataflow: 'The ring is the system’s cycle; the UAV at its centre is what the cycle acts through.',
      animation: ['Ring nodes pulse in sequence', 'Packets circulate the ring', 'UAV yaws slowly', 'Camera orbits at 0.03 rad/s'],
      text: 'One line: the loop. One paragraph: what the platform is.',
      message: 'The deck ends where the system does: a loop that never stops.',
    },
  },
];
