const L = (n, title, o) => ({
  kicker: `LAYER ${n} / 15`,
  title,
  badge: o.badge ?? `L${n}`,
  ...o,
});

export const LAYERS = [
  L(1, 'Physical world — the only ground truth', {
    sub: 'Purpose: define what the system is responsible for perceiving and changing. Everything above this layer is a model of it, and every model is wrong somewhere.',
    scene: 'l1PhysicalWorld',
    stageTag: 'L1 · PHYSICAL WORLD',
    caption: 'City · roads · vehicles · humans · farmland · industrial site · maritime · disaster zone, on real terrain.',
    diagram: {
      type: 'chain',
      title: 'L1 INPUT → PROCESSING → OUTPUT',
      items: [
        { t: 'Reality', s: 'terrain, structures, weather, people, machines' },
        { t: 'Physical events', s: 'earthquake, blockage, outage, growth', e: '→', cls: 'warn' },
        { t: 'Observable signals', s: 'photons, RF, sound, vibration, motion', cls: 'accent' },
        { t: 'To L2 sensing', s: 'what must be measured, at what rate', cls: 'accent' },
      ],
    },
    left: [
      { h: 'ENVIRONMENT CLASSES', items: ['Urban: buildings, streets, crowds, cellular grid', 'Rural / agricultural: fields, irrigation, machinery', 'Industrial: plants, tanks, pipelines, restricted zones', 'Maritime: vessels, ports, sea state', 'Disaster: collapse, fire, flooding, debris'] },
      { h: 'INPUTS', tone: 'ok', items: ['None — this layer <b>is</b> the input to the system'] },
    ],
    right: [
      { h: 'WHAT THE PLATFORM MUST HANDLE', items: ['Geometry that changes without warning', 'Actors that do not cooperate', 'Weather that invalidates plans and links', 'Regulatory boundaries that are invisible to sensors'] },
      { h: 'INTERFACE ▲ TO L2', tone: 'ai', text: 'Defines the <b>sensing requirement</b>: resolution, revisit rate, spectral bands, accuracy and coverage needed to act safely.' },
    ],
    tech: ['GIS / OpenStreetMap', 'GeoJSON', 'DTM / DSM', 'cadastral + airspace data', 'weather feeds', 'traffic feeds'],
    metrics: [['cm–m', 'geometric accuracy required'], ['s–min', 'change detection latency'], ['km²', 'area of responsibility'], ['24/7', 'operating window']],
    note: 'Design rule: never let a model’s assumption about the world become invisible. Everything above must be traceable to something measurable here.',
    spec: {
      visual: 'Wide aerial establishing shot: real terrain with a partially damaged city at centre, farmland west, industrial site east, sea to the north and a marked disaster zone.',
      scene3d: '190 × 190 m displaced terrain; 150-building instanced city (22% damaged); 24 moving vehicles; 6 pedestrians; 5 crop plots; 4 industrial tanks; animated sea plane with a moving vessel.',
      components: ['Terrain mesh + wireframe', 'City + roads + vehicles', 'Humans', 'Farmland plots', 'Industrial tanks', 'Sea + ship', 'Red disaster-zone disc'],
      dataflow: 'None yet — this is the source. Arrows begin at L2.',
      animation: ['Vehicles drive along the grid', 'Sea wireframe swells', 'Ship traverses the coastline', 'Slow high orbit camera'],
      text: 'Environment classes, what the platform must tolerate, and the sensing requirement passed to L2.',
      message: 'The physical world is the specification. Model quality is judged against it, never the reverse.',
      production: 'Camera (0,30,62) → (0,3,−2), 48° FOV, fog 70/240. Cool key 0xcfe4ff at 0.85 to keep it documentary rather than heroic.',
    },
  }),

  L(2, 'Sensing — turning the world into measurements', {
    sub: 'Purpose: acquire calibrated, time-stamped, geo-referenced observations from orbit, air, ground and fixed infrastructure, with known uncertainty.',
    scene: 'l2Sensing',
    stageTag: 'L2 · SENSING',
    caption: 'One UAV emitting LiDAR, camera, radar and RF sensing volumes over a city, with a satellite swath sweeping across it.',
    diagram: {
      type: 'chain',
      title: 'L2 SENSOR PIPELINE',
      items: [
        { t: 'Physical signal', s: 'photons · RF · inertia' },
        { t: 'Sensor + calibration', s: 'intrinsics, extrinsics, bias', cls: 'accent' },
        { t: 'Time & pose stamping', s: 'PTP / GNSS-PPS, IMU fusion', cls: 'accent' },
        { t: 'Compression / triage', s: 'onboard, bandwidth-aware', cls: 'ok' },
        { t: 'To L5 / L7', s: 'measurement + uncertainty', cls: 'ok' },
      ],
    },
    left: [
      { h: 'INPUTS', items: ['Photons (VIS/NIR/thermal)', 'RF energy (radar, spectrum, CSI)', 'Inertial + satellite navigation', 'Environmental scalars (wind, temp, gas)'] },
      { h: 'SENSOR SET', tone: 'ok', items: ['<b>Camera</b> RGB / IR, rolling-shutter aware', '<b>LiDAR</b> 32–128 ch, 10–20 Hz', '<b>Radar</b> mmWave, range-Doppler', '<b>RF</b> spectrum + CSI probes', '<b>IMU + GNSS-RTK</b> pose', '<b>Satellite</b> multispectral + SAR'] },
    ],
    right: [
      { h: 'PROCESSING', items: ['Calibration and de-warping', 'Time sync to a single mission clock', 'Pose stamping (every sample geo-referenced)', 'Onboard triage: what is worth transmitting'] },
      { h: 'OUTPUTS → INTERFACES', tone: 'ai', items: ['Point clouds, frames, spectra, tracks', 'Uncertainty per measurement', '▼ from L1: physical signal', '▲ to L5 edge inference and L7 data platform'] },
    ],
    tech: ['ROS 2 sensor_msgs', 'PTP / GNSS-PPS', 'RTK', 'GStreamer / NVENC', 'Velodyne/Ouster SDK', 'SAR / multispectral products'],
    metrics: [['&lt;1 ms', 'inter-sensor time sync'], ['&lt;5 cm', 'RTK pose accuracy'], ['10–20 Hz', 'LiDAR frame rate'], ['&gt;10:1', 'onboard data reduction']],
    note: 'A measurement without time, pose and uncertainty is not data — it is an anecdote. This layer exists to prevent anecdotes entering the platform.',
    spec: {
      visual: 'Hero UAV at 18 m over a city with four visibly different sensing volumes: mint LiDAR fan, amber camera frustum with a scanning line, pink radar cone, violet RF cone. A satellite sweeps a bright swath across the ground.',
      scene3d: 'LiDAR: 54 rotating rays with hit points; camera: line frustum + scan bar; radar/RF: additive cones with breathing scale; satellite swath: 10 × 2.4 m footprint translating on Z.',
      components: ['UAV + 4 sensing volumes', 'Satellite + swath + footprint', '14 pulsing IoT nodes', 'UGV with spinning LiDAR', 'Six sensor labels'],
      dataflow: 'World → sensor volumes → (implicit) onboard triage. Every volume is annotated with the data product it yields.',
      animation: ['LiDAR fan rotates at 1.6 rad/s', 'Camera scan bar sweeps', 'Cones breathe at 1.7 Hz', 'Satellite footprint sweeps ±18 m', 'IoT nodes pulse asynchronously'],
      text: 'Sensor set with real specs, processing steps, and the uncertainty-carrying output contract.',
      message: 'Sensing is a metrology problem before it is an AI problem.',
      production: 'Camera (26,18,40) → (0,8,0). Keep the four volumes visually distinct by colour AND geometry so the slide reads in five seconds.',
    },
  }),

  L(3, 'Physical agents — the bodies the AI operates', {
    sub: 'Purpose: provide the mobility, payload, endurance and compute envelopes that bound every plan the autonomy layer is allowed to make.',
    scene: 'l3Agents',
    stageTag: 'L3 · PHYSICAL AGENTS',
    caption: 'Satellite, UAV swarm, UGVs, autonomous vehicle and edge node, each with its capability envelope.',
    diagram: {
      type: 'matrix',
      title: 'AGENT CLASSES · CAPABILITY ENVELOPES',
      ih: 28,
      cols: [
        { t: 'SATELLITE', cls: 'accent', items: [{ t: 'LEO 500–600 km' }, { t: 'revisit: hours' }, { t: 'wide-area, low detail' }, { t: 'NTN backhaul' }] },
        { t: 'UAV', cls: 'ok', items: [{ t: '20–60 min endurance' }, { t: '0–500 m AGL' }, { t: '1–5 kg payload' }, { t: 'aerial base station' }] },
        { t: 'UAV SWARM', cls: 'ok', items: [{ t: '5–50 units' }, { t: 'area scaling' }, { t: 'mesh relay' }, { t: 'graceful degradation' }] },
        { t: 'UGV / ROBOT', cls: 'ai', items: [{ t: 'hours endurance' }, { t: 'contact-level work' }, { t: 'heavy sensors' }, { t: 'blocked by terrain' }] },
        { t: 'EDGE NODE', cls: 'warn', items: [{ t: 'static or vehicular' }, { t: 'GPU inference' }, { t: 'model cache' }, { t: 'local autonomy anchor' }] },
      ],
    },
    left: [
      { h: 'INPUTS', items: ['Task assignments from L13 orchestration', 'Control setpoints from L11 physical AI', 'Model updates from L12 learning'] },
      { h: 'PROCESSING', items: ['Flight / motion control (real-time, on-board)', 'Payload management and power budgeting', 'Health monitoring and self-reporting'] },
    ],
    right: [
      { h: 'OUTPUTS', tone: 'ok', items: ['Physical effect in the world', 'Sensor streams (to L2)', 'Health, energy and capability telemetry'] },
      { h: 'INTERFACES', tone: 'ai', items: ['▼ from L4/L5: commands, policies, inference', '▲ to L2/L7: observations and telemetry', 'Hard limits published to L13 as constraints'] },
    ],
    tech: ['PX4 / ArduPilot', 'MAVLink', 'ROS 2 control', 'Jetson Orin / AGX', 'CAN / UAVCAN', 'ISO 21384 (UAS)', 'ITU/3GPP NTN'],
    metrics: [['20–60 min', 'UAV endurance'], ['100–275 TOPS', 'onboard AI compute'], ['5–50', 'agents per mission'], ['&lt;10 ms', 'inner control loop']],
    note: 'The physical envelope is not a detail — it is the hard constraint set that makes an autonomy plan feasible or fiction.',
    spec: {
      visual: 'A lit hangar apron with each agent class present and a floating spec panel beside it.',
      scene3d: 'Satellite at (−26,22,−8); 8-UAV mesh swarm at 13 m; solo UAV low for detail; two UGVs; a moving autonomous vehicle; a GPU rack. Five canvas spec panels.',
      components: ['5 agent classes', 'Per-class spec panels', 'Dynamic mesh links between swarm members'],
      dataflow: 'Implicit: commands arrive from above, telemetry leaves from below. Explicit flows appear in L4.',
      animation: ['Vehicle drives across the apron and loops', 'Rotors + LiDAR spin', 'Satellite yaws slowly'],
      text: 'Capability-envelope matrix, inputs, processing, outputs and interfaces.',
      message: 'Autonomy is only as good as the bodies it commands; envelopes are published as constraints, not assumptions.',
    },
  }),

  L(4, 'Communication — the fabric that makes the fleet one system', {
    sub: 'Purpose: keep every agent reachable, every observation deliverable and every decision timely across space, air and ground, with graceful degradation instead of failure.',
    scene: 'l4Comms',
    stageTag: 'L4 · COMMUNICATION',
    caption: 'Ka feeder · NTN Ku sat↔UAV · UAV mesh · fronthaul · 5G/6G access · optical inter-satellite link.',
    diagram: {
      type: 'graph',
      title: 'LINK TOPOLOGY AND ROLES',
      h: 290,
      nodes: [
        { id: 'leo', x: 20, y: 40, w: 150, h: 48, t: 'LEO satellite', s: 'NTN + imaging', cls: 'accent' },
        { id: 'leo2', x: 20, y: 118, w: 150, h: 48, t: 'LEO satellite', s: 'optical ISL peer', cls: 'accent' },
        { id: 'uav', x: 250, y: 40, w: 160, h: 48, t: 'UAV relay / ABS', s: 'aerial base station', cls: 'ok' },
        { id: 'mesh', x: 250, y: 118, w: 160, h: 48, t: 'UAV↔UAV mesh', s: 'multi-hop, self-healing', cls: 'ok' },
        { id: 'gw', x: 480, y: 40, w: 160, h: 48, t: 'Gateway / ground station', s: 'feeder + core uplink' },
        { id: 'gnb', x: 480, y: 118, w: 160, h: 48, t: '5G/6G gNB', s: 'terrestrial access' },
        { id: 'ue', x: 480, y: 196, w: 160, h: 48, t: 'Users & robots', s: 'UE / device', cls: 'ok' },
        { id: 'core', x: 710, y: 78, w: 160, h: 48, t: 'Core + edge UPF', s: 'routing, slicing' },
        { id: 'orch', x: 710, y: 158, w: 160, h: 48, t: 'Comms agent', s: 'topology + power control', cls: 'ai' },
      ],
      edges: [
        { a: 'leo', b: 'uav', t: 'Ku NTN' }, { a: 'leo', b: 'gw', t: 'Ka feeder' }, { a: 'leo', b: 'leo2', t: 'FSO ISL' },
        { a: 'uav', b: 'mesh', cls: 'ok' }, { a: 'mesh', b: 'gnb', t: 'fronthaul', cls: 'ok' },
        { a: 'gnb', b: 'ue' },
        { a: 'gw', b: 'core' }, { a: 'core', b: 'orch', cls: 'ai' }, { a: 'orch', b: 'mesh', cls: 'ai', bend: 60 },
      ],
      texts: [{ t: 'every node is a relay candidate — routing is a decision, not a diagram', x: 20, y: 275, cls: 'dg-s' }],
    },
    left: [
      { h: 'INPUTS', items: ['Traffic demand per user / agent / task', 'Channel state (CSI), interference, blockage', 'Positions, velocities, energy budgets', 'Spectrum and regulatory constraints'] },
      { h: 'PROCESSING', items: ['Topology and relay selection', 'Beamforming and interference coordination', 'Power / bandwidth / MCS allocation', 'Handover between terrestrial and NTN'] },
    ],
    right: [
      { h: 'OUTPUTS', tone: 'ok', items: ['End-to-end reachability with SLA classes', 'Achieved rate, latency, outage per link', 'Predicted link quality for planners'] },
      { h: 'INTERFACES', tone: 'ai', items: ['▼ from L3: platform positions and energy', '▲ to L5/L13: achievable rates as constraints', 'Comms agent (L10) owns the control policy'] },
    ],
    tech: ['3GPP NTN (Rel-17/18)', '5G NR / 6G candidates', 'mmWave', 'FSO / optical ISL', 'O-RAN', 'NVIDIA Sionna', 'TR 38.901 channel models'],
    metrics: [['&gt;100 Mb/s', 'aggregate user throughput'], ['&lt;50 ms', 'edge RTT'], ['&lt;1%', 'in-mission outage'], ['n+1', 'independent paths per critical flow']],
    note: 'Communication is treated as a controlled resource with a learned policy — not as plumbing that either works or does not.',
    spec: {
      visual: 'Global-to-local communication scene where each link type is visually distinct: solid beams for data, dashed marching lines for control, a thin white line for the optical ISL.',
      scene3d: 'Two satellites at 46–48 m translating on X; 6-UAV mesh at 22 m with 26 m mesh range; gateway; three towers with coverage cones; six ground users.',
      components: ['6 labelled link types', 'Coverage cones', 'Gateway + towers + users'],
      dataflow: 'Sat→ground feeder, sat→UAV NTN, UAV↔UAV mesh, UAV→tower fronthaul, direct 5G/6G access, satellite↔satellite optical.',
      animation: ['Packets march at different rates per link class', 'Satellites drift, swarm re-forms mesh'],
      text: 'Link topology graph plus inputs/processing/outputs and hard network KPIs.',
      message: 'Connectivity is an optimisation problem solved continuously by a learning agent, with n+1 redundancy for anything mission-critical.',
    },
  }),

  L(5, 'Edge computing — putting the loop where the latency is', {
    sub: 'Purpose: execute perception, control and local decisions close to the actuator so that autonomy survives a lost link, and reserve the cloud for what genuinely needs scale.',
    scene: 'l5Edge',
    stageTag: 'L5 · EDGE COMPUTING',
    caption: 'Exploded onboard compute module and the four-tier closed-loop latency budget.',
    diagram: {
      type: 'stack',
      title: 'COMPUTE PLACEMENT DECISION',
      bh: 38,
      items: [
        { t: 'Hard real-time control (IMU→motor)', s: 'must never leave the vehicle', l: '&lt;10 ms', cls: 'bad' },
        { t: 'Perception + local planning', s: 'onboard GPU / DLA, TensorRT', l: '10–50 ms', cls: 'ok' },
        { t: 'Multi-agent fusion, twin update, mapping', s: 'edge server at the gateway', l: '50–200 ms' },
        { t: 'LLM reasoning, RAG, mission re-planning', s: 'regional cloud, cached results', l: '0.2–2 s', cls: 'ai' },
        { t: 'Training, large-scale simulation, analytics', s: 'central GPU cluster', l: 'minutes–hours', cls: 'warn' },
      ],
    },
    left: [
      { h: 'INPUTS', items: ['Raw and pre-processed sensor streams', 'Deployed model artefacts + configs', 'Local mission context and geofences'] },
      { h: 'PROCESSING', items: ['Quantised inference (INT8/FP8) with TensorRT', 'Sensor fusion and state estimation', 'Local decision making under link loss', 'Store-and-forward when disconnected'] },
    ],
    right: [
      { h: 'OUTPUTS', tone: 'ok', items: ['Detections, tracks, local maps', 'Control setpoints and mode changes', 'Compressed summaries for the platform'] },
      { h: 'INTERFACES', tone: 'ai', items: ['▼ from L4: whatever bandwidth actually exists', '▲ to L6/L7: fused state and summaries', 'Degraded-mode contract with the safety plane monitors'] },
    ],
    tech: ['Jetson Orin / AGX', 'TensorRT', 'CUDA', 'Triton', 'ROS 2 + DDS', 'K3s / KubeEdge', 'ONNX', 'gRPC'],
    metrics: [['1–20 ms', 'onboard inference'], ['&gt;30 FPS', 'perception rate'], ['100%', 'autonomy retained on link loss'], ['&lt;15 W', 'inference power budget']],
    note: 'The rule is simple: if losing the link would break the loop, the loop belongs on the vehicle.',
    spec: {
      visual: 'An exploded onboard compute stack (sensor IO, CPU, GPU, NPU, radio) as glowing PCB plates with components, plus a four-bar latency ladder.',
      scene3d: 'Five 11 × 7 m plates spaced 2.4 m with 9 procedural chips each; NVIDIA-green data spine with bidirectional packets; a UAV hovering above the stack; latency bars scaled by budget.',
      components: ['5 compute plates', 'Bidirectional spine', 'Latency ladder (onboard / edge / cloud / satellite)', '“Placement rule” panel'],
      dataflow: 'Sensors → CPU/GPU/NPU → radio, with results returning down the spine to the actuator.',
      animation: ['Packets flow up and down the module', 'Rotors spin above', 'Latency bars glow at different intensities'],
      text: 'Compute placement stack with explicit latency classes.',
      message: 'Latency defines architecture. Placement of compute is a safety decision, not an infrastructure preference.',
    },
  }),

  L(6, 'Digital twin — a runnable copy of the mission environment', {
    sub: 'Purpose: maintain a physically accurate, continuously synchronised virtual replica in which the platform can measure, predict, rehearse and validate before acting in the real world.',
    scene: 'l6DigitalTwin',
    stageTag: 'L6 · DIGITAL TWIN',
    caption: 'Left: physical Taipei. Right: synchronised twin. Up-arrow: telemetry. Down-arrow: optimised policy.',
    diagram: {
      type: 'chain',
      title: 'SYNCHRONISATION LOOP',
      items: [
        { t: 'Physical state', s: 'poses, sensors, network, weather' },
        { t: 'State estimation', s: 'fuse + align to twin frame', cls: 'accent' },
        { t: 'Twin update', s: 'geometry, semantics, channel model', cls: 'ok' },
        { t: 'Predict / rehearse', s: 'N futures in parallel', cls: 'ai' },
        { t: 'Policy or plan back', s: 'validated before execution', cls: 'ai' },
      ],
      note: 'Closed loop: physical → twin → prediction → policy → physical, with a bounded synchronisation age.',
    },
    left: [
      { h: 'WHAT IS TWINNED', items: ['Terrain, buildings, interiors where needed', 'Every agent (UAV, UGV, satellite) with its dynamics', 'Radio environment (path loss, blockage, interference)', 'Weather, traffic, crowds, energy state', 'Users and their demand'] },
      { h: 'INPUTS', tone: 'ok', items: ['GIS + as-built models', 'Live telemetry and fused perception', 'Network measurements (CSI, RSRP, throughput)'] },
    ],
    right: [
      { h: 'PROCESSING', items: ['Geometric and semantic alignment', 'Physics: flight dynamics, contact, sensor rendering', 'Radio propagation on the twin geometry', 'Massively parallel what-if rollouts'] },
      { h: 'OUTPUTS → INTERFACES', tone: 'ai', items: ['Predicted risk, coverage, energy and time', 'Validated policies and trajectories', '▲ to L10–L12: environment for agents and training', '▼ from L5/L7: state to synchronise on'] },
    ],
    tech: ['NVIDIA Omniverse', 'Isaac Sim', 'USD / OpenUSD', 'Isaac Lab', 'QGIS / OSM', 'SUMO (traffic)', 'Sionna RT (radio)', 'STK (orbits)'],
    metrics: [['&lt;200 ms', 'sync age for control-relevant state'], ['&lt;1 m', 'geometric twin error'], ['&lt;3 dB', 'radio model error vs measurement'], ['10³–10⁶', 'parallel rollouts per decision batch']],
    note: 'The twin is not a visualisation. It is the place where the platform is allowed to be wrong.',
    spec: {
      visual: 'Split screen: warm-lit physical city on the left, mint wireframe-boxed twin on the right, both containing the same UAV in the same pose. Two large arrows between them.',
      scene3d: 'Identical instanced city seed (31) rendered twice with different palettes; twin UAV copies the real UAV transform every frame; a mint bounding volume marks the simulated domain; “Δt SYNC < 200 ms” label pulses.',
      components: ['Physical city + vehicles + UAV', 'Twin city + vehicles + UAV', 'Telemetry arrow (cyan)', 'Policy arrow (violet)', 'Sync-age indicator'],
      dataflow: 'Left→right: telemetry, pose, sensors, network state. Right→left: optimised policy, predicted risk, plan.',
      animation: ['Real UAV flies a Lissajous path; twin UAV mirrors it exactly', 'Both arrows pulse out of phase', 'Sync label breathes at 1.6 Hz'],
      text: 'What is twinned, inputs, processing, outputs, and the twin’s accuracy budget.',
      message: 'A twin with a bounded synchronisation age and quantified fidelity is what makes pre-validated autonomy possible.',
      production: 'Camera (0,26,58) → (0,6,0), 48° FOV. Keep the two halves at identical scale and camera distance so the viewer reads them as the same city.',
    },
  }),

  L(7, 'Data platform — the memory of the whole system', {
    sub: 'Purpose: capture every observation, decision and outcome in a replayable, lineage-tracked form so that training, certification and forensics are all possible after the fact.',
    scene: 'l7Data',
    stageTag: 'L7 · DATA PLATFORM',
    caption: 'Seven source classes → ingest → bronze → silver → gold, then out to training, twin, RAG and analytics.',
    diagram: {
      type: 'stack',
      title: 'MEDALLION LAYOUT WITH MISSION SEMANTICS',
      bh: 38,
      items: [
        { t: 'Ingest bus', s: 'Kafka / Zenoh bridges, back-pressure aware', l: 'stream', cls: 'accent' },
        { t: 'Bronze — immutable raw', s: 'exactly what the sensor produced', l: 'append-only' },
        { t: 'Silver — curated', s: 'calibrated, time-aligned, geo-referenced', l: 'joinable', cls: 'ok' },
        { t: 'Gold — training & serving', s: 'datasets, features, embeddings, labels', l: 'versioned', cls: 'ok' },
        { t: 'Catalogue + lineage', s: 'mission ID, asset ID, model version, consent', l: 'governance', cls: 'ai' },
      ],
    },
    left: [
      { h: 'INPUTS', items: ['Telemetry, video, LiDAR, RF, spectrum', 'Satellite products and GIS layers', 'Simulation and synthetic data', 'Operator actions and annotations', 'Model decisions and their justifications'] },
    ],
    right: [
      { h: 'PROCESSING', items: ['Schema-on-write for training sets, schema-on-read for exploration', 'Deduplication, quality scoring, PII handling', 'Bit-exact mission replay', 'Automatic dataset cards and drift statistics'] },
      { h: 'INTERFACES', tone: 'ai', items: ['▼ from L2/L5/L6: measurements + fused state', '▲ to L8: documents and embeddings', '▲ to L12: training sets and replay buffers'] },
    ],
    tech: ['Kafka / Zenoh', 'Parquet / Delta / Iceberg', 'MCAP / rosbag2', 'S3-compatible object store', 'DVC / LakeFS', 'Feature store', 'OpenLineage'],
    metrics: [['TB/day', 'ingest per active fleet'], ['100%', 'records with time+pose+mission ID'], ['bit-exact', 'replay guarantee'], ['&lt;24 h', 'field data → training-ready']],
    note: 'If a mission cannot be replayed exactly, its outcome cannot be explained, certified or learned from.',
    spec: {
      visual: 'Seven glowing source boxes above four labelled data-tier slabs, with beams converging downward and dashed consumer links leaving toward the viewer.',
      scene3d: 'Sources at y=19 spaced 6.2 m; tiers at y=12/9/6/3 as 26 × 10 m slabs; four consumer labels at z=13 fed by dashed links.',
      components: ['7 source classes', '4 medallion tiers', '4 consumers', '“Contract” panel'],
      dataflow: 'Sources → ingest → bronze → silver → gold → consumers, with lineage recorded at every hop.',
      animation: ['Packets fall from sources into ingest', 'Consumer links pull dashed packets outward', 'Slow camera orbit'],
      text: 'Medallion stack with mission semantics; replay and lineage guarantees.',
      message: 'Data engineering is what converts flights into assets. Without lineage there is no certification story.',
    },
  }),

  L(8, 'RAG & knowledge — the AI must not guess what it can look up', {
    sub: 'Purpose: give every agent grounded access to maps, regulations, manuals, mission history and live sensor summaries, so that decisions cite evidence instead of relying on pretraining.',
    scene: 'l8RAG',
    stageTag: 'L8 · RAG / KNOWLEDGE',
    caption: 'Documents → embedding model → vector database + knowledge graph → grounded agent answer.',
    diagram: {
      type: 'chain',
      title: 'RETRIEVAL PATH',
      items: [
        { t: 'Corpus', s: 'docs · maps · history · manuals' },
        { t: 'Chunk + embed', s: 'multimodal encoders', cls: 'accent' },
        { t: 'Vector DB + KG', s: 'ANN search + relations', cls: 'ok' },
        { t: 'Retrieve → rerank', s: 'hybrid BM25 + dense', cls: 'ok' },
        { t: 'Grounded answer', s: 'with citations + confidence', cls: 'ai' },
      ],
    },
    left: [
      { h: 'KNOWLEDGE SOURCES', items: ['Airspace rules, NOTAMs, local regulation', 'Vehicle and payload manuals, checklists', 'Every previous mission and its outcome', 'Maps, building footprints, floor plans', 'Satellite products and change history', 'Live sensor summaries from the current mission'] },
    ],
    right: [
      { h: 'PROCESSING', items: ['Multimodal chunking (text, image, geometry, tabular)', 'Hybrid retrieval: dense + sparse + spatial filter', 'Graph traversal for entity relations', 'Reranking, then citation-bound generation'] },
      { h: 'INTERFACES', tone: 'ai', items: ['▼ from L7: curated corpora + embeddings', '▲ to L9/L10: grounded context for models and agents', 'Every answer returns sources and a confidence'] },
    ],
    tech: ['Vector DB (FAISS / Milvus / pgvector)', 'Knowledge graph (Neo4j / RDF)', 'CLIP-style multimodal embeddings', 'BM25 hybrid retrieval', 'Cross-encoder rerankers', 'LLM / VLM with tool calls'],
    metrics: [['&gt;0.9', 'retrieval recall@10 on mission queries'], ['&lt;300 ms', 'retrieval latency at the edge'], ['100%', 'answers with citations'], ['0', 'ungrounded safety-critical claims']],
    note: 'The point of RAG here is accountability: an autonomous decision that cannot cite its basis cannot be approved.',
    spec: {
      visual: 'Floating document planes orbiting inward to a rotating embedding cube, which feeds a coloured vector point cloud on the left and a knowledge graph sphere on the right; an agent orb below queries both.',
      scene3d: 'Six document planes bobbing at radius 15; embedding cube 5 × 3 × 5 m rotating at 0.5 rad/s; 900-point vector cloud in 6 clusters; 30-node graph with proximity edges; query orb at z=15.',
      components: ['6 corpus classes', 'Embedding model', 'Vector DB', 'Knowledge graph', 'Query agent', 'Grounded-answer label'],
      dataflow: 'Corpus → embeddings → indexes; agent query → retrieval from both indexes → grounded answer → mission decision.',
      animation: ['Documents bob and stream into the cube', 'Cube rotates', 'Cloud and graph rotate at different rates', 'Query links pulse both ways'],
      text: 'Knowledge sources, hybrid retrieval processing, and the citation guarantee.',
      message: 'Grounding is a safety feature: retrieval turns a plausible answer into a defensible one.',
    },
  }),

  L(9, 'AI models — specialised heads on shared backbones', {
    sub: 'Purpose: supply the predictive capabilities the agents reason with: perception, language grounding, forecasting, anomaly detection, trajectory and wireless channel prediction.',
    scene: 'l9Models',
    stageTag: 'L9 · AI MODELS',
    caption: 'Eight model families sitting on a shared foundation-model substrate.',
    diagram: {
      type: 'matrix',
      title: 'MODEL PORTFOLIO · TASK → OUTPUT → CONSUMER',
      ih: 27,
      cols: [
        { t: 'PERCEPTION', cls: 'accent', items: [{ t: 'detect / segment / track' }, { t: '→ objects, masks, tracks' }, { t: '→ L6 twin, L10 agents' }] },
        { t: 'LANGUAGE & VLM', cls: 'ai', items: [{ t: 'ground text ↔ imagery' }, { t: '→ answers, referring targets' }, { t: '→ operators, L10 agents' }] },
        { t: 'PREDICTION', cls: 'ok', items: [{ t: 'trajectory / weather / demand' }, { t: '→ distributions, horizons' }, { t: '→ planners, L13' }] },
        { t: 'WIRELESS', cls: 'accent', items: [{ t: 'CSI, path loss, blockage' }, { t: '→ achievable rate maps' }, { t: '→ L4 comms agent' }] },
        { t: 'INTEGRITY', cls: 'bad', items: [{ t: 'anomaly / OOD / drift' }, { t: '→ alarms + uncertainty' }, { t: '→ L14 human, safety plane' }] },
      ],
    },
    left: [
      { h: 'INPUTS', items: ['Curated multimodal datasets (L7)', 'Grounded context (L8)', 'Simulation-generated data (L6)'] },
      { h: 'PROCESSING', items: ['Pretrain or adopt foundation backbones', 'Fine-tune specialised heads per task', 'Distil + quantise for the edge', 'Calibrate uncertainty, not just accuracy'] },
    ],
    right: [
      { h: 'OUTPUTS', tone: 'ok', items: ['Predictions with calibrated confidence', 'Embeddings reused across tasks', 'Explanations and saliency for operators'] },
      { h: 'INTERFACES', tone: 'ai', items: ['▲ to L10: perception + prediction as tools', '▲ to L11: policies and world models', '▼ from L12: new weights, versioned'] },
    ],
    tech: ['PyTorch', 'CUDA / cuDNN', 'TensorRT', 'Transformers / ViT', 'VLM (open weights)', 'Diffusion for synthetic data', 'Gaussian processes for uncertainty'],
    metrics: [['mAP / IoU', 'perception quality'], ['&lt;15%', 'sim-to-real gap'], ['ECE &lt; 0.05', 'calibration error'], ['INT8', 'edge deployment precision']],
    note: 'Models are components with versions, contracts and expiry — not the product.',
    spec: {
      visual: 'Eight translucent model blocks in two rows with internal “layer” bars pulsing, all fed from a wide foundation-model slab below.',
      scene3d: '7.4 × 4 × 3.4 m blocks at two heights; 5 pulsing internal layer bars per block; 40 × 8 m foundation slab at y=1; violet beams from the slab to each block.',
      components: ['8 model families', 'Foundation substrate', 'Beams representing shared representations'],
      dataflow: 'Foundation backbone → specialised heads → consumers named in the diagram.',
      animation: ['Internal bars breathe at different phases', 'Blocks yaw ±0.05 rad', 'Beam packets rise from the substrate'],
      text: 'Portfolio matrix mapping task → output → consumer, plus calibration metrics.',
      message: 'A portfolio of calibrated, versioned models on shared backbones is cheaper and safer than one monolithic model.',
    },
  }),

  L(10, 'Agentic AI — autonomous agents that plan, negotiate and act', {
    sub: 'Purpose: convert mission intent into coordinated action through specialised agents that hold state, use tools, communicate on a shared bus and can be audited individually.',
    scene: 'l10Agentic',
    stageTag: 'L10 · AGENTIC AI',
    caption: 'Ten agents on an orchestration bus, tasking a UAV swarm and a ground robot below; the safety agent holds a veto.',
    diagram: {
      type: 'graph',
      title: 'AGENT TOPOLOGY',
      h: 300,
      nodes: [
        { id: 'm', x: 400, y: 20, w: 190, h: 46, t: 'MISSION AGENT', s: 'intent, constraints, success criteria', cls: 'ai' },
        { id: 'p', x: 400, y: 92, w: 190, h: 46, t: 'MISSION PLANNER', s: 'decompose → task graph', cls: 'ai' },
        { id: 'n', x: 90, y: 168, w: 150, h: 44, t: 'NAVIGATION', s: 'routes, airspace', cls: 'accent' },
        { id: 'c', x: 258, y: 168, w: 150, h: 44, t: 'COMMUNICATION', s: 'topology, power', cls: 'accent' },
        { id: 'e', x: 426, y: 168, w: 150, h: 44, t: 'ENERGY', s: 'endurance, charging', cls: 'warn' },
        { id: 'r', x: 594, y: 168, w: 150, h: 44, t: 'RESOURCE ALLOC', s: 'compute, spectrum', cls: 'warn' },
        { id: 'k', x: 762, y: 168, w: 150, h: 44, t: 'KNOWLEDGE', s: 'RAG, regulations', cls: 'ai' },
        { id: 'pe', x: 174, y: 240, w: 150, h: 44, t: 'PERCEPTION', s: 'fuse, detect, verify', cls: 'ok' },
        { id: 'dt', x: 342, y: 240, w: 150, h: 44, t: 'DIGITAL TWIN', s: 'rehearse, predict', cls: 'ok' },
        { id: 's', x: 510, y: 240, w: 150, h: 44, t: 'SAFETY', s: 'veto + fallback', cls: 'bad' },
        { id: 'f', x: 678, y: 240, w: 150, h: 44, t: 'FLEET MANAGER', s: 'assign, monitor, replace' },
      ],
      edges: [
        { a: 'm', b: 'p', cls: 'ai' },
        { a: 'p', b: 'n', cls: 'ai' }, { a: 'p', b: 'c', cls: 'ai' }, { a: 'p', b: 'e', cls: 'ai' }, { a: 'p', b: 'r', cls: 'ai' }, { a: 'p', b: 'k', cls: 'ai' },
        { a: 'n', b: 'pe' }, { a: 'c', b: 'dt' }, { a: 'e', b: 's', cls: 'bad' }, { a: 'r', b: 'f' },
        { a: 's', b: 'f', cls: 'bad', t: 'veto' },
      ],
      texts: [{ t: 'FLEET MANAGER → UAV / ROBOT / SATELLITE (actuation)', x: 678, y: 296, cls: 'dg-h' }],
    },
    left: [
      { h: 'EVERY AGENT HAS', tone: 'ai', items: ['<b>Objective</b> — a measurable goal', '<b>State</b> — what it believes right now', '<b>Memory</b> — episodic + long-term via RAG', '<b>Tools</b> — models, solvers, twin, APIs', '<b>Reasoning</b> — plan, critique, replan', '<b>Comms</b> — messages on the shared bus', '<b>Action</b> — bounded, logged, revocable'] },
    ],
    right: [
      { h: 'COORDINATION', items: ['Shared blackboard for world state', 'Contract-net style task bidding', 'Explicit conflict resolution order', 'Safety agent can veto any action'] },
      { h: 'INTERFACES', tone: 'ok', items: ['▼ from L8/L9: knowledge and predictions', '▲ to L11: goals and constraints for control', '▲ to L14: explanations and approval requests'] },
    ],
    tech: ['LLM planners with tool use', 'contract-net / auction protocols', 'behaviour trees', 'MCTS / LP solvers', 'ROS 2 actions', 'OpenTelemetry for agent traces'],
    metrics: [['&lt;2 s', 'intent → task assignment'], ['&lt;0.1/h', 'human interventions per UAV'], ['100%', 'agent actions logged with rationale'], ['1', 'agent with veto authority'], ['10', 'specialised agents']],
    note: 'Agentic autonomy without an audit trail is unusable in regulated airspace. Every decision is attributable to an agent, an input and a model version.',
    spec: {
      visual: 'Ten glowing agent orbs on an elliptical orchestration bus above a working city, with tasking beams descending to real assets and a red safety-veto beam.',
      scene3d: 'Orbs at radius 13 (Z compressed 0.6) at y≈24; torus bus radius 9.4 scaled 1 × 0.6; dashed agent-to-agent links skipping 3 positions; three tasking beams to the swarm; red beam from the safety agent to the UGV.',
      components: ['10 labelled agents', 'Orchestration bus', 'Agent↔agent message links', 'Tasking beams', 'Safety veto beam'],
      dataflow: 'Mission intent enters at the planner, decomposes to specialised agents, converges on the fleet manager, and only then reaches hardware — unless safety vetoes.',
      animation: ['Orb cages and rings counter-rotate', 'Messages march between agents', 'Tasking beams pulse to the swarm', 'Safety beam is always visible'],
      text: 'Agent anatomy (7 required properties) + coordination rules + the audit requirement.',
      message: 'Agentic AI is a control architecture with accountability, not a chat pattern.',
    },
  }),

  L(11, 'Physical AI — perception to actuation, closed on hardware', {
    sub: 'Purpose: close the loop between understanding and motion: perceive, build a world model, reason, plan, control, act — repeatedly, on the vehicle, within its physical limits.',
    scene: 'l11PhysicalAI',
    stageTag: 'L11 · PHYSICAL AI',
    caption: 'A robot and a UAV working in a structured environment, with the six-stage loop rendered above them.',
    diagram: {
      type: 'loop',
      title: 'THE PHYSICAL AI LOOP (runs on the vehicle)',
      h: 300,
      ellipse: 1.6,
      center: 'CLOSED LOOP',
      centerSub: '10–100 Hz',
      items: [
        { t: 'PERCEPTION', s: 'detect, segment, track', cls: 'accent' },
        { t: 'UNDERSTANDING', s: 'semantics + affordances', cls: 'accent' },
        { t: 'REASONING', s: 'goals vs constraints', cls: 'ai' },
        { t: 'PLANNING', s: 'trajectory + task order', cls: 'ai' },
        { t: 'CONTROL POLICY', s: 'RL or MPC', cls: 'ok' },
        { t: 'ACTUATION', s: 'motors, gimbal, radio', cls: 'ok' },
      ],
    },
    left: [
      { h: 'INPUTS', items: ['Calibrated sensor streams (L2)', 'Local map + twin prior (L6)', 'Goals and constraints from agents (L10)'] },
      { h: 'PROCESSING', items: ['World model update (geometry + semantics + dynamics)', 'Reasoning over feasibility and risk', 'Trajectory optimisation / learned policy', 'Low-level control with hard limits'] },
    ],
    right: [
      { h: 'OUTPUTS', tone: 'ok', items: ['Actuator commands (thrust, steering, gimbal, TX power)', 'Executed trajectory and its deviation', 'Experience tuples for learning (L12)'] },
      { h: 'INTERFACES', tone: 'ai', items: ['▼ from L10: what to achieve, never how to twitch', '▲ to L12: trajectories, rewards, failures', 'Safety monitors wrap the policy output'] },
    ],
    tech: ['RL policies (PPO / SAC)', 'MPC', 'visual-inertial odometry', 'occupancy + ESDF mapping', 'Isaac Lab-trained controllers', 'ros2_control'],
    metrics: [['10–100 Hz', 'loop rate'], ['&lt;10 ms', 'control latency'], ['&lt;0.5 m', 'trajectory tracking error'], ['0', 'commands outside the envelope']],
    note: 'Physical AI is where errors have mass. Every learned output passes through a classical limit-check before it reaches an actuator.',
    spec: {
      visual: 'Structured obstacle environment with a moving UGV (spinning LiDAR sweeping the ground) and a UAV circling above; a six-station ring loop hovers over the scene with packets running around it.',
      scene3d: '16 procedural obstacle boxes; UGV oscillating on X with LiDAR fan at 2.2 rad/s; UAV on a circular path at 9 m; six 2.2 m station discs at radius 15 (Z scaled 0.5) at y=20 connected by curved beams.',
      components: ['UGV + LiDAR', 'UAV', 'Obstacles', '6 loop stations', 'observe / act links into the loop'],
      dataflow: 'World → perception station → around the ring → actuation station → back into the world (visualised by the observe/act links).',
      animation: ['Packets circulate the ring continuously', 'LiDAR sweeps', 'Robot and UAV move on independent paths'],
      text: 'Loop diagram with rates + the envelope-check rule.',
      message: 'Autonomy is a closed loop on hardware at a guaranteed rate, with classical limits around learned components.',
    },
  }),

  L(12, 'Learning — the platform improves with every mission', {
    sub: 'Purpose: convert operational experience into better policies and models through reinforcement learning, multi-agent RL, federated learning, imitation and self-supervision — without shipping raw sensitive data.',
    scene: 'l12Learning',
    stageTag: 'L12 · LEARNING',
    caption: 'Central GPU training, federated aggregation of on-device models, and a multi-agent RL arena.',
    diagram: {
      type: 'chain',
      title: 'LEARNING MODES AND WHERE THEY RUN',
      items: [
        { t: 'Self-supervised', s: 'unlabelled sensors → representations', cls: 'accent' },
        { t: 'Imitation', s: 'operator demos → warm start', cls: 'ok' },
        { t: 'RL in the twin', s: 'single-agent control', cls: 'ai' },
        { t: 'MARL in the twin', s: 'swarm coordination', cls: 'ai' },
        { t: 'Federated', s: 'on-device updates only', cls: 'ok' },
        { t: 'Continual', s: 'field data → next candidate', cls: 'warn' },
      ],
    },
    left: [
      { h: 'INPUTS', items: ['Replay buffers and trajectories (L7)', 'Simulated experience at scale (L6)', 'Operator demonstrations and corrections (L14)', 'On-device gradients from the fleet'] },
      { h: 'PROCESSING', items: ['Distributed RL / MARL rollouts', 'Secure aggregation (FedAvg and variants)', 'Curriculum + domain randomisation', 'Offline evaluation before any rollout'] },
    ],
    right: [
      { h: 'OUTPUTS', tone: 'ok', items: ['Candidate policies and model versions', 'Performance deltas per scenario family', 'Rejected candidates with reasons (kept)'] },
      { h: 'INTERFACES', tone: 'ai', items: ['▼ from L6/L7: environments and data', '▲ to L9/L11: new weights after certification', 'Never bypasses the 9-level validation gates'] },
    ],
    tech: ['Isaac Lab', 'PPO / SAC / MADDPG / QMIX', 'FedAvg / FedProx / secure aggregation', 'Ray / torchrun', 'differential privacy', 'MLflow / W&B'],
    metrics: [['10³–10⁶', 'parallel training environments'], ['&lt;15%', 'sim-to-real gap'], ['0 raw bytes', 'sensitive data leaving devices (FL mode)'], ['&lt;24 h', 'mission → candidate model']],
    note: 'Learning is a governed pipeline: nothing reaches an aircraft because it looked better on a chart.',
    spec: {
      visual: 'Three learning modalities in one frame: a GPU pod at the back, six fleet devices carrying local models in a ring, and a violet MARL arena to the left.',
      scene3d: 'GPU pod 2 × 4 racks at z=−18; 4 UAVs + 2 UGVs on a ring of radius 22 with pulsing “local model θᵢ” chips; amber aggregation orb at (0,12,−6); MARL arena disc r=15 with a 7-UAV violet mesh.',
      components: ['Central training cluster', 'Federated devices + local models', 'Aggregation orb', 'MARL arena', '“Learning modes” panel'],
      dataflow: 'Devices → dashed update links → aggregation orb → GPU cluster; mint beams carry the new global model back to every device.',
      animation: ['Local-model chips pulse as they train', 'Update packets flow inward, model packets flow outward', 'MARL swarm re-forms its mesh continuously'],
      text: 'Six learning modes mapped to where they run + the governance rule.',
      message: 'Continuous improvement is an architectural feature with privacy and certification constraints built in.',
    },
  }),

  L(13, 'Orchestration — allocating scarce resources under pressure', {
    sub: 'Purpose: decide continuously which asset does what, with which spectrum, compute, energy and airspace, and re-decide the moment reality changes.',
    scene: 'l13Orchestration',
    stageTag: 'L13 · ORCHESTRATION',
    caption: 'Task-graph board with five mission lanes above the assets executing them, and four live resource ledgers.',
    diagram: {
      type: 'graph',
      title: 'ORCHESTRATION CONTROL LOOP',
      h: 250,
      nodes: [
        { id: 'i', x: 20, y: 40, w: 170, h: 48, t: 'Mission intent', s: 'objectives + constraints', cls: 'ai' },
        { id: 'd', x: 230, y: 40, w: 170, h: 48, t: 'Task decomposition', s: 'DAG of tasks', cls: 'ai' },
        { id: 'a', x: 440, y: 40, w: 170, h: 48, t: 'Allocation', s: 'asset × task × resource', cls: 'warn' },
        { id: 'x', x: 650, y: 40, w: 170, h: 48, t: 'Execution', s: 'dispatch + monitor' },
        { id: 'm', x: 650, y: 150, w: 170, h: 48, t: 'Measurement', s: 'KPI vs plan', cls: 'accent' },
        { id: 'r', x: 440, y: 150, w: 170, h: 48, t: 'Re-allocation', s: 'preempt, replace, degrade', cls: 'warn' },
        { id: 'l', x: 230, y: 150, w: 170, h: 48, t: 'Resource ledgers', s: 'compute · spectrum · energy · airspace' },
        { id: 'e', x: 20, y: 150, w: 170, h: 48, t: 'Escalation', s: 'to human when unresolvable', cls: 'bad' },
      ],
      edges: [
        { a: 'i', b: 'd', cls: 'ai' }, { a: 'd', b: 'a', cls: 'ai' }, { a: 'a', b: 'x' },
        { a: 'x', b: 'm', cls: 'accent' }, { a: 'm', b: 'r', cls: 'warn' }, { a: 'r', b: 'l' }, { a: 'l', b: 'e', cls: 'bad' },
        { a: 'r', b: 'a', cls: 'warn', bend: -70 },
      ],
    },
    left: [
      { h: 'INPUTS', items: ['Mission objectives and priorities', 'Asset availability, health, energy', 'Achievable link rates (L4) and compute (L5)', 'Airspace and regulatory constraints'] },
      { h: 'PROCESSING', items: ['Task decomposition into a DAG', 'Constrained assignment (assets × tasks × resources)', 'Preemption and graceful degradation policies', 'Model and firmware rollout scheduling'] },
    ],
    right: [
      { h: 'OUTPUTS', tone: 'ok', items: ['Per-asset task queues with deadlines', 'Resource grants (spectrum, compute, energy, airspace slots)', 'Explicit degradation decisions when demand exceeds supply'] },
      { h: 'INTERFACES', tone: 'ai', items: ['▼ from L10: agent-level plans and bids', '▲ to L3: executable task queues', '▲ to L14: what was sacrificed and why'] },
    ],
    tech: ['Kubernetes-style scheduling concepts', 'MILP / CP-SAT solvers', 'auction protocols', 'network slicing', 'ROS 2 actions', 'GitOps for fleet config'],
    metrics: [['&lt;2 s', 'replan latency after a failure'], ['&gt;85%', 'asset utilisation'], ['&lt;5%', 'tasks missed without notice'], ['100%', 'degradations logged with rationale']],
    note: 'Orchestration is where the system admits that resources are finite — explicitly, and with a record of every trade-off.',
    spec: {
      visual: 'A mission-control task board: five swim-lanes with glowing task cards, dashed assignment links descending to real assets, and four resource gauges.',
      scene3d: 'Board plane 30 × 12 m at y=20; five lanes with four pulsing cards each; five assets (3 UAV, 1 UGV, 1 satellite pass) at y≈6; four canvas gauges at y=12.5.',
      components: ['Task board with lanes', 'Assignment links', 'Assets', 'Compute / spectrum / energy / airspace ledgers'],
      dataflow: 'Board → assignment links → assets; measurement returns implicitly through the gauges.',
      animation: ['Cards fade in and out as tasks are (re)assigned', 'Assignment links march', 'Gauges oscillate with load'],
      text: 'Control-loop graph including escalation, plus utilisation metrics.',
      message: 'Autonomy must decide what NOT to do; that decision has to be visible and logged.',
    },
  }),

  L(14, 'Human & operator — authority, not supervision theatre', {
    sub: 'Purpose: give humans the smallest set of decisions that actually require judgement, with enough explanation to make them quickly, and absolute authority to intervene.',
    scene: 'l14Human',
    stageTag: 'L14 · HUMAN / OPERATOR',
    caption: 'Mission control: status wall, alert wall with an approval request, AI accountability wall, and a holographic twin table.',
    diagram: {
      type: 'chain',
      title: 'HUMAN INTERACTION MODES',
      items: [
        { t: 'Monitor', s: 'aggregate state, not raw video', cls: 'accent' },
        { t: 'Be alerted', s: 'ranked, deduplicated, actionable', cls: 'warn' },
        { t: 'Approve', s: 'only where policy requires it', cls: 'ai' },
        { t: 'Intervene', s: 'retask, pause, reroute', cls: 'warn' },
        { t: 'Override', s: 'take manual control instantly', cls: 'bad' },
      ],
      note: 'Design target: fewer than 0.1 interventions per UAV-hour, and every intervention becomes training data.',
    },
    left: [
      { h: 'INPUTS', items: ['Fleet and mission state (aggregated)', 'Ranked alerts with predicted consequences', 'Agent decisions with rationale and confidence', 'Approval requests bound to policy rules'] },
      { h: 'PROCESSING', items: ['Attention management: what deserves a human', 'Explanation generation (why, alternatives, risk)', 'Authority arbitration (who may override what)'] },
    ],
    right: [
      { h: 'OUTPUTS', tone: 'ok', items: ['Approvals, rejections, and constraint changes', 'Manual takeover commands', 'Corrections that become imitation-learning data'] },
      { h: 'INTERFACES', tone: 'ai', items: ['▼ from L10/L13: decisions and escalations', '▲ to L3/L11: authority commands (highest priority)', '▲ to L12: labelled human preferences'] },
    ],
    tech: ['3D mission dashboards', 'WebRTC video on demand', 'explainability (saliency, counterfactuals)', 'RBAC + audit logs', 'digital-twin operator views'],
    metrics: [['&lt;0.1/h', 'interventions per UAV'], ['&lt;5 s', 'alert → informed decision'], ['100%', 'AI actions with an explanation on request'], ['&lt;1 s', 'override takes effect']],
    note: 'The measure of a good autonomy UI is how few decisions it asks for — and how fast it lets a human take everything back.',
    spec: {
      visual: 'Interior mission-control shot: three glowing information walls, three operators at consoles, and a holographic city twin on a round table with a miniature swarm above it.',
      scene3d: 'Walls as canvas panels at z=−14/−15; table cylinder r=6.4 at y=2 with a rotating mini-city and a 4-UAV mesh; three operators with desks and coloured screens; camera dollies laterally.',
      components: ['Mission status wall', 'Alert wall (approval required)', 'AI accountability wall', 'Holographic twin table', 'Operators + consoles'],
      dataflow: 'Platform → walls (aggregated state) → human decision → authority commands back down to the fleet.',
      animation: ['Twin city rotates slowly', 'Mini swarm holds formation above the table', 'Alert banner pulses', 'Camera dollies from −9 to +9 on X'],
      text: 'Five interaction modes and the intervention-rate target.',
      message: 'Human authority is a design requirement; supervision load is a KPI to minimise.',
      production: 'Warm amber key at 0.55 intensity, dark floor, three coloured console screens for depth. Keep FOV at 50° for an interior feel.',
    },
  }),

  L(15, 'Deployment — the infrastructure in operation', {
    sub: 'Purpose: run the platform continuously across multiple regions and domains, with per-region autonomy, global coordination and a single operational picture.',
    scene: 'l15Deployment',
    stageTag: 'L15 · DEPLOYMENT',
    caption: 'Four regions running independently, linked by inter-region mesh and a satellite layer, under one global autonomy control.',
    diagram: {
      type: 'stack',
      title: 'DEPLOYMENT TOPOLOGY',
      bh: 38,
      items: [
        { t: 'Global control plane', s: 'policy, model registry, fleet-wide KPIs', l: 'central', cls: 'ai' },
        { t: 'Satellite layer', s: 'wide-area sensing + NTN backhaul', l: 'space', cls: 'accent' },
        { t: 'Regional autonomy cell', s: 'own edge, own twin slice, own agents', l: 'per region', cls: 'ok' },
        { t: 'Mission cell', s: 'swarm + robots + local network', l: 'per mission', cls: 'ok' },
        { t: 'Asset', s: 'onboard autonomy, always able to stand alone', l: 'per unit', cls: 'warn' },
      ],
      note: 'Autonomy degrades gracefully downward: if the global plane is unreachable, regions run; if a region is unreachable, missions run; if a mission cell is lost, each asset comes home safely.',
    },
    left: [
      { h: 'INPUTS', items: ['Certified models and policies', 'Regional configuration and regulation', 'Mission requests from operators or triggers'] },
      { h: 'PROCESSING', items: ['Region-local autonomy with global policy', 'Cross-region asset sharing when justified', 'Continuous KPI reporting and drift detection'] },
    ],
    right: [
      { h: 'OUTPUTS', tone: 'ok', items: ['Delivered mission outcomes', 'Operational data returning to L7', 'Evidence packages for regulators'] },
      { h: 'INTERFACES', tone: 'ai', items: ['▼ from L12/L13: models and plans', '▲ to L1: physical effect in the world', '▲ to L7/L12: field experience for the next iteration'] },
    ],
    tech: ['multi-region Kubernetes', 'GitOps fleet config', 'model registry + signing', 'OTA update with rollback', 'observability stack', 'regulatory reporting'],
    metrics: [['4+', 'regions in parallel'], ['&gt;99%', 'mission availability'], ['&lt;1 h', 'global policy propagation'], ['0', 'unrecoverable assets']],
    note: 'This is the slide that closes the loop: deployment produces the physical-world change and the data that trains the next version.',
    spec: {
      visual: 'High wide shot of four regional operations on real terrain, each ringed and labelled, with a LEO shell above and a global control orb linked to every region.',
      scene3d: '260 m terrain; four region groups at (−58,10), (0,−34), (56,14), (−10,44) each with a city, 5-UAV mesh swarm, UGV, tower and 20 m ring; orbit shell r=96 at y=30; control orb at (0,56,40).',
      components: ['4 regional cells', 'Satellite layer', 'Inter-region dashed mesh', 'Global control orb'],
      dataflow: 'Satellite downlinks per region, inter-region peer links, and dashed policy links from global control to each region.',
      animation: ['Satellites orbit overhead', 'Each region’s swarm operates independently', 'Policy packets descend from global control', 'Very slow 96 m camera orbit'],
      text: 'Deployment topology stack with the graceful-degradation rule.',
      message: 'The deployed system is hierarchical and survivable: every level can operate when the level above is unreachable.',
    },
  }),
];
