export const OPENING = [
  {
    layout: 'full',
    titleSlide: true,
    scene: 'titleEarthToEdge',
    kicker: 'AUTONOMOUS PHYSICAL AI · SPACE + AIR + GROUND + EDGE + CLOUD',
    title: 'THE AUTONOMOUS <em>AIR–SPACE–GROUND</em> AI INFRASTRUCTURE',
    sub: 'From sensing the physical world to reasoning, learning, deciding and acting autonomously.',
    strip: ['LEO / NTN', '6G MESH', 'UAV SWARM', 'GROUND ROBOTS', 'DIGITAL TWIN', 'AGENTIC AI', 'RAG', 'FEDERATED MARL', 'PHYSICAL AI'],
    stageTag: 'LIVE 3D · ORBIT → EDGE',
    caption: 'One system: 15 architecture layers, 14 development phases, 9 validation levels.',
    spec: {
      visual: 'Cinematic Earth limb from low orbit, LEO shell above, UAV swarm and a living city below, all connected by glowing links.',
      scene3d: 'Earth (r=34) centred at (0,−38,−8) with a fresnel atmosphere shell; 2 orbital planes × 6 satellites at r=44, i=58°; two detailed satellites at 27–31 m carrying the labelled links; instanced city (110 buildings) at y=−3.2; 9-UAV mesh swarm at 13 m; gateway, 3 towers, pedestrians and a UGV.',
      components: ['Earth + atmosphere shader', 'LEO constellation', 'UAV swarm with dynamic mesh links', 'City with moving vehicles', 'Ka-band feeder beam to gateway', 'Sub-6 GHz access beams'],
      dataflow: 'Satellite → UAV → ground (downlink beams, cyan) and ground → UAV → satellite (telemetry, mint). Packets are instanced spheres marching along Bezier curves.',
      animation: ['Earth spins at 0.012 rad/s', 'Satellites orbit at 0.09 rad/s', 'Rotors at ~30 rad/s, UAVs bob and re-form the mesh continuously', 'Camera orbits the scene at 0.03 rad/s'],
      text: 'Title + subtitle only. The image must carry the message: three domains, one network.',
      message: 'This is infrastructure, not a demo: space, air and ground assets operate as a single addressable, learning system.',
      production: 'Camera 48° FOV, authored at (0,12,54) → (0,13,0); the deck then auto-frames it to the content bounding sphere. Key light (40,50,60) 1.05; blue rim 0.75; cyan accent point light; ACES tone map, exposure 1.16. Palette: cyan #35e0ff data, mint #6ef2c0 learning, ice #9fd8ff space.',
    },
  },

  {
    kicker: 'POSITIONING',
    title: 'This is not “an AI model for drones”',
    sub: 'It is a vertically integrated autonomy stack: the physical world is the input, the physical world is the output, and every mission makes the next mission better.',
    scene: 'platformStack',
    stageTag: 'PLATFORM STACK',
    caption: 'Eight functional strata; a bidirectional data spine binds them.',
    left: [
      { h: 'WHAT PEOPLE USUALLY BUILD', tone: 'warn', items: ['A perception model on one airframe', 'A hand-tuned flight mission', 'A dashboard with live video', 'A simulation that never touches hardware'] },
      { h: 'WHY IT STOPS SCALING', items: ['No shared world model → every new asset is a new integration', 'No knowledge layer → the fleet cannot be told <b>why</b>', 'No learning loop → field experience is thrown away'] },
    ],
    right: [
      { h: 'WHAT THIS PLATFORM IS', tone: 'ok', items: ['<b>Sensing → knowledge → reasoning → actuation</b> as one pipeline', 'Assets are interchangeable capabilities, not projects', 'Simulation is a first-class runtime, not a side tool', 'Every mission returns data, models and lessons'] },
      { h: 'CONSEQUENCE', tone: 'ai', text: 'Adding a new airframe, sensor, orbit or city becomes a <b>configuration</b> problem, not a re-engineering programme.' },
    ],
    tech: ['ROS 2', 'PX4', 'Isaac Sim / Isaac Lab', 'Omniverse', 'PyTorch', 'CUDA', 'Kubernetes', 'Vector DB', 'MLflow'],
    metrics: [['15', 'architecture layers'], ['14', 'development phases'], ['9', 'validation levels'], ['1', 'continuous learning loop']],
    note: 'The unit of value is the platform, not the model. Models are replaceable parts inside it.',
    spec: {
      visual: 'Eight translucent holographic slabs stacked in perspective, pierced by a vertical data spine with packets travelling up and down.',
      scene3d: 'Slab width tapers 20 → 17.5 with altitude to force perspective; emissive edge lines colour-coded per stratum; spine at x=0 carries cyan packets up, mint packets down.',
      components: ['Physical world & agents', 'Sensing & communication', 'Edge + cloud compute', 'Digital twin', 'Data + RAG knowledge', 'AI models', 'Agentic + physical AI', 'Continual learning'],
      dataflow: 'Up = observations; down = commands and model updates. The loop closes at the bottom stratum.',
      animation: ['Packets march up and down the spine', 'Slow 0.05 rad/s camera orbit', 'Edge glow breathes on the agentic layer'],
      text: 'Left column = what people usually build. Right column = what this is.',
      message: 'Platform thinking is the differentiator; the AI model is one replaceable component.',
      production: 'Camera (22,15,40) → (0,8,0), 42° FOV. Slabs: MeshStandard opacity 0.5, emissive intensity 0.12, edge LineBasic 0.75 alpha.',
    },
  },

  {
    kicker: 'HOW TO READ THIS DECK',
    title: 'Visual grammar and asset vocabulary',
    sub: 'Every symbol, line style and colour is used consistently on all 90+ slides. Learn it once here.',
    scene: 'assetLineup',
    stageTag: 'LEGEND · 3D',
    caption: 'Five physical asset classes and the five link/flow types used throughout.',
    left: [
      { h: 'ASSET CLASSES', items: ['<b>Satellite</b> — LEO/GEO sensing + NTN backhaul', '<b>UAV</b> — aerial sensing + aerial base station', '<b>UGV</b> — ground robot, close-range work', '<b>Ground station</b> — gateway to the terrestrial core', '<b>Edge / GPU</b> — compute wherever latency demands it'] },
    ],
    right: [
      { h: 'LINK & FLOW TYPES', tone: 'ok', items: ['<b>Solid glowing beam</b> — high-rate data link', '<b>Dashed marching line</b> — control / telemetry', '<b>Cyan spine</b> — platform data bus', '<b>Mint arrow</b> — learning / model update', '<b>Violet orb + halo</b> — autonomous AI agent'] },
      { h: 'COLOUR SEMANTICS', tone: 'ai', kv: [['CYAN', 'data & communication'], ['MINT', 'learning & digital twin'], ['VIOLET', 'agentic / generative AI'], ['AMBER', 'human, energy, orchestration'], ['RED', 'failure, safety, risk']] },
    ],
    tech: ['consistent iconography', 'consistent terminology', 'dark aerospace palette', 'one idea per slide'],
    note: 'A viewer should decode any slide in five seconds because the grammar never changes.',
    spec: {
      visual: 'Five hero assets on lit landing pads in a dark hangar grid, each labelled, with a floating legend panel behind.',
      scene3d: 'Assets spaced 12 m apart on a 120 m grid; each on a glowing ring pad (r=2.6–3.1); legend rendered as a canvas-textured plane 4.4 m tall at z=-16.',
      components: ['Satellite (solar panels, dish, optical terminal)', 'Quadcopter (gimbal, LED, antenna)', 'UGV (spinning LiDAR)', 'Ground station dish', 'GPU rack'],
      dataflow: 'None — this is the vocabulary slide. Flow semantics are stated in text and used from the next slide onward.',
      animation: ['Satellite yaws at 0.25 rad/s', 'UAV hovers ±0.35 m', 'UGV LiDAR drum spins at 3 rad/s', 'Camera dollies slowly across the lineup'],
      text: 'Two columns: asset classes and link/flow types + colour semantics.',
      message: 'Consistency is a design requirement, not decoration: it is what makes a 90-slide technical deck readable.',
      production: 'Camera (0,9,40) → (0,4,0). Hemisphere fill 0.7 to keep hardware silhouettes readable against the dark grid.',
    },
  },

  {
    kicker: 'STRUCTURE',
    title: 'Deck map — from problem to autonomous operation',
    sub: 'Eleven acts. The narrative always moves in one direction: why → what → how it is built → how it is proven → how it operates.',
    diagram: {
      type: 'matrix',
      title: 'NARRATIVE STRUCTURE',
      ih: 26,
      cols: [
        { t: 'ACT I–II · WHY', cls: 'warn', items: [{ t: 'The disconnected world' }, { t: '11 domains that break' }, { t: 'Why silos fail' }, { t: 'Global vision: Earth → Edge' }] },
        { t: 'ACT III–IV · WHAT', cls: 'accent', items: [{ t: 'Master architecture, 15 layers' }, { t: 'Four cross-cutting planes' }, { t: 'One slide per layer (L1–L15)' }, { t: 'Inputs · processing · outputs' }] },
        { t: 'ACT V · ARCHITECTURES', cls: 'ai', items: [{ t: 'Simulation stack' }, { t: 'AI stack' }, { t: 'Agentic AI + RAG' }, { t: 'Digital twin + comms' }, { t: 'Federated & multi-agent RL' }] },
        { t: 'ACT VI–VII · BUILD & PROVE', cls: 'ok', items: [{ t: '14 development phases' }, { t: '9-level testing pyramid' }, { t: 'Failure & safety architecture' }, { t: 'MLOps / AIOps / RobotOps' }] },
        { t: 'ACT VIII–XI · OPERATE', items: [{ t: 'Hardware ecosystem' }, { t: 'End-to-end earthquake mission' }, { t: '10 global use cases' }, { t: 'Technology map' }, { t: 'Final master architecture' }] },
      ],
    },
    left: [
      { h: 'READING PATHS', items: ['<b>Investor / agency</b> — acts I, II, IX, X, XI', '<b>CTO / architect</b> — acts III, IV, V, VII', '<b>Researcher</b> — acts V, VI, VII', '<b>Programme manager</b> — acts VI, VII, VIII'] },
      { h: 'IN-DECK TOOLS', tone: 'ok', items: ['<kbd>G</kbd> grid overview', '<kbd>N</kbd> per-slide production spec', '<kbd>P</kbd> freeze animation for print/screenshot'] },
    ],
    note: 'Every slide is specified: VISUAL · 3D SCENE · COMPONENTS · DATA FLOW · ANIMATION · TEXT · TECHNICAL MESSAGE.',
    spec: {
      visual: 'Five-column structural matrix, colour-coded by act family, no 3D needed — this is the map, it must be instantly scannable.',
      components: ['Act columns', 'Slide-group cells', 'Reading paths per audience'],
      animation: ['Static by design. If animated, reveal one column at a time from left to right.'],
      text: 'Reading paths for four audiences.',
      message: 'The deck is engineered as a document with a defined traversal order, not a slide pile.',
    },
  },

  {
    kicker: 'ACT I · THE PROBLEM',
    title: 'When the physical world breaks, the digital world goes blind',
    sub: 'An earthquake, a typhoon, a cable cut or simply distance: within minutes the terrestrial layer that all modern autonomy silently depends on is gone.',
    scene: 'brokenWorld',
    stageTag: 'ZERO-INFRASTRUCTURE ZONE',
    caption: 'Collapsed districts, dead base stations, no backhaul, no map, no situational awareness.',
    left: [
      { h: 'WHAT IS LOST', tone: 'warn', items: ['Cellular access <b>and</b> backhaul', 'Power, therefore edge compute', 'Road access, therefore ground crews', 'Any current map of what just happened'] },
      { h: 'WHAT STILL WORKS', items: ['Orbit — nothing on the ground can break it', 'Air — a corridor nobody has to clear', 'Batteries, GPUs and radios you can fly in'] },
    ],
    right: [
      { h: 'THE OPERATIONAL GAP', tone: 'warn', kv: [['0–2 h', 'no reliable comms, no picture'], ['2–12 h', 'manual recon, partial voice'], ['12–72 h', 'ad-hoc networks, still no fused map'], ['GOAL', 'usable network + live map in minutes']] },
      { h: 'WHY AUTONOMY, NOT MORE PEOPLE', tone: 'ai', text: 'The bottleneck is not willingness — it is <b>simultaneity</b>: hundreds of decisions per minute across kilometres of terrain, under degraded sensing and comms.' },
    ],
    metrics: [['&lt;10 min', 'target time-to-first-link'], ['0', 'assumed ground infrastructure'], ['100%', 'of decisions initially manual today']],
    note: 'The problem is not a missing model. It is a missing infrastructure that can be delivered by air and space and think for itself.',
    spec: {
      visual: 'Night-time disaster city in red/amber: 45% of buildings collapsed or tilted, fires and drifting smoke, three dead towers flashing “NO SERVICE”.',
      scene3d: 'Instanced city, damaged=0.45, emissive roof lights recoloured to ember; 16 fire cones + smoke spheres animated; dark circular “outage” disc r=40 on the ground plane.',
      components: ['Damaged instanced city', 'Fire/smoke particle proxies', 'Dead cell towers with red beacons', 'Status panel: backhaul DOWN / grid PARTIAL / roads BLOCKED'],
      dataflow: 'Deliberately absent. The absence of links is the message of the slide.',
      animation: ['Flames scale-pulse at 5 Hz', 'Smoke drifts vertically', '“NO SERVICE” labels blink out of phase', 'Camera orbits slowly at 0.024 rad/s'],
      text: 'Left: what is lost / what still works. Right: the operational gap in time bands.',
      message: 'Autonomy is required because the failure is simultaneous, wide-area and time-critical.',
      production: 'Warm key light 0xff9d7a at 0.5 intensity, red point light at the city centre, fog 0x0a0608 near 40 / far 150 to bury the horizon.',
    },
  },

  {
    kicker: 'ACT I · SCOPE',
    title: 'Eleven domains, one recurring failure',
    sub: 'Disaster response is the sharpest case, not the only one. Every domain below fails for the same reason: the physical world is bigger than the sensing, comms and decision capacity available on the ground.',
    scene: 'domainTiles',
    stageTag: '11 DOMAINS · ONE PLATFORM',
    caption: 'Each tile is a deployment environment; the core is the same autonomy platform.',
    left: [
      { h: 'THE COMMON PATTERN', items: ['Large area, sparse sensing', 'Intermittent or absent connectivity', 'Decisions needed faster than humans can gather context', 'High cost of being wrong'] },
    ],
    right: [
      { h: 'WHY ONE PLATFORM', tone: 'ok', items: ['Same sensing abstractions', 'Same comms and edge fabric', 'Same digital twin and knowledge layer', 'Only the <b>mission policy</b> and payload change'] },
    ],
    tech: ['disaster', 'remote areas', 'telecom outage', 'agriculture', 'logistics', 'inspection', 'search & rescue', 'industrial', 'smart city', 'maritime', 'space ops'],
    note: 'Reuse across domains is the economic argument: one infrastructure amortised over eleven markets.',
    spec: {
      visual: 'Eleven glowing environment tiles arranged in a ring around a central agent orb labelled “ONE INFRASTRUCTURE”, each tile linked to the core by a beam.',
      scene3d: 'Tiles 7.4 × 7.4 m at radius 22, each with 7 procedural extrusions in the domain colour and a floating octahedron pin; core orb r=2.4 at 5 m.',
      components: ['11 domain tiles', 'Central platform orb', '11 tile→core beams with packets'],
      dataflow: 'Bidirectional: each domain contributes data and consumes autonomy from the same core.',
      animation: ['Pins bob out of phase', 'Beam packets flow inward', 'Camera orbits the ring at 0.035 rad/s'],
      text: 'Left: the common pattern. Right: why one platform serves all eleven.',
      message: 'The platform is domain-agnostic; the mission layer is domain-specific.',
    },
  },

  {
    kicker: 'ACT I · WHY TODAY FAILS',
    title: 'Three separate programmes cannot become one capability',
    sub: 'Space, air and ground autonomy are usually procured, built and operated as independent programmes. The integration cost is then paid forever, at the worst possible moment: during the mission.',
    scene: 'silos',
    diagram: {
      type: 'chain',
      title: 'INTEGRATION COST OF SILOED AUTONOMY',
      bh: 62,
      items: [
        { t: 'Separate data models', s: 'no common world state', cls: 'bad' },
        { t: 'Separate comms', s: 'manual relay design', cls: 'bad', e: '×' },
        { t: 'Separate planners', s: 'no joint task allocation', cls: 'bad', e: '×' },
        { t: 'Separate training', s: 'no shared experience', cls: 'bad', e: '×' },
        { t: 'Human glue', s: 'operators become the integration layer', cls: 'warn', e: '=' },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'SYMPTOMS', tone: 'warn', items: ['“The drone team owns that, the satellite team owns this”', 'Two dashboards that disagree about the same building', 'A model that cannot be deployed because no one can certify it', 'Field data that never reaches training'] },
    ],
    right: [
      { h: 'ROOT CAUSE', tone: 'warn', text: 'No shared representation of the world, of knowledge, or of learning. Every interface is bilateral, so cost grows with the <b>square</b> of the number of programmes.' },
      { h: 'THE FIX', tone: 'ok', text: 'One world model, one knowledge base, one learning loop — enforced by architecture, not by meetings.' },
    ],
    note: 'The architecture in this deck exists specifically to remove the human glue from the critical path.',
    spec: {
      visual: 'Three isolated circular islands (space / drone / robotics programme) with broken red links between them and a red ✕ at each break.',
      scene3d: 'Islands r=7 at x = −20, 0, +20 with a satellite, a UAV and a UGV; broken polylines with a gap in the middle; explanatory panel floating in front.',
      components: ['Three programme islands', 'Broken inter-programme links', '“Failure mode” panel'],
      dataflow: 'Intentionally broken — the gaps are the content.',
      animation: ['Static assets, slow camera orbit', 'Optional: red ✕ pulses on each break'],
      text: 'Symptoms → root cause → the fix, plus a five-stage cost chain below the 3D view.',
      message: 'Siloed autonomy scales quadratically in integration cost and cannot meet mission timelines.',
    },
  },

  {
    kicker: 'ACT I · THE ANSWER',
    title: 'Satellites + UAVs + ground robots + edge as one intelligent infrastructure',
    sub: 'The same three assets, now sharing a world model, a knowledge base, a communication fabric and a learning loop, coordinated by an autonomy layer above all of them.',
    scene: 'integrated',
    stageTag: 'ONE SYSTEM',
    caption: 'NTN feeder · satellite↔UAV · UAV↔robot · edge fabric, all under one autonomy layer.',
    left: [
      { h: 'SHARED BY DESIGN', tone: 'ok', items: ['<b>World model</b> — one geometry, one semantics, one timeline', '<b>Knowledge</b> — maps, regulations, manuals, mission history', '<b>Comms fabric</b> — every asset is a relay candidate', '<b>Learning loop</b> — every asset contributes experience'] },
    ],
    right: [
      { h: 'WHAT BECOMES POSSIBLE', tone: 'ai', items: ['A satellite detection can task a UAV within seconds', 'A UAV can become the base station its robots need', 'A robot’s LiDAR can correct the twin the swarm plans on', 'A failure anywhere is reallocated, not escalated'] },
      { h: 'CONTROL PRINCIPLE', tone: 'warn', text: 'Autonomy is <b>bounded</b>: agents plan and act inside envelopes that humans set and can always retake.' },
    ],
    tech: ['SAGIN', '3GPP NTN', 'ROS 2 DDS', 'MAVLink', 'Zenoh/DDS bridging', 'gRPC', 'Kubernetes at the edge'],
    metrics: [['seconds', 'detection → tasking'], ['3', 'domains under one planner'], ['n+1', 'redundant comms paths']],
    note: 'Integration is achieved by shared representations, not by point-to-point connectors.',
    spec: {
      visual: 'A satellite, a 6-UAV mesh swarm, two ground robots, a gateway and an edge rack, all tied to a violet “shared autonomy layer” orb above the scene.',
      scene3d: 'Sat at (−20,18,−6); swarm at 11 m with 20 m mesh range; robots at (16,0,6) and (21,0,−4); gateway (−18,0,12); rack (4,0,16); orb at (0,24,8).',
      components: ['NTN feeder beam (cyan)', 'Sat↔UAV dashed control link', 'UAV↔robot beam (mint)', 'Edge fabric link (NVIDIA green)', 'Agent orb with dashed links to every asset'],
      dataflow: 'Sensing flows up to the autonomy layer; tasking flows back down to each asset class; peer links carry local coordination.',
      animation: ['Packets flow on all five links', 'Robot LiDAR spins, rotors spin', 'Orb rings counter-rotate', 'Camera orbit 0.03 rad/s'],
      text: 'Left: what is shared. Right: what becomes possible + the bounded-autonomy principle.',
      message: 'Cross-domain autonomy is an architectural property: shared world model, shared knowledge, shared learning.',
    },
  },

  {
    layout: 'full',
    kicker: 'ACT II · GLOBAL VISION',
    title: 'Earth-to-Edge: seven tiers, one vertical information column',
    sub: 'SPACE → LEO → HAPS → UAV SWARM → 6G/NTN ACCESS → GROUND STATIONS → CITIES, IoT, ROBOTS, HUMANS. Data climbs; commands and models descend.',
    scene: 'earthToEdgeStack',
    stageTag: 'EARTH → EDGE · LIVE',
    caption: 'Vertical spine = platform bus (up: observations, down: commands + model updates). Horizontal links = peer coordination inside each tier.',
    tech: ['GEO relay', 'LEO imaging + NTN', 'HAPS', 'UAV aerial base stations', '5G/6G + RIS', 'FSO', 'gateways', 'edge GPU', 'IoT'],
    metrics: [['7', 'tiers'], ['2', 'flow directions'], ['ms → s', 'latency budget by tier'], ['km → 1000s km', 'link range span']],
    note: 'Every later slide is a zoom into one tier or one flow of this single picture.',
    spec: {
      visual: 'Full-bleed vertical stack of seven labelled altitude tiers with real assets on each, pierced by a bright bidirectional spine.',
      scene3d: 'Tier planes at y = 3, 9, 16, 25, 34, 46, 56 with shrinking width to create perspective; satellites at 46–56 m, HAPS 34 m, swarm 25 m, towers/gateway 9 m, city + humans + robot at 3 m.',
      components: ['Tier planes + rings', 'Assets per tier', 'Central spine with up/down packet streams', 'Six cross-tier links alternating beam/dashed'],
      dataflow: 'Up: raw sensing → fused state → global knowledge. Down: mission intent → policies → actuator commands → model weights.',
      animation: ['Satellites translate across their tier', 'Spine packets: cyan up, mint down', 'Swarm re-forms its mesh', 'Camera orbits at 0.028 rad/s with slight bob'],
      text: 'Title, subtitle, tier labels in-scene only. No body text — the picture is the argument.',
      message: 'The platform is a vertical information column: any tier can sense, relay, compute or act, and the column never stops learning.',
      production: 'Camera (30,26,54) → (0,24,0), 48° FOV, fog 80/260. Tier label sprites at x=−26 so they never overlap the assets.',
    },
  },

  {
    kicker: 'ACT II · TARGETS',
    title: 'What “good” means: the platform KPI envelope',
    sub: 'Autonomy claims are only credible with numbers attached. These are the platform-level targets every later architecture decision is judged against.',
    scene: 'kpiWall',
    diagram: {
      type: 'chain',
      title: 'KPI FAMILIES AND OWNERSHIP',
      bh: 66,
      items: [
        { t: 'MISSION', s: 'time-to-first-link · area covered · targets found', cls: 'accent' },
        { t: 'NETWORK', s: 'throughput · coverage · outage · handover', cls: 'accent' },
        { t: 'AUTONOMY', s: 'interventions per hour · decision latency', cls: 'ai' },
        { t: 'SAFETY', s: 'incidents · fallback activations · geofence breaches', cls: 'bad' },
        { t: 'LEARNING', s: 'sim-to-real gap · model regression rate', cls: 'ok' },
        { t: 'ECONOMICS', s: 'cost per covered km² · energy per bit', cls: 'warn' },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'MISSION KPIs', kv: [['&lt;10 min', 'first usable link'], ['&gt;90%', 'priority area covered in 1 h'], ['&lt;2 s', 'detection → task assignment'], ['&gt;95%', 'map freshness &lt; 5 min']] },
      { h: 'NETWORK KPIs', kv: [['&gt;100 Mb/s', 'aggregate user throughput'], ['&lt;50 ms', 'edge inference RTT'], ['&lt;1%', 'link outage in mission window']] },
    ],
    right: [
      { h: 'AUTONOMY & SAFETY KPIs', tone: 'ai', kv: [['&lt;0.1/h', 'human interventions per UAV'], ['100%', 'safety-critical actions monitored'], ['&lt;1 s', 'fault detection → safe policy'], ['0', 'uncommanded geofence exits']] },
      { h: 'LEARNING KPIs', tone: 'ok', kv: [['&lt;15%', 'sim-to-real performance gap'], ['&gt;1', 'policy improvement per mission batch'], ['&lt;24 h', 'field data → retrained candidate']] },
    ],
    metricsLabel: 'HEADLINE TARGETS',
    metrics: [['&lt;10 min', 'time to first link'], ['&lt;0.1/h', 'interventions per UAV'], ['&lt;15%', 'sim-to-real gap'], ['&gt;90%', 'priority coverage']],
    note: 'Each KPI family has an owning layer and an owning agent — they are wired into the orchestration layer, not just reported.',
    spec: {
      visual: 'Four live holographic gauges above a small instrumented city, with a six-family KPI chain below the 3D view.',
      scene3d: 'Canvas-texture gauges (coverage, link uptime, autonomy, energy) at 9 m, redrawn every frame; 70-building city and a 5-UAV mesh below for context.',
      components: ['4 animated gauges', 'Context city + swarm', 'KPI family chain diagram'],
      dataflow: 'Telemetry → aggregation → KPI → orchestration feedback (the gauges are the feedback signal, not decoration).',
      animation: ['Gauge needles oscillate ±5% around target to imply live telemetry', 'Slow camera drift'],
      text: 'Four KPI cards, one headline metric strip.',
      message: 'Autonomy is an engineering claim with measurable acceptance thresholds.',
    },
  },

  {
    layout: 'full',
    kicker: 'ACT III · MASTER ARCHITECTURE',
    title: 'The complete system: 15 layers, sensing up, action down',
    sub: 'L1 physical world · L2 sensing · L3 physical agents · L4 communication · L5 edge · L6 digital twin · L7 data · L8 RAG/knowledge · L9 AI models · L10 agentic AI · L11 physical AI · L12 learning · L13 orchestration · L14 human · L15 deployment.',
    scene: 'masterArchitecture',
    stageTag: 'MASTER ARCHITECTURE · LIVE 3D',
    caption: 'Left spine = SENSE (observations rising). Right spine = ACT (decisions descending). Icons mark the layer where each asset class physically lives.',
    tech: ['ROS 2', 'PX4', 'Isaac Sim', 'Isaac Lab', 'Omniverse', '3GPP NTN', 'RIS', 'Vector DB', 'Knowledge Graph', 'VLM/LLM', 'MARL', 'Federated Learning', 'Kubernetes', 'CUDA'],
    metrics: [['15', 'layers'], ['4', 'cross-cutting planes'], ['2', 'closed loops (control + learning)'], ['1', 'shared world model']],
    note: 'Read it as a loop, not a stack: L15 deployment feeds L1 the physical world, which is sensed again by L2 — the system never leaves the loop.',
    spec: {
      visual: 'Fifteen stacked translucent architecture slabs in deep perspective, two counter-flowing spines, and 3D asset icons anchored to the layers where they live.',
      scene3d: 'Slabs 34 × 15 m spaced 2.5 m; left spine (x=−11) cyan upward, right spine (x=+11) violet downward; icons: city (L1), UAV (L3), satellite (L4), rack (L5), twin city (L6), knowledge graph (L8), agent orb (L10), robot (L11), human (L14).',
      components: ['15 labelled layer slabs', 'SENSE spine', 'ACT spine', '9 anchored asset icons'],
      dataflow: 'L1→L2→…→L11 produces action; L12 learning taps every layer; L13 orchestrates across layers; L14 can intercept at any layer.',
      animation: ['Packets rise on the left spine and fall on the right', 'Knowledge graph and agent orb rotate', 'Camera makes a slow 74 m orbit to reveal depth'],
      text: 'Only layer names in-scene; the subtitle enumerates them for readers of the printed version.',
      message: 'This one picture is the contract for the rest of the deck: every following slide is a zoom into one of these layers.',
      production: 'Camera (46,34,58) → (0,17,0), 46° FOV, fog 90/300. Slab opacity 0.42 so eight layers remain legible through each other.',
    },
  },

  {
    kicker: 'ACT III · CROSS-CUTTING',
    title: 'Four planes cut through every layer',
    sub: 'A layered diagram alone is a lie: the interesting failures are vertical. Data, control, learning and safety are separate planes with separate guarantees, and each crosses all fifteen layers.',
    scene: 'crossPlanes',
    diagram: {
      type: 'graph',
      title: 'PLANE RESPONSIBILITIES AND GUARANTEES',
      h: 300,
      groups: [
        { t: 'DATA PLANE', x: 14, y: 34, w: 232, h: 250 },
        { t: 'CONTROL PLANE', x: 258, y: 34, w: 232, h: 250 },
        { t: 'LEARNING PLANE', x: 502, y: 34, w: 232, h: 250 },
        { t: 'SAFETY PLANE', x: 746, y: 34, w: 240, h: 250 },
      ],
      nodes: [
        { id: 'd1', x: 28, y: 62, w: 204, h: 44, t: 'Sensor & telemetry transport', s: 'best-effort, high volume', cls: 'accent' },
        { id: 'd2', x: 28, y: 118, w: 204, h: 44, t: 'Feature & state store', s: 'append-only, replayable' },
        { id: 'd3', x: 28, y: 174, w: 204, h: 44, t: 'World state service', s: 'single source of geometry' },
        { id: 'd4', x: 28, y: 230, w: 204, h: 40, t: 'Guarantee: lineage', s: 'every value traceable to a sensor', cls: 'ghost' },
        { id: 'c1', x: 272, y: 62, w: 204, h: 44, t: 'Mission & task commands', s: 'authenticated, ordered', cls: 'warn' },
        { id: 'c2', x: 272, y: 118, w: 204, h: 44, t: 'Policy selection', s: 'which controller is live' },
        { id: 'c3', x: 272, y: 174, w: 204, h: 44, t: 'Actuator setpoints', s: 'hard real-time on-board' },
        { id: 'c4', x: 272, y: 230, w: 204, h: 40, t: 'Guarantee: determinism', s: 'bounded latency, no reordering', cls: 'ghost' },
        { id: 'l1', x: 516, y: 62, w: 204, h: 44, t: 'Experience collection', s: 'trajectories, rewards, labels', cls: 'ai' },
        { id: 'l2', x: 516, y: 118, w: 204, h: 44, t: 'Training & aggregation', s: 'central, federated, MARL', cls: 'ai' },
        { id: 'l3', x: 516, y: 174, w: 204, h: 44, t: 'Model registry & rollout', s: 'versioned, signed, revertible', cls: 'ai' },
        { id: 'l4', x: 516, y: 230, w: 204, h: 40, t: 'Guarantee: reproducibility', s: 'data + code + seed pinned', cls: 'ghost' },
        { id: 's1', x: 760, y: 62, w: 212, h: 44, t: 'Independent monitors', s: 'no shared failure mode with AI', cls: 'bad' },
        { id: 's2', x: 760, y: 118, w: 212, h: 44, t: 'Envelopes & geofences', s: 'checked outside the policy', cls: 'bad' },
        { id: 's3', x: 760, y: 174, w: 212, h: 44, t: 'Fallback controllers', s: 'classical, certifiable', cls: 'bad' },
        { id: 's4', x: 760, y: 230, w: 212, h: 40, t: 'Guarantee: last word', s: 'safety can always override AI', cls: 'ghost' },
      ],
      edges: [
        { a: 'd1', b: 'd2' }, { a: 'd2', b: 'd3' }, { a: 'c1', b: 'c2', cls: '' }, { a: 'c2', b: 'c3' },
        { a: 'l1', b: 'l2', cls: 'ai' }, { a: 'l2', b: 'l3', cls: 'ai' },
        { a: 's1', b: 's2', cls: 'bad' }, { a: 's2', b: 's3', cls: 'bad' },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'WHY SEPARATE THEM', items: ['Different latency classes (ms vs minutes)', 'Different failure semantics (drop vs never drop)', 'Different certification paths', 'Different owners in the organisation'] },
    ],
    right: [
      { h: 'THE ONE HARD RULE', tone: 'warn', text: 'The safety plane must not share components, clocks or power domains with the learning plane. If the AI is wrong, the thing that stops it must not be wrong for the same reason.' },
    ],
    note: 'Layers describe structure; planes describe guarantees. Both are needed before any code is written.',
    spec: {
      visual: 'Eight faint layer slabs pierced vertically by four coloured translucent planes, each labelled with its function.',
      scene3d: 'Planes 13 × 25 m rotated 90° about Y at x = −9, −3, +3, +9; each with its own spine of packets rising at 0.16 speed.',
      components: ['Layer slabs (context)', 'Data / control / learning / safety planes', 'Per-plane packet spines'],
      dataflow: 'Each plane carries a different traffic class through the same physical assets.',
      animation: ['Packets rise in each plane at different rates', 'Camera orbits to show the planes cutting the stack'],
      text: 'Why separate them + the one hard rule; the diagram states each plane’s guarantee.',
      message: 'Separation of planes — especially safety from learning — is what makes autonomous physical AI certifiable.',
    },
  },
];
