export const OPS = [
  {
    kicker: 'ACT VII · VALIDATION',
    title: 'The testing pyramid: nine levels before anything matters',
    sub: 'Cheap tests run constantly; expensive tests run rarely; nothing flies over people until level 8. The pyramid is an economic argument as much as a safety one.',
    scene: 'testPyramid',
    stageTag: 'VALIDATION PYRAMID',
    caption: 'Level 1 software unit tests → level 9 operational deployment, with cost of failure rising and test count falling.',
    diagram: {
      type: 'pyramid',
      title: 'NINE VALIDATION LEVELS',
      maxW: 700,
      minW: 240,
      items: [
        { t: 'L1  SOFTWARE UNIT TESTS', l: 'seconds', r: 'thousands per commit · CI gate', cls: 'accent' },
        { t: 'L2  AI MODEL TESTS', l: 'minutes', r: 'accuracy · calibration · OOD · bias', cls: 'accent' },
        { t: 'L3  SIMULATION', l: 'minutes', r: 'nominal end-to-end missions', cls: 'ok' },
        { t: 'L4  MASSIVE SIMULATION', l: 'hours', r: '10⁴–10⁶ randomised missions', cls: 'ok' },
        { t: 'L5  SCENARIO RANDOMISATION', l: 'hours', r: 'adversarial + rare events + tails', cls: 'ai' },
        { t: 'L6  HARDWARE-IN-THE-LOOP', l: 'days', r: 'real firmware, real timing', cls: 'warn' },
        { t: 'L7  CONTROLLED FIELD TEST', l: 'days', r: 'one aircraft, bounded volume', cls: 'warn' },
        { t: 'L8  PILOT DEPLOYMENT', l: 'weeks', r: 'real users, full monitoring', cls: 'bad' },
        { t: 'L9  OPERATIONAL DEPLOYMENT', l: 'continuous', r: 'continuous assurance + canaries', cls: 'bad' },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'WHY NOT TEST IN THE REAL WORLD FIRST', tone: 'warn', items: ['A real failure can injure someone — a simulated one cannot', 'A real flight costs hours; a simulated mission costs seconds', 'Real conditions are not repeatable, so you cannot debug them', 'Rare events are, by definition, almost never in your flight log'] },
    ],
    right: [
      { h: 'GATE RULE', tone: 'ok', text: 'A level is only passed with <b>evidence</b>: recorded runs, metrics against thresholds, and reproducible seeds for every failure found.' },
      { h: 'WHAT MOVES UPWARD', items: ['Only artefacts that passed the level below', 'Plus the scenarios that broke them, as permanent regression tests'] },
    ],
    tech: ['CI/CD', 'pytest / gtest', 'model test harness', 'Isaac Lab batch runs', 'scenario DSL', 'PX4 HITL', 'flight-test procedures', 'canary rollout'],
    metrics: [['9', 'levels'], ['10⁶', 'simulated missions before flight'], ['100%', 'failures kept as regressions'], ['L8', 'first flight over people']],
    note: 'Autonomous AI must not be debugged in the real world. The pyramid exists so that reality is the confirmation, not the experiment.',
    spec: {
      visual: 'A nine-tier 3D pyramid with a UAV hovering above the apex, cost-of-failure rising on the left and test-count falling on the right.',
      scene3d: 'Boxes 30 → 6.8 m wide, 1.7 m tall, spaced 2.1 m; per-level description labels to the right; cyan spine on the left annotated with the two gradients.',
      components: ['9 pyramid tiers', 'Per-tier description', 'Cost/count gradient annotations', 'UAV at the apex'],
      dataflow: 'Artefacts and regression scenarios move upward only after passing each level.',
      animation: ['Spine packets rise', 'Apex UAV hovers', 'Slow orbit to show the taper'],
      text: 'Why not the real world first, the gate rule, and what moves upward.',
      message: 'Validation is a staged, evidence-based economic process — reality is the last step, not the first.',
    },
  },

  {
    kicker: 'ACT VII · SAFETY',
    title: 'Failure architecture: ten failures, one response chain',
    sub: 'Every credible failure is enumerated, detected by a monitor that is independent of the AI, and handled by a chain that ends — if necessary — with a human.',
    scene: 'safetyArch',
    stageTag: 'SAFETY PLANE',
    caption: 'Ten failure sources converging on the vehicle, and the six-stage response chain in front of it.',
    diagram: {
      type: 'graph',
      title: 'DETECTION → RESPONSE → EVIDENCE',
      h: 300,
      nodes: [
        { id: 'f1', x: 20, y: 44, w: 158, h: 40, t: 'GPS unavailable', cls: 'bad' },
        { id: 'f2', x: 20, y: 92, w: 158, h: 40, t: 'Communication lost', cls: 'bad' },
        { id: 'f3', x: 20, y: 140, w: 158, h: 40, t: 'Sensor failure', cls: 'bad' },
        { id: 'f4', x: 20, y: 188, w: 158, h: 40, t: 'Battery degradation', cls: 'bad' },
        { id: 'f5', x: 20, y: 236, w: 158, h: 40, t: 'Collision risk', cls: 'bad' },
        { id: 'f6', x: 198, y: 44, w: 158, h: 40, t: 'Weather deterioration', cls: 'bad' },
        { id: 'f7', x: 198, y: 92, w: 158, h: 40, t: 'Model uncertainty / OOD', cls: 'bad' },
        { id: 'f8', x: 198, y: 140, w: 158, h: 40, t: 'Cyber attack', cls: 'bad' },
        { id: 'f9', x: 198, y: 188, w: 158, h: 40, t: 'Satellite outage', cls: 'bad' },
        { id: 'f10', x: 198, y: 236, w: 158, h: 40, t: 'UAV failure', cls: 'bad' },
        { id: 'd', x: 400, y: 44, w: 160, h: 44, t: 'DETECTION', s: 'independent monitors', cls: 'ok' },
        { id: 'a', x: 400, y: 102, w: 160, h: 44, t: 'ASSESSMENT', s: 'severity + time to act', cls: 'ok' },
        { id: 'sp', x: 400, y: 160, w: 160, h: 44, t: 'SAFE POLICY', s: 'classical fallback', cls: 'ok' },
        { id: 'rd', x: 400, y: 218, w: 160, h: 44, t: 'REDUNDANCY', s: 'alternate asset / path', cls: 'ok' },
        { id: 'rc', x: 596, y: 102, w: 160, h: 44, t: 'RECOVERY', s: 'RTH · land · re-route', cls: 'warn' },
        { id: 'hu', x: 596, y: 160, w: 160, h: 44, t: 'HUMAN ESCALATION', s: 'override authority', cls: 'warn' },
        { id: 'ev', x: 792, y: 130, w: 186, h: 44, t: 'EVIDENCE RECORD', s: 'for certification + learning', cls: 'ai' },
        { id: 'mech', x: 596, y: 224, w: 382, h: 52, t: 'Mechanisms: safety agent · fallback controller · emergency landing · return-to-home · geofencing · redundant comms · human override', cls: 'ghost' },
      ],
      edges: [
        { a: 'f1', b: 'd', cls: 'bad' }, { a: 'f5', b: 'd', cls: 'bad' }, { a: 'f7', b: 'd', cls: 'bad' }, { a: 'f10', b: 'd', cls: 'bad' },
        { a: 'd', b: 'a', cls: 'ok' }, { a: 'a', b: 'sp', cls: 'ok' }, { a: 'sp', b: 'rd', cls: 'ok' },
        { a: 'a', b: 'rc', cls: 'warn' }, { a: 'rc', b: 'hu', cls: 'warn' }, { a: 'hu', b: 'ev', cls: 'ai' }, { a: 'rd', b: 'ev', cls: 'ai' },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'INDEPENDENCE REQUIREMENT', tone: 'warn', items: ['Monitors do not share models with the policy', 'Envelope checks run outside the learned stack', 'Fallback controllers are classical and certifiable', 'Separate power and clock domains where feasible'] },
    ],
    right: [
      { h: 'MECHANISMS', tone: 'ok', items: ['Safety agent with veto authority', 'Fallback controller (MPC / PID)', 'Emergency landing site selection', 'Return-to-home with energy reserve', 'Geofencing enforced below the policy', 'Redundant communication paths', 'Human override from any mode'] },
    ],
    tech: ['independent monitors', 'runtime assurance (simplex)', 'geofence enforcement', 'anomaly / OOD detection', 'secure boot + attestation', 'redundant links'],
    metrics: [['&lt;1 s', 'detect → safe policy'], ['10', 'enumerated failure families'], ['100%', 'events with evidence records'], ['0', 'AI-only safety decisions']],
    note: 'If the AI is wrong, the thing that stops it must not be wrong for the same reason. That single sentence drives this entire slide.',
    spec: {
      visual: 'A UAV inside a mint protective shield, encircled by ten pulsing red failure nodes, with a six-stage green response chain laid out in front.',
      scene3d: 'UAV at 12 m inside a 5.4 m shield sphere; ten failure octahedra on an ellipse (r=17 × 9) with dashed links inward; six response boxes at z=12 with arrows between them.',
      components: ['Protected vehicle', '10 failure nodes', '6-stage response chain', 'Escalation path'],
      dataflow: 'Failures converge on the vehicle; the response chain runs left to right and ends in human escalation and an evidence record.',
      animation: ['Failure nodes pulse asynchronously', 'Dashed fault links march inward', 'Response chain arrows are steady — deliberately calm'],
      text: 'Independence requirement and the seven concrete mechanisms.',
      message: 'Safety is an independent plane with its own mechanisms, guarantees and evidence trail.',
    },
  },

  {
    kicker: 'ACT VII · DEGRADATION',
    title: 'Four modes, one-way transitions',
    sub: 'Autonomy does not fail — it degrades. NOMINAL → DEGRADED → SAFE → EMERGENCY, each with its own controller, its own envelope and its own monitor.',
    scene: 'safetyLadder',
    stageTag: 'DEGRADATION LADDER',
    caption: 'Same aircraft, four operating modes, decreasing altitude and authority from left to right.',
    diagram: {
      type: 'chain',
      title: 'MODE DEFINITIONS AND TRIGGERS',
      bh: 76,
      items: [
        { t: 'NOMINAL', s: 'learned policy · full envelope · full autonomy', cls: 'ok' },
        { t: 'DEGRADED', s: 'reduced envelope · simpler policy · higher margins', cls: 'warn', e: 'trigger' },
        { t: 'SAFE', s: 'classical fallback controller · minimal mission', cls: 'warn', e: 'trigger' },
        { t: 'EMERGENCY', s: 'return-to-home or immediate controlled landing', cls: 'bad', e: 'trigger' },
      ],
      note: 'Transitions down are automatic and immediate; transitions up require a clean state, a stabilisation timer and (for NOMINAL) an explicit release.',
    },
    left: [
      { h: 'TRIGGER EXAMPLES', items: ['NOMINAL → DEGRADED: link margin low, one sensor lost, model uncertainty high', 'DEGRADED → SAFE: GPS denied, second sensor lost, controller disagreement', 'SAFE → EMERGENCY: energy reserve breached, geofence proximity, airframe fault'] },
    ],
    right: [
      { h: 'PROPERTIES', tone: 'ok', items: ['Each mode is independently testable', 'Each mode has a monitor that can force the next mode down', 'Human override is reachable from every mode', 'Mode history is part of the mission record'] },
      { h: 'ANTI-PATTERN', tone: 'warn', text: 'A single “autonomy on/off” switch. Binary autonomy produces binary outcomes.' },
    ],
    tech: ['runtime assurance / simplex architecture', 'MPC and PID fallbacks', 'energy reserve policy', 'independent mode monitors'],
    metrics: [['4', 'operating modes'], ['&lt;1 s', 'downward transition'], ['timer + clean state', 'upward transition'], ['100%', 'mode changes logged']],
    note: 'Graceful degradation is what makes autonomy operationally acceptable: the worst case is a boring, predictable landing.',
    spec: {
      visual: 'Four lit pads in a row, each with the same UAV at a lower altitude and a different trim colour, with red trigger arrows between them; the last one is descending inside an emergency beacon cone.',
      scene3d: 'Pads at x = −21, −7, +7, +21; UAV altitudes 12, 9, 6, ~1–2.4 m; emergency UAV descends repeatedly inside a red cone; trigger arrows between pads.',
      components: ['4 mode pads', '4 UAV states', 'Trigger arrows', 'Ladder panel'],
      dataflow: 'One-way downward transitions; upward requires conditions stated in the panel.',
      animation: ['Left three UAVs hover at different frequencies; the right one repeatedly descends and lands', 'Trigger arrows steady'],
      text: 'Triggers, properties, and the binary-autonomy anti-pattern.',
      message: 'Design the degraded modes first; they are what the system will actually spend its bad days in.',
    },
  },

  {
    kicker: 'ACT VII · MLOps / AIOps / ROBOTOPS',
    title: 'The operational pipeline for models that fly',
    sub: 'DATA → TRAIN → VALIDATE → REGISTER → SIMULATE → CERTIFY → DEPLOY → MONITOR → COLLECT → RETRAIN, with versioning, canaries and rollback as first-class features.',
    scene: 'mlopsLoop',
    stageTag: 'MLOps LOOP',
    caption: 'Ten-station operational loop with the model registry above it and a sub-minute rollback path.',
    diagram: {
      type: 'loop',
      title: 'MODEL LIFECYCLE WITH GATES',
      h: 320,
      ellipse: 1.62,
      center: 'EVERY STEP',
      centerSub: 'versioned + reproducible',
      items: [
        { t: 'DATA', s: 'versioned datasets', cls: 'accent' },
        { t: 'TRAIN', s: 'pinned code + seed', cls: 'accent' },
        { t: 'VALIDATE', s: 'offline metrics + calibration', cls: 'ok' },
        { t: 'REGISTER', s: 'signed artefact + model card', cls: 'ok' },
        { t: 'SIMULATE', s: 'P7 regression suite', cls: 'ai' },
        { t: 'CERTIFY', s: 'safety evidence package', cls: 'warn' },
        { t: 'DEPLOY', s: 'canary → staged fleet', cls: 'warn' },
        { t: 'MONITOR', s: 'KPI + drift + fleet health', cls: 'bad' },
        { t: 'COLLECT', s: 'hard cases first', cls: 'accent' },
        { t: 'RETRAIN', s: 'candidate for the next round', cls: 'accent' },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'NON-NEGOTIABLES', items: ['No manual copies of weights, ever', 'Every deployed model is signed and traceable to data + code + seed', 'Certification artefacts stored <b>with</b> the model', 'Fleet health tracked per model version'] },
    ],
    right: [
      { h: 'ROLLBACK', tone: 'warn', kv: [['trigger', 'KPI regression, safety event, drift alarm'], ['scope', 'per asset, per region, or fleet-wide'], ['time', '&lt; 60 s to previous version'], ['evidence', 'automatic incident record']] },
      { h: 'WHAT IS DIFFERENT FROM WEB MLOps', tone: 'ai', text: 'A bad rollout here has mass and velocity. Canaries are physical assets, so the blast radius is bounded by geography and mission role, not by traffic percentage alone.' },
    ],
    tech: ['MLflow / W&B', 'model registry + signing', 'DVC / LakeFS', 'Argo / GitOps', 'OTA update', 'drift detection', 'OpenTelemetry'],
    metrics: [['&lt;60 s', 'rollback'], ['100%', 'signed artefacts'], ['canary-first', 'every deploy'], ['per-version', 'fleet health tracking']],
    note: 'RobotOps is MLOps with a physical blast radius. Everything is the same except the consequences, which changes every default.',
    spec: {
      visual: 'A ten-station operational ring with a model-registry row of version cubes above it and a red rollback arrow cutting back through the versions.',
      scene3d: 'Stations on an ellipse (r=19 × 10.5) at y=6; four version cubes at y=15 with the live one glowing mint; red rollback arrow above the cubes.',
      components: ['10 lifecycle stations', 'Version cubes v12.4 → v14.2', 'Rollback arrow', 'Rules panel'],
      dataflow: 'Clockwise lifecycle; registry above; rollback jumps backwards through versions.',
      animation: ['Packets circulate the ring', 'Live version cube rotates faster than the archived ones', 'Rollback arrow pulses'],
      text: 'Non-negotiables, rollback contract, and how this differs from web MLOps.',
      message: 'Model operations for physical systems require signing, canaries and instant rollback as defaults.',
    },
  },

  {
    kicker: 'ACT VII · OPERATIONS',
    title: 'Fleet health and model rollout, on one wall',
    sub: 'Thirty-two assets, three health states, two model versions in flight. The operations question is never “is the model good?” but “which assets are running which model, and how are they doing?”.',
    scene: 'fleetWall',
    stageTag: 'FLEET OPS WALL',
    caption: 'Per-asset state and model version, with four aggregate gauges below.',
    left: [
      { h: 'PER-ASSET STATE', items: ['NOMINAL / DEGRADED / FAULT', 'Model version currently running', 'Energy and mission assignment', 'Open faults and their age'] },
    ],
    right: [
      { h: 'AGGREGATES', tone: 'ok', kv: [['availability', 'share of assets mission-capable'], ['adoption', 'share on the newest certified model'], ['open faults', 'count and trend'], ['energy reserve', 'fleet-wide margin']] },
      { h: 'ESCALATION', tone: 'warn', text: 'Fault clusters that correlate with a model version trigger an automatic rollback proposal, not a discussion.' },
    ],
    tech: ['observability stack', 'time-series KPIs', 'per-version cohort analysis', 'automated rollback proposals'],
    metrics: [['32', 'assets shown'], ['&gt;99%', 'availability target'], ['2', 'model versions in flight'], ['auto', 'rollback proposal']],
    note: 'Operating an autonomous fleet is a cohort-analysis problem: assets, versions, environments and outcomes, correlated continuously.',
    spec: {
      visual: 'A wall of 32 status tiles (mint/amber/red) each labelled with asset ID, state and model version, above four aggregate gauges.',
      scene3d: '4 × 8 tile grid of 2.9 × 2.2 m planes with edge outlines and three text rows each; four canvas gauges at y=3.4.',
      components: ['32 asset tiles', '4 aggregate gauges'],
      dataflow: 'Telemetry → per-asset state → aggregate KPIs → rollback proposals.',
      animation: ['Tile glow breathes per asset to imply live telemetry', 'Gauges oscillate slightly'],
      text: 'Per-asset state, aggregates, and the automatic escalation rule.',
      message: 'Fleet operations is where model quality becomes an operational fact, per asset and per version.',
    },
  },

  {
    kicker: 'ACT VIII · HARDWARE',
    title: 'The hardware ecosystem, and what each part owes the system',
    sub: 'UAV, ground robot, satellite, ground station, edge server and cloud cluster — one exploded view showing the subsystems that actually determine what the autonomy can promise.',
    scene: 'hardwareEcosystem',
    stageTag: 'HARDWARE ECOSYSTEM',
    caption: 'UAV subsystems called out; robot, satellite, gateway, edge and cloud linked by their real data paths.',
    diagram: {
      type: 'matrix',
      title: 'SUBSYSTEM RESPONSIBILITIES',
      ih: 26,
      cols: [
        { t: 'UAV', cls: 'accent', items: [{ t: 'flight controller (PX4)' }, { t: 'GPU/SoC (Orin-class)' }, { t: 'camera + gimbal' }, { t: 'LiDAR / radar' }, { t: 'IMU + GNSS-RTK' }, { t: '5G modem + mesh radio' }] },
        { t: 'GROUND ROBOT', cls: 'ok', items: [{ t: 'drive + suspension' }, { t: '360° LiDAR' }, { t: 'manipulator (optional)' }, { t: 'edge GPU' }, { t: 'long-endurance battery' }] },
        { t: 'SATELLITE', cls: 'accent', items: [{ t: 'imaging payload' }, { t: 'SAR (optional)' }, { t: 'Ka/Ku radios' }, { t: 'optical terminal' }, { t: 'power + ADCS' }] },
        { t: 'GROUND STATION', cls: 'warn', items: [{ t: 'tracking antenna' }, { t: 'modem + gateway' }, { t: 'timing reference' }, { t: 'core network uplink' }] },
        { t: 'EDGE / CLOUD', cls: 'ai', items: [{ t: 'edge GPU servers' }, { t: 'training cluster' }, { t: 'object storage' }, { t: 'model registry' }, { t: 'Kubernetes control plane' }] },
      ],
    },
    diagramLead: true,
    left: [
      { h: 'SELECTION DRIVERS', items: ['Compute per watt (endurance is the real constraint)', 'Sensor synchronisation capability', 'Radio flexibility (mesh + cellular + NTN)', 'Serviceability and spare availability', 'Certification history of the airframe'] },
    ],
    right: [
      { h: 'WHAT HARDWARE PROMISES THE SOFTWARE', tone: 'ok', items: ['A time base good to &lt; 1 ms', 'A pose good to &lt; 5 cm (RTK) or a documented degradation', 'A power budget the inference stack must live inside', 'A guaranteed independent path for safety commands'] },
    ],
    tech: ['PX4 / ArduPilot', 'Jetson Orin / AGX', 'Ouster / Velodyne', 'mmWave radar', 'RTK GNSS', '5G modules', 'Kubernetes', 'NVIDIA GPUs'],
    metrics: [['100–275 TOPS', 'onboard AI compute'], ['&lt;15 W', 'inference power budget'], ['&lt;1 ms', 'time sync'], ['&lt;5 cm', 'RTK pose']],
    note: 'Hardware is where autonomy claims meet physics: endurance, power and time synchronisation set the ceiling for everything above.',
    spec: {
      visual: 'A wide hangar-style layout with a large UAV on the left annotated with six callout lines, and robot, satellite, gateway, edge rack and cloud pod arrayed to the right.',
      scene3d: 'UAV at scale 3.2 with six leader lines to labels; UGV, satellite, ground station, edge rack, 2 × 3 cloud pod; five links between them in different styles.',
      components: ['Annotated UAV', 'UGV', 'Satellite', 'Ground station', 'Edge rack', 'Cloud pod', 'Inter-asset links'],
      dataflow: 'UAV → gateway → edge → cloud, plus robot → UAV and satellite → gateway.',
      animation: ['Rotors, LiDAR and satellite yaw', 'Packets on all five links', 'Slow orbit'],
      text: 'Selection drivers and the four hardware guarantees the software depends on.',
      message: 'Autonomy budgets are hardware budgets: watts, milliseconds and centimetres.',
    },
  },

  {
    kicker: 'ACT VIII · COMPUTE PLACEMENT',
    title: 'Where computation happens: onboard, edge, cloud, satellite',
    sub: 'Four altitude bands, four latency classes, four different jobs. The placement is derived from the control loop, not from where capacity happens to be cheap.',
    scene: 'computeBands',
    stageTag: 'COMPUTE PLACEMENT',
    caption: 'Satellite · UAV/onboard · edge · cloud, each with its capacity bar and its assigned workloads.',
    diagram: {
      type: 'chain',
      title: 'WORKLOAD PLACEMENT AND WHY',
      bh: 82,
      items: [
        { t: 'ONBOARD', s: 'perception · control · local planning — 1–20 ms · must survive link loss', cls: 'ok' },
        { t: 'EDGE', s: 'multi-agent fusion · twin slice · RAG cache — 10–50 ms · shared context', cls: 'accent' },
        { t: 'CLOUD', s: 'training · massive simulation · LLM reasoning — 0.2–2 s · elastic scale', cls: 'ai' },
        { t: 'SATELLITE', s: 'onboard triage · change detection · store-and-forward — power-limited', cls: 'warn' },
      ],
      note: 'Rule: if losing the link would break the loop, the loop runs on the vehicle. Everything else is an optimisation.',
    },
    diagramLead: true,
    left: [
      { h: 'DECISION INPUTS', items: ['Loop deadline (hard vs soft)', 'Data volume vs available bandwidth', 'Power and thermal budget', 'Privacy and data-residency constraints', 'Failure behaviour when the tier is unreachable'] },
    ],
    right: [
      { h: 'CONSEQUENCES', tone: 'ok', items: ['Onboard: quantised models, fixed memory, no surprises', 'Edge: shared state, must be replicated per region', 'Cloud: unlimited scale, never in a control loop', 'Satellite: compute is a power decision first'] },
    ],
    tech: ['TensorRT / INT8', 'Triton', 'KubeEdge / K3s', 'GPU clusters', 'store-and-forward protocols', 'data residency policy'],
    metrics: [['1–20 ms', 'onboard'], ['10–50 ms', 'edge'], ['0.2–2 s', 'cloud'], ['200–700 ms', 'via satellite']],
    note: 'Compute placement is a safety architecture decision disguised as an infrastructure decision.',
    spec: {
      visual: 'Four stacked translucent altitude bands with ring outlines, each labelled with its tier, a capacity bar and its three assigned workloads, pierced by a bidirectional spine.',
      scene3d: 'Bands at y = 30 (satellite), 20 (UAV), 9 (edge), 2 (cloud); 44 × 16 m planes with r=19 rings; capacity bars scaled 0.25–1.0; central spine with up/down packets.',
      components: ['4 bands', 'Capacity bars', 'Workload labels', 'Bidirectional spine'],
      dataflow: 'Requests and data move up and down the spine; each band answers only what its latency class allows.',
      animation: ['Spine packets travel both ways', 'Bands glow at intensities proportional to capacity'],
      text: 'Decision inputs and the consequences of each placement.',
      message: 'Latency and link-loss behaviour decide placement; cost is a secondary consideration.',
    },
  },
];
