const P = (n, title, o) => ({
  kicker: `PHASE ${n} / 13`,
  title,
  badge: `P${n}`,
  ...o,
});

export const PIPELINE = [
  {
    layout: 'full',
    kicker: 'ACT VI · DEVELOPMENT PIPELINE',
    title: 'Fourteen phases, and the loop that never ends',
    sub: 'P0 requirements → P1 design → P2 data → P3 digital twin → P4 AI models → P5 agentic AI → P6 multi-agent learning → P7 simulation → P8 safety validation → P9 hardware-in-the-loop → P10 field test → P11 pilot → P12 continual learning → P13 autonomous operation.',
    scene: 'pipelineOverview',
    stageTag: 'PIPELINE HELIX',
    caption: 'The ascending helix is the build path; the mint return path is field data flowing back into P2, which is what makes this a platform rather than a project.',
    tech: ['requirements traceability', 'interface contracts', 'data versioning', 'twin validation', 'RL training', 'fault injection', 'HITL rigs', 'flight test', 'canary rollout'],
    metrics: [['14', 'phases'], ['1', 'return loop'], ['9', 'validation levels inside P7–P11'], ['&lt;24 h', 'field data → candidate model']],
    note: 'Phases are gated: each one has entry criteria, exit criteria and artefacts. Nothing advances because a demo looked good.',
    spec: {
      visual: 'A rising helix of fourteen labelled phase discs with a bright forward path and a separate mint return path arcing from the top back to the data phase.',
      scene3d: 'Discs on a 2.1-turn helix (radius 22 × 12, height 3 → 25); Catmull-Rom tube for the forward path with 14 packets; second tube for the P13 → P2 return.',
      components: ['14 phase discs', 'Forward path', 'Return path', 'Phase labels'],
      dataflow: 'Forward: artefacts. Backward: field experience and measured gaps.',
      animation: ['Packets travel the helix continuously', 'Return-path packets travel faster to imply the tight learning loop'],
      text: 'Title and phase enumeration only.',
      message: 'Development is a gated, cyclic pipeline whose last phase feeds its third.',
    },
  },

  P(0, 'Requirements — write down what “done” means', {
    sub: 'Mission definition, constraints, success criteria and explicit non-goals. Everything in the following thirteen phases must trace back to a line written here.',
    scene: 'p0Requirements',
    stageTag: 'P0 · REQUIREMENTS',
    caption: 'Four cards: mission, constraints, success criteria, non-goals.',
    left: [
      { h: 'ACTIVITIES', items: ['Mission and stakeholder definition', 'Operational environment description', 'Regulatory and airspace constraints', 'Explicit non-goals and out-of-scope risks'] },
      { h: 'ENTRY CRITERIA', items: ['A named operator and a named use case', 'Access to the target environment’s data'] },
    ],
    right: [
      { h: 'ARTEFACTS', tone: 'ok', items: ['Mission specification with measurable success criteria', 'Constraint register (physical, legal, ethical)', 'KPI definitions and acceptance thresholds', 'Requirements traceability matrix'] },
      { h: 'EXIT CRITERIA', tone: 'warn', text: 'Every KPI has a number, an owner and a test method. If a criterion cannot be measured, it is rewritten or removed.' },
    ],
    tech: ['requirements management', 'CONOPS documents', 'airspace / NOTAM analysis', 'stakeholder workshops'],
    metrics: [['100%', 'requirements measurable'], ['0', 'unowned KPIs']],
    note: 'The most expensive autonomy failures are specification failures discovered after hardware exists.',
    spec: {
      visual: 'Four floating requirement cards over empty terrain — deliberately quiet, no hardware yet.',
      scene3d: 'Bare 120 m terrain; four canvas panels arranged 2 × 2 at y = 5–12; non-goals card outlined in red.',
      components: ['Mission card', 'Constraints card', 'Success-criteria card', 'Non-goals card'],
      dataflow: 'None — this phase produces text, and that is the point.',
      animation: ['Very slow camera drift only; the stillness contrasts with later phases'],
      text: 'Activities, entry criteria, artefacts, exit criteria.',
      message: 'Autonomy programmes are won or lost in the requirements phase.',
    },
  }),

  P(1, 'System design — interfaces before implementations', {
    sub: 'Define the fifteen layers, the four planes, and every contract between them: message schema, rate, latency class and failure semantics.',
    scene: 'p1SystemDesign',
    stageTag: 'P1 · SYSTEM DESIGN',
    caption: 'Nine subsystem blocks with eleven versioned interface contracts between them.',
    left: [
      { h: 'ACTIVITIES', items: ['Layer and plane decomposition', 'Interface contract definition', 'Latency and bandwidth budgeting', 'Failure mode and effects analysis (FMEA)', 'Safety concept and authority model'] },
    ],
    right: [
      { h: 'ARTEFACTS', tone: 'ok', items: ['Architecture description with 15 layers + 4 planes', 'Interface catalogue (schema, rate, latency, failure)', 'Compute placement decisions per function', 'Preliminary safety case outline'] },
      { h: 'EXIT CRITERIA', tone: 'warn', text: 'Two teams can build either side of every interface without talking to each other. If they cannot, the contract is incomplete.' },
    ],
    tech: ['ROS 2 IDL', 'protobuf / JSON schema', 'ArchiMate / C4 diagrams', 'FMEA', 'latency budgeting'],
    metrics: [['11+', 'contracts specified'], ['100%', 'interfaces with failure semantics'], ['4', 'planes with separate guarantees']],
    note: 'The interface catalogue is the real deliverable of this phase; the block diagram is just its cover page.',
    spec: {
      visual: 'A wireframe blueprint of the platform: nine translucent subsystem boxes in three tiers, linked by animated contract edges.',
      scene3d: 'Boxes 9 × 3 × 4 m at y = 4, 11, 18, 25; eleven links alternating beam/dashed with packets; “design output” panel in front.',
      components: ['9 subsystem blocks', '11 interface links', 'Design-output panel'],
      dataflow: 'Each edge is a contract; packets show that contracts carry traffic classes, not just arrows.',
      animation: ['Packets traverse each contract', 'Slow orbit to reveal the tiering'],
      text: 'Activities, artefacts, and the two-team exit test.',
      message: 'Interfaces are the architecture; implementations are replaceable.',
    },
  }),

  P(2, 'Data — collect and generate the fuel', {
    sub: 'Real-world collection campaigns plus simulation-generated data, unified in one versioned platform where any mission can be replayed bit-exactly.',
    scene: 'p2Data',
    stageTag: 'P2 · DATA',
    caption: 'Real collection (left) and simulated/synthetic generation (right) converging into one versioned data platform.',
    left: [
      { h: 'ACTIVITIES', items: ['Flight and drive campaigns for real data', 'Satellite and GIS product acquisition', 'RF / channel measurement campaigns', 'Synthetic data generation in the twin', 'Labelling with quality control'] },
    ],
    right: [
      { h: 'ARTEFACTS', tone: 'ok', items: ['Versioned datasets with lineage', 'Dataset cards: coverage, bias, gaps', 'Replay bundles per mission', 'Labelling guidelines and inter-annotator agreement'] },
      { h: 'EXIT CRITERIA', tone: 'warn', text: 'A named dataset exists for every model planned in P4, with a documented gap analysis against the operating envelope.' },
    ],
    tech: ['MCAP / rosbag2', 'Parquet / Delta', 'DVC / LakeFS', 'Isaac Sim replicator', 'CVAT-style labelling', 'Sionna for RF data'],
    metrics: [['TB/day', 'ingest rate'], ['&gt;0.9', 'inter-annotator agreement'], ['bit-exact', 'replay'], ['&lt;24 h', 'campaign → usable dataset']],
    note: 'Synthetic data is not a shortcut here — it is how rare and dangerous cases become trainable at all.',
    spec: {
      visual: 'Two collection worlds — a warm real city with a flying UAV and a mint simulated city with a swarm — both streaming into a glowing cylindrical data vault.',
      scene3d: 'Real city at x=−18, simulated city at x=+18, vault (r=5, h=4) at (0,2.4,16); two convergent beams with packets; six source-type labels around the vault.',
      components: ['Real collection', 'Synthetic generation', 'Data vault', 'Source-type labels'],
      dataflow: 'Both worlds → vault; the vault is the only path into P4.',
      animation: ['UAV sweeps the real city; swarm patrols the sim city', 'Packets converge into the vault'],
      text: 'Activities, artefacts, and the gap-analysis exit criterion.',
      message: 'The output of this phase is a versioned, replayable dataset — not a folder of recordings.',
    },
  }),

  P(3, 'Digital twin — build it layer by layer, validate each', {
    sub: 'GIS → terrain → buildings → traffic and weather → agents and network. Each layer is validated against measurements before the next is added.',
    scene: 'p3DigitalTwinBuild',
    stageTag: 'P3 · DIGITAL TWIN BUILD',
    caption: 'Five construction stages, left to right, each adding one validated layer.',
    left: [
      { h: 'ACTIVITIES', items: ['Import authoritative geospatial data', 'Generate terrain and building geometry (USD)', 'Add traffic (SUMO) and weather fields', 'Add agents with validated dynamics', 'Add radio propagation on the real geometry'] },
    ],
    right: [
      { h: 'ARTEFACTS', tone: 'ok', items: ['Versioned twin scene of record', 'Per-layer validation report with error numbers', 'Scenario library built on the twin', 'Twin-to-reality comparison harness'] },
      { h: 'EXIT CRITERIA', tone: 'warn', text: 'Geometry &lt; 1 m error, radio &lt; 3 dB error, vehicle dynamics &lt; 10% step-response error — each demonstrated against field measurements.' },
    ],
    tech: ['QGIS / OSM', 'OpenUSD', 'Omniverse', 'Isaac Sim', 'SUMO', 'Sionna RT', 'weather reanalysis data'],
    metrics: [['&lt;1 m', 'geometry error'], ['&lt;3 dB', 'radio error'], ['&lt;10%', 'dynamics error'], ['5', 'validated layers']],
    note: 'Building the twin in validated increments is what prevents a beautiful simulation that teaches the wrong physics.',
    spec: {
      visual: 'Five side-by-side pads showing the twin being assembled: bare GIS grid, terrain, buildings, traffic + weather, then agents + network.',
      scene3d: 'Pads 13 × 13 m at x = −30 … +30, each cumulative; arrows between pads; camera dollies left to right.',
      components: ['5 construction stages', 'Inter-stage arrows'],
      dataflow: 'Each stage inherits the previous and adds exactly one validated layer.',
      animation: ['Traffic moves in stage 4', 'Swarm holds formation in stage 5', 'Lateral camera dolly across the assembly line'],
      text: 'Activities, artefacts, numeric exit criteria.',
      message: 'Fidelity is built and proven incrementally, layer by layer, with numbers.',
    },
  }),

  P(4, 'AI model development — train what the mission needs', {
    sub: 'Perception, prediction, planning, communication optimisation, resource allocation and navigation models, trained on the P2 datasets and P3 twin, then quantised for the edge.',
    scene: 'p4ModelDev',
    stageTag: 'P4 · MODEL DEVELOPMENT',
    caption: 'GPU cluster training with live curves for perception, trajectory, channel and policy models.',
    left: [
      { h: 'ACTIVITIES', items: ['Baseline first: classical method before learning', 'Backbone selection and fine-tuning', 'Uncertainty calibration', 'Quantisation and TensorRT export', 'Offline evaluation on held-out scenarios'] },
    ],
    right: [
      { h: 'ARTEFACTS', tone: 'ok', items: ['Registered model versions with metrics', 'Model cards: data, limits, failure modes', 'Edge-ready engines (INT8/FP8)', 'Comparison against the classical baseline'] },
      { h: 'EXIT CRITERIA', tone: 'warn', text: 'Every model beats a tuned classical baseline on the mission metric, is calibrated (ECE &lt; 0.05), and runs inside its latency and power budget.' },
    ],
    tech: ['PyTorch', 'CUDA', 'TensorRT', 'MLflow / W&B', 'ONNX', 'Optuna', 'model cards'],
    metrics: [['&gt;baseline', 'on mission metric'], ['ECE &lt; 0.05', 'calibration'], ['INT8', 'edge precision'], ['&lt;15 W', 'inference power']],
    note: 'The classical baseline is mandatory. Without it, nobody can tell whether the learning added value or noise.',
    spec: {
      visual: 'A GPU cluster with four live training curves rendered above it, and a UAV and robot receiving/returning artefacts.',
      scene3d: '2 × 5 rack pod; four canvas plots (340 × 190) at y=16 animating a growing loss/metric trace; deploy beam to a UAV, experience link from a robot.',
      components: ['GPU pod', '4 live metric plots', 'Deploy + experience links'],
      dataflow: 'Data → training → candidate model → device; experience returns to the cluster.',
      animation: ['Curves draw progressively and reset (implying successive runs)', 'Packets on both links'],
      text: 'Activities, artefacts, and the baseline-beating exit criterion.',
      message: 'Models are engineering deliverables with budgets and baselines, not research artefacts.',
    },
  }),

  P(5, 'Agentic AI — build agents like software, not prompts', {
    sub: 'Each agent gets an objective, tools with typed schemas, scoped memory, guardrails and full tracing — then a review before it is allowed near the fleet.',
    scene: 'p5AgenticBuild',
    stageTag: 'P5 · AGENT CONSTRUCTION',
    caption: 'Three assembly bays: objective + policy, tools + memory, guardrails + logging.',
    left: [
      { h: 'ACTIVITIES', items: ['Define objective and success test', 'Register tools with schemas and rate limits', 'Scope memory and set retention', 'Add guardrails: envelopes, budgets, veto hooks', 'Red-team the agent against adversarial prompts and states'] },
    ],
    right: [
      { h: 'ARTEFACTS', tone: 'ok', items: ['Agent specification (the seven fields)', 'Tool registry entries', 'Guardrail test suite + red-team report', 'Revocation procedure'] },
      { h: 'EXIT CRITERIA', tone: 'warn', text: 'The agent cannot exceed its envelope even when its model output is adversarial or nonsensical — demonstrated, not asserted.' },
    ],
    tech: ['tool schemas', 'behaviour trees', 'guardrail middleware', 'prompt / policy versioning', 'OpenTelemetry tracing', 'red-teaming'],
    metrics: [['7', 'mandatory spec fields'], ['100%', 'tool calls validated'], ['0', 'envelope escapes in red-team'], ['&lt;1 s', 'revocation']],
    note: 'An agent is a privileged process with tools and authority. It gets the same review as any other privileged process.',
    spec: {
      visual: 'An “agent factory”: three wireframe assembly bays with an agent orb growing in complexity from bay to bay, ending as a certified agent above.',
      scene3d: 'Bays 9 × 8 × 6 m at x = −12, 0, +12 on a violet holo ring; orbs of increasing radius per bay; certified agent at (0,15,−6).',
      components: ['3 assembly bays', 'Progressive agent orbs', 'Certified agent', 'Build checklist panel'],
      dataflow: 'Left to right assembly, then upward to certification.',
      animation: ['Arrows pulse between bays', 'Orbs rotate at increasing rates', 'Certified agent glows steadily'],
      text: 'Activities, artefacts, and the adversarial exit criterion.',
      message: 'Agentic autonomy is a software engineering discipline with review gates.',
    },
  }),

  P(6, 'Multi-agent learning — train the swarm, not the drone', {
    sub: 'Swarm coordination, distributed decision making, federated learning and multi-agent reinforcement learning across many randomised environments in parallel.',
    scene: 'p6MultiAgentLearning',
    stageTag: 'P6 · MULTI-AGENT LEARNING',
    caption: 'Five parallel arenas with different seeds, one shared policy/critic above them.',
    left: [
      { h: 'ACTIVITIES', items: ['Formulate the Dec-POMDP: obs, actions, reward', 'Curriculum from 2 agents to 20+', 'Domain randomisation across cities, wind, demand', 'Federated variant where data cannot be pooled', 'Emergent-behaviour review'] },
    ],
    right: [
      { h: 'ARTEFACTS', tone: 'ok', items: ['Trained joint policies with evaluation matrix', 'Scenario-family performance breakdown', 'Emergent behaviour catalogue (good and bad)', 'Baseline comparison vs classical heuristics'] },
      { h: 'EXIT CRITERIA', tone: 'warn', text: 'The policy beats the tuned heuristic on throughput and coverage, never violates hard constraints, and degrades gracefully when agents are removed.' },
    ],
    tech: ['MADDPG / QMIX / MAPPO', 'Isaac Lab', 'Ray', 'FedAvg', 'domain randomisation', 'curriculum learning'],
    metrics: [['5 → 10⁴', 'parallel environments'], ['2 → 20', 'agents in curriculum'], ['0', 'hard-constraint violations'], ['n−1', 'agents removable without failure']],
    note: 'Emergent coordination is reviewed, catalogued and constrained. “The swarm figured something out” is not an acceptable operational answer.',
    spec: {
      visual: 'Five circular arenas, each with its own mini-city and 5-UAV swarm and its own seed, all connected to a shared policy orb above.',
      scene3d: 'Arenas r=11 at five positions; per-arena swarms with different mesh colours; shared policy orb at (0,26,4) with dashed gradients up and mint policy beams down.',
      components: ['5 seeded arenas', 'Shared policy/critic orb', 'MARL setup panel'],
      dataflow: 'Arenas → experience → shared critic → improved policy → arenas.',
      animation: ['Each swarm behaves slightly differently', 'Gradient packets rise, policy packets descend'],
      text: 'Full activity list, artefacts, and graceful-degradation exit criterion.',
      message: 'Swarm behaviour is trained and audited as a joint policy, with explicit robustness to losing agents.',
    },
  }),

  P(7, 'Simulation — run millions of missions before one flight', {
    sub: 'Thousands of parallel randomised environments produce statistics, not anecdotes: performance distributions per scenario family, with tail behaviour visible.',
    scene: 'p7Simulation',
    stageTag: 'P7 · MASSIVE SIMULATION',
    caption: '49 of 10,000+ parallel environments, each with randomised layout, weather, noise and link quality.',
    left: [
      { h: 'RANDOMISED DIMENSIONS', items: ['Layout, obstacles, user distribution', 'Weather, wind, visibility', 'Sensor noise and calibration drift', 'Link quality, interference, outages', 'Asset failures and energy states'] },
    ],
    right: [
      { h: 'ARTEFACTS', tone: 'ok', items: ['Performance distributions per scenario family', 'Tail analysis: worst 1% of missions', 'Failure catalogue with reproducible seeds', 'Regression suite for every future model'] },
      { h: 'EXIT CRITERIA', tone: 'warn', text: 'Mission success in the worst 1% of scenarios still meets safety criteria, and every discovered failure has a reproducible seed.' },
    ],
    tech: ['Isaac Lab parallel envs', 'CUDA', 'Ray', 'scenario DSL', 'seeded determinism', 'statistical analysis'],
    metrics: [['10⁴–10⁶', 'missions simulated'], ['P99', 'reported, not just mean'], ['100%', 'failures reproducible'], ['seeded', 'determinism'] ],
    note: 'The purpose of massive simulation is to find the tail, not to prove the average.',
    spec: {
      visual: 'A 7 × 7 grid of miniature simulated worlds, each with its own randomised buildings and moving agents — the visual impression of scale.',
      scene3d: '49 groups on a 13 m pitch, each with a glowing pad, 9 procedural buildings and 3 orbiting agent markers, all with independent seeds.',
      components: ['49 environment tiles', 'Per-tile agents', '“Massive simulation” panel'],
      dataflow: 'Each tile independently produces mission statistics that aggregate upward.',
      animation: ['Agents orbit at per-tile rates so the grid never looks synchronised', 'High slow orbit'],
      text: 'Randomised dimensions, artefacts, and the P99 exit criterion.',
      message: 'Statistical evidence over many randomised missions is the only credible pre-flight argument.',
    },
  }),

  P(8, 'Safety validation — break it on purpose', {
    sub: 'GPS denial, link loss, sensor failure, battery degradation, weather, adversarial inputs, satellite outage and UAV loss — each injected deliberately, each requiring a demonstrated safe outcome.',
    scene: 'p8SafetyValidation',
    stageTag: 'P8 · FAULT INJECTION',
    caption: 'Six simultaneous fault injections into a live swarm, each with a required safe response.',
    left: [
      { h: 'FAULT CATALOGUE', tone: 'warn', items: ['GPS denied / spoofed', 'Communication lost (partial and total)', 'Sensor failure and calibration drift', 'Battery degradation and thermal limits', 'Severe weather and wind gusts', 'Adversarial and out-of-distribution inputs', 'Satellite outage', 'Single and multiple UAV loss'] },
    ],
    right: [
      { h: 'REQUIRED RESPONSES', tone: 'ok', items: ['GPS denial → visual-inertial navigation fallback', 'Link loss → autonomous return inside the geofence', 'Sensor fault → degraded but stable policy', 'OOD input → anomaly detector triggers veto', 'Multi-asset loss → mission re-scoped, not abandoned'] },
      { h: 'EXIT CRITERIA', tone: 'warn', text: 'Every fault in the catalogue has an injected test, a recorded outcome and evidence that the safe behaviour occurred within its time budget.' },
    ],
    tech: ['fault injection framework', 'chaos testing', 'adversarial input generation', 'anomaly detectors', 'geofencing', 'formal envelope checks'],
    metrics: [['&lt;1 s', 'detection → safe policy'], ['100%', 'faults with evidence'], ['0', 'unsafe outcomes accepted'], ['8', 'fault families']],
    note: 'This phase is where autonomy earns the right to be trusted. It is also the phase most programmes skip.',
    spec: {
      visual: 'A red-lit swarm over a damaged city with six simultaneous warning rings and labels — “GPS DENIED”, “LINK LOST”, “SENSOR FAILURE”, “BATTERY FAULT”, “WIND GUST”, “ADVERSARIAL INPUT”.',
      scene3d: 'Red-tinted grid and city; 6-UAV swarm at 14 m with red mesh; per-fault pulsing torus rings and floating warning labels attached to individual UAVs.',
      components: ['Fault-injected swarm', '6 warning rings + labels', 'Fault-injection campaign panel'],
      dataflow: 'Fault → detection → safe policy → recorded evidence (stated in the panel).',
      animation: ['Warning rings pulse and scale asynchronously', 'Labels blink', 'Camera keeps the whole swarm in frame'],
      text: 'Fault catalogue vs required responses, plus the evidence-based exit criterion.',
      message: 'Safety is validated by deliberate failure with recorded evidence, not by absence of incidents.',
    },
  }),

  P(9, 'Hardware-in-the-loop — real firmware, simulated world', {
    sub: 'The actual autopilot and the actual compute module run the actual binaries, while sensors and radio are injected from the twin. This is where integration and timing bugs surface.',
    scene: 'p9HITL',
    stageTag: 'P9 · HITL',
    caption: 'Real flight controller and edge GPU on the bench (left) wired to the simulated world (right).',
    left: [
      { h: 'ACTIVITIES', items: ['Bench rig with real autopilot + real edge compute', 'Sensor injection at true rates and formats', 'RF channel emulation from the twin', 'Timing and jitter measurement', 'Fault injection at the hardware level'] },
    ],
    right: [
      { h: 'ARTEFACTS', tone: 'ok', items: ['Timing and jitter report for the real loop', 'Integration defect list (the point of the phase)', 'Repeatable HITL regression suite', 'Firmware + model version pairing matrix'] },
      { h: 'EXIT CRITERIA', tone: 'warn', text: 'The loop meets its rate and jitter budget on real hardware, and every P8 fault scenario reproduces the same safe behaviour with hardware in the loop.' },
    ],
    tech: ['PX4 HITL', 'Jetson on the bench', 'Isaac Sim sensor injection', 'Sionna channel emulation', 'CAN / UART / Ethernet capture', 'timing analysis'],
    metrics: [['&lt;10 ms', 'measured control latency'], ['&lt;1 ms', 'jitter budget'], ['100%', 'P8 scenarios reproduced'], ['1:1', 'firmware/model pairing']],
    note: 'Most “AI failures” in robotics are integration and timing failures. This is the phase that finds them cheaply.',
    spec: {
      visual: 'Split bench scene: an illuminated flight-controller board with components on a lab bench, cabled to a large screen showing the simulated city with a flying UAV.',
      scene3d: 'Bench + board at x=−9 with 14 procedural components; simulation screen 14 × 8 m at x=+10 with an inset live mini-city and UAV; two labelled links (sensor injection, actuator commands).',
      components: ['Real autopilot board', 'Simulated world screen', 'Sensor injection link', 'Actuator command link', 'HITL panel'],
      dataflow: 'Simulated sensors → real hardware → real commands → simulated actuation, closed at real time.',
      animation: ['Packets on both links', 'Mini UAV flies inside the screen', 'Slow parallax drift'],
      text: 'Activities, artefacts, and timing/jitter exit criteria.',
      message: 'Timing parity on real hardware is a prerequisite for flight, and it is cheap to test on a bench.',
    },
  }),

  P(10, 'Controlled field test — one aircraft, bounded volume', {
    sub: 'First contact with reality: a small number of physical agents inside a geofenced test range, with a safety pilot, full telemetry recording and a direct comparison against the twin’s prediction.',
    scene: 'p10FieldTest',
    stageTag: 'P10 · FIELD TEST',
    caption: 'Geofenced volume, one UAV on a repeatable trajectory, ground control with a safety pilot on the stick.',
    left: [
      { h: 'ACTIVITIES', items: ['Repeatable trajectories flown in a bounded volume', 'Sim-to-real gap measurement on the same scenario', 'Sensor and channel calibration against ground truth', 'Progressive envelope expansion', 'Abort-procedure rehearsal'] },
    ],
    right: [
      { h: 'ARTEFACTS', tone: 'ok', items: ['Measured sim-to-real gap per metric', 'Twin corrections fed back to P3', 'Flight-test report with envelope achieved', 'Updated safety case'] },
      { h: 'EXIT CRITERIA', tone: 'warn', text: 'Sim-to-real gap under 15% on mission metrics, zero geofence breaches, and every abort executed within its time budget.' },
    ],
    tech: ['geofencing (independent of the policy)', 'RTK ground truth', 'full-rate telemetry logging', 'safety pilot override', 'flight-test procedures'],
    metrics: [['&lt;15%', 'sim-to-real gap'], ['0', 'geofence breaches'], ['1', 'aircraft at a time'], ['100%', 'flights recorded at full rate']],
    note: 'The purpose is measurement, not demonstration. A field test that only proves it works has wasted the flight.',
    spec: {
      visual: 'A bright daylight test range with a visible cylindrical geofence, one UAV flying a closed repeatable circuit, and a ground control vehicle with two operators.',
      scene3d: 'Geofence cylinder r=22, h=14 with glowing top and bottom rims; Catmull-Rom closed trajectory with a trail and the UAV as marker; GCS van + dish + two humans at (−26,0,18); dashed C2 link.',
      components: ['Geofence volume', 'UAV + flown trajectory', 'Ground control station', 'C2 link', 'Field-test panel'],
      dataflow: 'C2 link (dashed) to the aircraft; telemetry recorded; results compared to twin prediction (stated in panel).',
      animation: ['UAV traverses the trajectory continuously', 'Trail persists to show repeatability', 'Geofence rims glow steadily'],
      text: 'Activities, artefacts, and numeric exit criteria.',
      message: 'The first flights exist to measure the gap between the twin and reality.',
    },
  }),

  P(11, 'Pilot deployment — real mission, real users', {
    sub: 'A limited fleet operating a real mission in a defined district, with full monitoring, agreed abort criteria and a daily review of every intervention.',
    scene: 'p11Pilot',
    stageTag: 'P11 · PILOT',
    caption: 'Pilot district with a small fleet, a satellite backhaul, a working tower and a gateway.',
    left: [
      { h: 'ACTIVITIES', items: ['Operate a real mission at reduced scale', 'Monitor continuously with a human on call', 'Review every intervention within 24 hours', 'Measure operational KPIs against P0 criteria', 'Engage regulators with real evidence'] },
    ],
    right: [
      { h: 'ARTEFACTS', tone: 'ok', items: ['Operational KPI report vs P0 acceptance thresholds', 'Intervention log with root causes', 'Regulatory evidence package', 'Go / no-go recommendation for scale-up'] },
      { h: 'EXIT CRITERIA', tone: 'warn', text: 'KPIs met on real missions, intervention rate trending down, and no safety event that was not already anticipated in P8.' },
    ],
    tech: ['operational monitoring', 'on-call procedures', 'regulatory reporting', 'canary model rollout', 'incident management'],
    metrics: [['&lt;0.1/h', 'interventions per UAV'], ['&gt;90%', 'mission objectives met'], ['0', 'unanticipated safety events'], ['24 h', 'review cadence']],
    note: 'The pilot is where value is measured for the first time — and where the operational culture is actually built.',
    spec: {
      visual: 'A real district ringed in mint, with four UAVs, a ground robot, a live tower, a gateway and a satellite pass overhead.',
      scene3d: 'Terrain 180 m; 120-building city; 4-UAV mesh at 18 m; UGV; tower with coverage; gateway at (−30,0,22); satellite at (18,44,−14) with a feeder beam; district ring r=25.',
      components: ['Pilot district ring', 'Limited fleet', 'Live network', 'Satellite backhaul', 'Pilot panel'],
      dataflow: 'Satellite feeder → gateway; fleet mesh; all telemetry to operations.',
      animation: ['Fleet operates continuously', 'Feeder beam packets', 'Slow wide orbit'],
      text: 'Activities, artefacts, exit criteria.',
      message: 'Scale-up is earned with measured operational evidence, not with a successful demo.',
    },
  }),

  P(12, 'Continual learning — the loop that makes it an infrastructure', {
    sub: 'Field data returns, hard cases are mined first, candidates are retrained, re-validated through the whole gate stack, and rolled out as canaries with a rollback always one command away.',
    scene: 'p12ContinualLearning',
    stageTag: 'P12 · CONTINUAL LEARNING',
    caption: 'Field operations → ingest → label/mine → retrain → re-validate → roll out → back to the field.',
    left: [
      { h: 'ACTIVITIES', items: ['Prioritise data the models got wrong', 'Active learning and hard-case mining', 'Retrain candidates against the regression suite', 'Re-run P7–P9 gates automatically', 'Canary rollout with KPI monitoring'] },
    ],
    right: [
      { h: 'DISCIPLINE', tone: 'warn', items: ['Never retrain without re-validating', 'Never roll out to the whole fleet at once', 'Never lose the ability to roll back', 'Never discard a failure case'] },
      { h: 'EXIT CRITERIA', tone: 'ok', text: 'A new mission’s data can produce a validated candidate model within 24 hours, and rollback completes in under a minute.' },
    ],
    tech: ['active learning', 'automated regression suites', 'model registry', 'canary deployment', 'drift detection', 'OTA update with rollback'],
    metrics: [['&lt;24 h', 'mission → candidate'], ['&lt;60 s', 'rollback'], ['100%', 'candidates re-validated'], ['&gt;1', 'improvement per mission batch']],
    note: 'This loop is the difference between a system that ages and a system that compounds.',
    spec: {
      visual: 'Field operations on the left feeding a five-station learning chain above right, with an improved policy arcing back to the field.',
      scene3d: 'Field city + 4-UAV swarm at x=−22; five chain stations at y=18 spaced 6.2 m; dashed experience link up, sagging mint policy beam back down.',
      components: ['Field operations', '5-station learning chain', 'Experience link', 'Policy return beam', 'Discipline panel'],
      dataflow: 'Field → ingest → mine → retrain → re-validate → roll out → field.',
      animation: ['Packets step through the chain', 'Return beam carries the improved policy back'],
      text: 'Activities, the four “never” rules, and the 24-hour exit criterion.',
      message: 'Compounding improvement requires automated gates, canaries and instant rollback.',
    },
  }),

  P(13, 'Autonomous operation — sense, learn, reason, plan, act, observe, adapt', {
    sub: 'Steady state: the platform runs continuously, decides locally, escalates rarely, and improves from every hour it operates.',
    scene: 'p13AutonomousOperation',
    stageTag: 'P13 · AUTONOMOUS OPERATION',
    caption: 'Live city operations under the seven-stage continuous loop.',
    left: [
      { h: 'STEADY-STATE BEHAVIOUR', items: ['Continuous sensing across space, air and ground', 'Local decisions at the edge, global coordination above', 'Human attention spent only on genuine judgement calls', 'Model versions rolling forward under monitoring'] },
    ],
    right: [
      { h: 'WHAT “AUTONOMOUS” MEANS HERE', tone: 'ai', items: ['<b>Not</b> unsupervised — bounded and observable', '<b>Not</b> static — continuously retrained', '<b>Not</b> opaque — every decision traceable', '<b>Not</b> fragile — degrades level by level'] },
      { h: 'OPERATING TARGETS', tone: 'ok', kv: [['availability', '&gt; 99% of mission windows'], ['interventions', '&lt; 0.1 per UAV-hour'], ['adaptation', 'new policy per mission batch'], ['safety', 'zero unrecoverable assets']] },
    ],
    tech: ['multi-region operations', 'observability stack', 'automated assurance', 'continuous certification evidence'],
    metrics: [['24/7', 'operation'], ['&gt;99%', 'availability'], ['&lt;0.1/h', 'interventions'], ['7', 'loop stages']],
    note: 'This is the destination: an infrastructure that senses, understands, reasons, learns, plans, acts, observes and adapts without stopping.',
    spec: {
      visual: 'A fully operational city — swarm, robots, satellite, traffic — under a luminous seven-node ring reading SENSE, LEARN, REASON, PLAN, ACT, OBSERVE, ADAPT.',
      scene3d: 'City 56 m with vehicles; 9-UAV mesh at 17 m; two UGVs; a translating satellite; seven ring nodes at y=30 on radius 20 (Z 0.5) linked by curved beams.',
      components: ['Live operations', '7-stage loop ring', 'Satellite pass'],
      dataflow: 'The ring is the control loop; the city below is its subject.',
      animation: ['Loop packets circulate', 'Fleet and traffic operate continuously', 'Satellite translates overhead'],
      text: 'Steady-state behaviour and the four “not”s that define bounded autonomy.',
      message: 'Autonomy in production means bounded, observable, continuously improving operation — not the absence of humans.',
    },
  }),
];
