const U = (variant, n, title, o) => ({
  kicker: `USE CASE ${n} / 10`,
  title,
  badge: `UC${n}`,
  scene: 'useCase',
  sceneOpts: { variant },
  diagram: {
    type: 'chain',
    title: 'PROBLEM → AI DECISION → PHYSICAL ACTION → RESULT',
    bh: 76,
    items: [
      { t: 'PROBLEM', s: o.problem, cls: 'bad' },
      { t: 'AI DECISION', s: o.decision, cls: 'ai', e: '→' },
      { t: 'PHYSICAL ACTION', s: o.action, cls: 'accent', e: '→' },
      { t: 'RESULT', s: o.result, cls: 'ok', e: '→' },
    ],
  },
  diagramLead: true,
  ...o,
});

export const USECASES = [
  U('disaster', 1, 'Disaster response', {
    sub: 'The sharpest case: no infrastructure, no map, no time. Space provides the picture, air provides the network, ground provides the reach.',
    problem: 'infrastructure destroyed, situational awareness zero, minutes matter',
    decision: 'classify event, rank priority zones, allocate relay + search roles',
    action: 'UAV relay lattice + LiDAR mapping + UGV search in rubble',
    result: 'usable network in <10 min, live damage map, survivors located',
    stageTag: 'DISASTER RESPONSE',
    left: [{ h: 'WHY THE PLATFORM WINS', items: ['One system covers detection, comms, mapping and search', 'Works with zero surviving ground infrastructure', 'Every decision is logged for the post-event inquiry'] }],
    right: [{ h: 'BUYER', tone: 'ai', items: ['National disaster agencies', 'Telecom operators with resilience mandates', 'Civil protection and military support units'] }],
    metrics: [['&lt;10 min', 'to first link'], ['92%', 'priority coverage'], ['3', 'domains coordinated']],
    note: 'Disaster response is the proving ground: if the architecture works here, the commercial cases are easier versions of the same problem.',
    spec: { visual: 'Damaged city with a working swarm, three ground robots and a satellite overhead.', animation: ['Swarm mesh reconfigures; robots traverse the rubble'], message: 'Cross-domain autonomy converts a blackout into a managed operation.' },
  }),

  U('telecom', 2, 'Telecommunications — coverage on demand', {
    sub: 'Aerial base stations and RIS turn coverage into something that can be deployed in minutes and moved as demand moves.',
    problem: 'cell outage, event-driven demand spikes, shadowed streets, rural gaps',
    decision: 'predict demand and channel quality, choose altitude, power, RIS phases',
    action: 'UAV takes station as an aerial base station; RIS reconfigures',
    result: 'coverage and capacity restored, users served, SLA maintained',
    stageTag: 'TELECOMMUNICATIONS',
    left: [{ h: 'WHY NOW', items: ['3GPP NTN makes non-terrestrial access standard, not exotic', 'RIS makes blocked geometry recoverable without new sites', 'Operators are measured on resilience, not just peak speed'] }],
    right: [{ h: 'BUYER', tone: 'ai', items: ['Mobile network operators', 'Neutral-host and tower companies', 'Event and industrial private-network providers'] }],
    metrics: [['minutes', 'to deploy coverage'], ['&gt;100 Mb/s', 'aggregate capacity'], ['+86%', 'throughput after optimisation']],
    note: 'This is the most direct commercial path: the same platform, sold as coverage-as-a-service.',
    spec: { visual: 'City with one dead tower, an aerial base station with a wide mint coverage cone, an RIS panel and connected users.', animation: ['Coverage cone breathes; RIS elements shimmer'], message: 'Coverage becomes a deployable, steerable resource.' },
  }),

  U('agriculture', 3, 'Agriculture — decisions per square metre', {
    sub: 'Satellite for the field, UAV for the plant, robot for the action — with the twin holding the crop history that makes each intervention justifiable.',
    problem: 'stress, disease and irrigation faults are found too late and treated uniformly',
    decision: 'fuse multispectral + weather + history; localise stress; choose treatment',
    action: 'UAV surveys and targets; ground robot treats only the affected rows',
    result: 'yield protected, input use and cost down, full treatment audit trail',
    stageTag: 'AGRICULTURE',
    left: [{ h: 'PLATFORM REUSE', items: ['Same sensing and twin stack, different payload and policy', 'Satellite revisit for field scale, UAV for plant scale', 'Traceability satisfies food-safety and subsidy audits'] }],
    right: [{ h: 'BUYER', tone: 'ai', items: ['Large-scale growers and cooperatives', 'Agrochemical and equipment manufacturers', 'Government agricultural agencies'] }],
    metrics: [['cm-scale', 'intervention resolution'], ['−30–60%', 'input use (targeted vs uniform)'], ['days → hours', 'detection latency']],
    note: 'Agriculture is where the economics of autonomy are easiest to prove: inputs saved are directly measurable.',
    spec: { visual: 'Grid of crop plots colour-coded by health, a UAV flying a survey lawnmower pattern with a green sensing cone, and a ground robot treating a strip.', animation: ['UAV follows the survey path; robot traverses the rows'], message: 'Per-square-metre decisions, executed by the right machine.' },
  }),

  U('logistics', 4, 'Logistics — air and ground last mile', {
    sub: 'One planner allocates parcels across UAVs and autonomous vehicles based on weight, distance, weather, airspace and energy.',
    problem: 'last-mile cost dominates, terrain and traffic break schedules, demand is spiky',
    decision: 'joint air/ground assignment under weather, airspace and energy constraints',
    action: 'UAVs fly light urgent parcels; autonomous vans carry the heavy tail',
    result: 'delivery time and cost reduced, schedule robust to traffic and weather',
    stageTag: 'LOGISTICS',
    left: [{ h: 'WHAT IS HARD', items: ['Airspace authorisation, not aerodynamics', 'Energy planning with wind and payload coupling', 'Handover between air and ground modes', 'Recharging as a scheduled resource'] }],
    right: [{ h: 'BUYER', tone: 'ai', items: ['Logistics and courier operators', 'Hospital and laboratory networks', 'Island and remote-community services'] }],
    metrics: [['air+ground', 'joint optimisation'], ['−20–40%', 'last-mile cost in favourable geographies'], ['minutes', 'urgent medical delivery']],
    note: 'The interesting problem is allocation across modes, not the drone itself — which is exactly what this platform is built for.',
    spec: { visual: 'A fulfilment hub with stacked parcels, four UAVs on curved delivery arcs to landing pads, and an autonomous van on the road grid.', animation: ['UAVs traverse their delivery arcs; van drives the loop'], message: 'Last mile is a joint air/ground allocation problem.' },
  }),

  U('inspection', 5, 'Infrastructure inspection', {
    sub: 'Power lines, pipelines, bridges, railways and wind farms surveyed autonomously, with defect history in the twin instead of in an engineer’s notebook.',
    problem: 'manual inspection is slow, dangerous, inconsistent and rarely repeatable',
    decision: 'plan the corridor, detect anomalies, compare against previous surveys',
    action: 'UAV flies a repeatable corridor with camera, thermal and LiDAR payloads',
    result: 'defects ranked by severity and trend, maintenance scheduled before failure',
    stageTag: 'INFRASTRUCTURE INSPECTION',
    left: [{ h: 'WHY REPEATABILITY MATTERS', items: ['The signal is the <b>change</b> between surveys, not one image', 'Same trajectory + same twin frame = comparable data', 'Trend data enables predictive maintenance, not just reporting'] }],
    right: [{ h: 'BUYER', tone: 'ai', items: ['Transmission and distribution utilities', 'Oil, gas and water pipeline operators', 'Rail and highway authorities', 'Wind farm operators'] }],
    metrics: [['cm-level', 'defect localisation'], ['repeatable', 'trajectory-to-trajectory comparison'], ['−50%+', 'inspection cost vs manual crews']],
    note: 'The value is a time series of a physical asset. That is a data-platform problem with a flying sensor attached.',
    spec: { visual: 'Five pylons with catenary conductors, a UAV flying a closed inspection circuit with a camera frustum, and a pulsing hotspot warning.', animation: ['UAV traverses the corridor loop; hotspot label pulses'], message: 'Autonomous inspection produces comparable time series, not photographs.' },
  }),

  U('sar', 6, 'Search and rescue', {
    sub: 'Wide-area thermal and RF search over terrain that ground teams cannot cover, with detections localised well enough to act on.',
    problem: 'search areas are enormous, terrain is hostile, survival windows are short',
    decision: 'plan coverage under terrain and weather; fuse thermal, acoustic and RF cues',
    action: 'UAV swarm sweeps assigned sectors; UGV investigates confirmed hits',
    result: 'search time collapsed, detections localised to a few metres, teams directed',
    stageTag: 'SEARCH & RESCUE',
    left: [{ h: 'SENSOR FUSION', items: ['Thermal for bodies, RF for phones and beacons', 'Acoustic for calls in voids', 'Terrain-aware coverage planning (shadowed valleys first)', 'False-positive suppression before a team is dispatched'] }],
    right: [{ h: 'BUYER', tone: 'ai', items: ['Mountain rescue and coastguard services', 'Civil protection agencies', 'Military SAR units'] }],
    metrics: [['&lt;2 m', 'detection localisation'], ['hours → minutes', 'sector search time'], ['multi-sensor', 'confirmation before dispatch']],
    note: 'The metric that matters is not detections but confirmed detections per team-hour spent.',
    spec: { visual: 'Mountain terrain with a six-UAV mesh, alternating thermal/visual sensing cones, three pulsing detection markers and a robot climbing toward one.', animation: ['Detection markers bob and pulse; robot advances'], message: 'Wide-area autonomous search with confirmation before human dispatch.' },
  }),

  U('smartcity', 7, 'Smart cities', {
    sub: 'Traffic, energy, safety and environmental monitoring treated as one control problem over a live city twin.',
    problem: 'city subsystems are instrumented separately and optimised against each other',
    decision: 'fuse fixed sensors, vehicles and aerial survey into one twin; predict and coordinate',
    action: 'signal timing, patrol routing, aerial survey and maintenance dispatch',
    result: 'congestion, response times and energy waste reduced measurably',
    stageTag: 'SMART CITY',
    left: [{ h: 'WHAT IS DIFFERENT HERE', items: ['The twin already exists — the city is the customer', 'Privacy is the primary constraint, not bandwidth', 'Aerial assets fill the gaps fixed sensors leave'] }],
    right: [{ h: 'BUYER', tone: 'ai', items: ['Municipal governments', 'Utilities and transport authorities', 'Public safety agencies'] }],
    metrics: [['one twin', 'multiple departments'], ['federated', 'learning to preserve privacy'], ['&lt;5 min', 'map freshness']],
    note: 'Smart-city projects fail on integration and privacy. This architecture addresses both structurally: one twin, federated learning.',
    spec: { visual: 'Dense city with moving traffic, 22 pulsing IoT sensor nodes, a four-UAV patrol and live towers.', animation: ['Traffic flows; sensors pulse; patrol orbits'], message: 'City-scale coordination on a shared twin with privacy-preserving learning.' },
  }),

  U('maritime', 8, 'Maritime monitoring', {
    sub: 'Satellite SAR plus AIS plus aerial verification: detect vessels that do not want to be detected, over areas no patrol can cover.',
    problem: 'vast areas, sparse patrols, AIS can simply be switched off',
    decision: 'correlate SAR detections with AIS tracks; flag unmatched vessels; task verification',
    action: 'UAV or vessel dispatched to verify the highest-confidence anomaly',
    result: 'dark vessels identified, illegal activity evidenced, patrols used efficiently',
    stageTag: 'MARITIME MONITORING',
    left: [{ h: 'FUSION LOGIC', items: ['SAR sees hulls regardless of cooperation', 'AIS says who is declaring themselves', 'A detection without a track is the interesting object', 'Aerial verification converts suspicion into evidence'] }],
    right: [{ h: 'BUYER', tone: 'ai', items: ['Coastguards and fisheries agencies', 'Port authorities', 'Environmental protection bodies', 'Naval forces'] }],
    metrics: [['km²-scale', 'coverage per satellite pass'], ['SAR+AIS', 'correlation for dark-vessel detection'], ['hours → minutes', 'anomaly to verification tasking']],
    note: 'This use case is almost pure data fusion — the physical assets exist only to verify what the fusion already suspects.',
    spec: { visual: 'Open sea with a swell wireframe, three vessels (one flagged “AIS DARK VESSEL”), a patrolling UAV with a sensing cone and a satellite with a SAR detection link.', animation: ['Vessels traverse; swell rolls; UAV orbits the area of interest'], message: 'Satellite detection plus aerial verification beats patrol coverage.' },
  }),

  U('industrial', 9, 'Industrial automation', {
    sub: 'Continuous autonomous inspection inside plants, refineries and yards, where the same rounds are walked by people today.',
    problem: 'manual rounds are infrequent, inconsistent and sometimes hazardous',
    decision: 'schedule rounds, detect thermal/gas/vibration anomalies, predict failures',
    action: 'UAV flies the elevated route; UGV covers ground level and confined areas',
    result: 'earlier fault detection, fewer human entries into hazardous zones',
    stageTag: 'INDUSTRIAL AUTOMATION',
    left: [{ h: 'CONSTRAINTS', items: ['GPS-denied and cluttered interiors', 'Explosive-atmosphere zoning restrictions', 'Fixed asset registers that must be matched exactly', 'Existing SCADA systems that must be integrated, not replaced'] }],
    right: [{ h: 'BUYER', tone: 'ai', items: ['Refineries and chemical plants', 'Mines and steelworks', 'Ports, yards and large warehouses', 'Power generation sites'] }],
    metrics: [['continuous', 'vs periodic rounds'], ['GPS-denied', 'navigation required'], ['−human entries', 'into hazardous zones']],
    note: 'Industrial sites are where GPS-denied autonomy and asset-register discipline matter more than range or speed.',
    spec: { visual: 'Plant with six tanks (one showing a thermal anomaly), pipe runs, a UAV orbiting above and a robot patrolling at ground level.', animation: ['Anomaly label pulses; UAV and robot follow independent routes'], message: 'Continuous autonomous inspection inside GPS-denied industrial environments.' },
  }),

  U('defense', 10, 'Defence and security', {
    sub: 'Persistent ISR across a monitored boundary, with detection and classification automated and every action requiring human authority.',
    problem: 'long boundaries, sparse sensors, alert fatigue, contested communications',
    decision: 'fuse ground sensors, aerial and satellite data; classify and rank tracks',
    action: 'aerial assets re-task to verify; findings escalated to a human decision',
    result: 'higher detection confidence, fewer false alarms, human authority preserved',
    stageTag: 'DEFENCE / SECURITY',
    left: [{ h: 'NON-NEGOTIABLE CONSTRAINTS', tone: 'warn', items: ['Human authorisation required for any action against a track', 'Full audit trail of every automated classification', 'Operation under jamming and degraded GNSS', 'Data residency and classification handling'] }],
    right: [{ h: 'BUYER', tone: 'ai', items: ['Border and infrastructure security agencies', 'Defence ISR programmes', 'Critical national infrastructure operators'] }],
    metrics: [['persistent', 'coverage vs periodic patrol'], ['100%', 'actions human-authorised'], ['contested', 'comms and GNSS assumed']],
    note: 'The platform is explicitly a sensing, communication and decision-support infrastructure. Authority over any use of force stays with humans, by architecture.',
    spec: { visual: 'Boundary line with posts, unattended ground sensors, a five-UAV high-altitude mesh with wide sensing cones and a flagged track requiring human decision.', animation: ['Sensors pulse; track label pulses; satellite links dashed'], message: 'Persistent ISR with automated classification and mandatory human authority.' },
  }),
];
